### ISSUE TITLE
Demo/New game related: Outline and document a production workflow for sprite creation

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#1051]
This is a summary of the discussion in #1050

That talk has shone a light on one of the most fundamental things that needs to be tackled for a new game: There really needs to be a simple, straightforward and nicely documented production workflow to allow character and monster sprites to be imported in game. Currently there isn't anything stopping anyone because there are a multitude of Infinity Engine BAM editors that can facilitate the task, but sadly the process is laborious and unpleasant.

The general idea is something like this (using Blender as the example because it is open source and also great):

1: Model is created and animated in Blender. 

- This part ideally shouldn't require any special consideration for GemRB, any model should work. If you can make a traffic cone that breakdances, you should be able to import it to GemRB without hard work.

2: A Blender sprite export plugin generates the orientations and animation sequences as PNG files

- PNG files are ideal because they can be saved with the x,y offset from the sprite origin, which is basically the most tedious job, and can hopefully be banished forever. The big question is, is that information easy to calculate in Blender.

- m7600 gave helpful example of a blender render script used in [Flare](https://flarerpg.org/), at the end of this page: http://clintbellanger.net/articles/isometric_tiles/

- The bones of the script seem to be there, but it needs to be expanded to render and export a whole animation sequence or even set of sequences 

- It's probably fine to use the maximum possible number of angle orientations in all cases, since memory is no concern these days.

3: A script for iesh compiles them into BAM files with a standard naming convention that GemRB recognises

- iesh should already be able to take care of the dirty work using the bam_composer script
https://github.com/gemrb/iesh/blob/master/bam_composer
https://github.com/gemrb/iesh/blob/master/infinity/bam_composer.py#L19

4: A new animation type is created to use the new sprites

- Which tables and what code relates to this, and if it is not straightforward can it be streamlined?

- Does the eventual requirement to externalise character animations factor into this? ( #93 )

Obviously it's a big challenge, but hopefully this defines the basic outline of the mission.

**Comment by lynxlynxlynx** [comment]
0. We need a blender project file with the base scene set up, so artists can start to work immediately.

What do you mean with offset talk at PNG?
The script does seem to export whole animations already. But it does need to be changed to 22.5° slices.
Saving files for all orientations is pointless, since we wouldn't read them anyway. Orientations get mirrored, so for the detailed case, we only need about half of them. But it does depend on the chosen animation type.
There's no need for a new animation type — we have too many already.

**Comment by m7600** [comment]
Here is [the empty blender project file](https://github.com/m7600/GemRB-demo-extension/blob/main/empty_start.blend) with everything set up. 
And here is the [work-in-progress blender file for the orc](https://github.com/m7600/GemRB-demo-extension/blob/main/orc_basic.blend).
You will notice that I changed the angle to -22.5 in the script like lynx suggested.

Ideally, we would export the images as .png, and Blender can certainly do this. However, for some weird reason, Bam Workshop 2 and .png files don't get along together very well. So we have to change the output to .bmp. This will be a problem, as explained later. For now, take a look at this screenshot:

![Screenshot from 2020-11-14 16-47-23](https://user-images.githubusercontent.com/56371872/99156124-48eacb00-269d-11eb-9c3c-bcaaa5577623.png)

I couldn't get iesh to run, it's throwing an error (I can say more about that later). It's possible to use NearInfinity for creating the .bam files. We go to Tools -> Convert -> BAM Converter. Then we add frames, use Shift-Click for selecting all of them from start to end after the window opens. Then, shift click all of them and enter an integer for Center X and Center Y. Since the frames I'm using here are 128 x 128, I choose 64 for both Center X and Center Y. Finally, save the output .bam file.

![Screenshot from 2020-11-14 16-59-35](https://user-images.githubusercontent.com/56371872/99156257-32913f00-269e-11eb-97e1-f875243036ce.png)

The next step is brutal, and it should be automatized in some way. Open Bam Worshop, open the .bam file we just generated, and you will have to replace the black background with transparency, for each frame, one by one. This is the inconvenience of working with .bmp files instead of .png, since .bmp does not save transparency. But the problem of exporting all of the frames as .png is that for some weird reason, Bam Worshop doesn't recognize them. It loads them, but they're entirely blank.

![Screenshot from 2020-11-14 17-03-07](https://user-images.githubusercontent.com/56371872/99156294-9a478a00-269e-11eb-8156-b5bfa7390561.png)

Here is the result in-game:

![Screenshot from 2020-11-14 17-04-23](https://user-images.githubusercontent.com/56371872/99156307-b1867780-269e-11eb-9bd1-adfb0827229c.png)

A note on naming conventions. These .bam files for monsters and characters have, for lack of better terms, a prefix and a suffix. In the case of the protagonist, the prefix is ZHMW1 , this is defined in avatars.2da. The suffixes are many, for example WK means "walk", so the full name for the walk animation file is ZHMW1WK.BAM. That is in fact what I used for this orc, because I didn't make a new .CRE file here, I simply replaced the animations for the protagonist.

**Comment by m7600** [comment]
BTW the Offset Y is wrong, instead of making it 64, it should probably be 128, since the green circle appears in the middle of the character right now.

**Comment by chilvence** [comment]
> What do you mean with offset talk at PNG?

Sorry, I didn't really word it that well, I was thinking of two things, first I kind assumed that the sprites would be cropped to just what is actually visible. At that point, the individual offset from the foot circle origin would be a pain to adjust. Ideally both things could be automated.

> Saving files for all orientations is pointless, since we wouldn't read them anyway. Orientations get mirrored, so for the detailed case, we only need about half of them. But it does depend on the chosen animation type.

I actually thought a lot of the BG2 sprites had full rotation sets, wasn't there an option in the original to choose whether or not to use them? Although, I can't seem to find any when I actually look for them...

> There's no need for a new animation type — we have too many already.

I think I meant to say animation ID, like an entry in avatars.2da - I'm not totally sure what the full process you have to go through to create a new animation set is, but if there is a guide or tutorial somewhere at the end of this, it should spell it out there I'd say. 

@m7600 does NearInfinity do better with importing PNG files? Is BAM workshop better in any way in particular?

I'm just wondering, other than actually composing the bam files, is there any feature of either that you find yourself needing to use, or would they both be redundant if we could create a simple bam import script in iesh? Can you elaborate on the error you are getting from it?

Also, looking at your screenshots, another potentially awkward thing occurred to me, how do we go about generating shadows?

**Comment by m7600** [comment]
Good catch about the shadows, I'll take a look.

About the .png files: The problem seems to be more serious than what I said before. png files don't seem to get along well with .bam files in general. It could be a mistake on my part, of course. But every program that I used for editing .bam files (DLTCEP, Bam Workshop, NearInfinity) does weird things to the .pngs when you try to convert them into a .bam. Sometimes it doesn't recognize them. Sometimes it creates stray pixels and artifacts. Sometimes the program crashes altogether. I will have to investigate more. 
About BAM Workshop, the only advantage that it has over NearInfinity in this specific issue about .bam files is that it has a built-in pixel editor for if you have to make some small pixel surgery to some frame or another, so that you don't have to export everything again from Blender.

The error from iesh that I got is that it can't find a module:

```
Traceback (most recent call last):
  File "/usr/local/bin/iesh", line 34, in <module>
    from infinity.formats import *
  File "/usr/local/lib/python2.7/dist-packages/infinity/formats/__init__.py", line 6, in <module>
    import bam
  File "/usr/local/lib/python2.7/dist-packages/infinity/formats/bam.py", line 23, in <module>
    import PIL
ImportError: No module named PIL

```

**Comment by lynxlynxlynx** [comment]
In the originals the shadows were either baked in or they used a shared one (pcs — CSHD and bg1 Sarevok his own). I don't think there's any benefit to having them separate, it was clearly a shortcut for them.

PIL: well install it then. :)

Animation ids are arbitrary. But you're right chiv, there are separate east files for several animation types.

With -22.5°, are some orientations (directions) missing then? I see you still create only 8.

**Comment by m7600** [comment]
lynx: Yes, this was just a test, some orientations are missing.

**Comment by chilvence** [comment]
Regarding PIL, you might specifically have to install the version for python 2.7, just looking at the error readout

**Comment by lynxlynxlynx** [comment]
Actually we will have problems with shadows ... but in the first area instead. It has a dawn/dusk sun angle, so shadows are long. Much too long if you want to create a shadow that works everywhere. So designers of these games had to make a deliberate decision to limit light angles to near vertical.

**Comment by m7600** [comment]
Actually I'm not sure that it's missing orientations. I just checked the original ZHMW1WK.BAM that is bundled with the demo, and the protagon has only 8 sequences (orientations) for the walking animation.

**Comment by m7600** [comment]
Here is a model for a basic human male. I used MakeHuman so that I didn't have to make the body from scratch, but I did make the clothes and props (belt, etc.) with Blender:

![Screenshot from 2020-11-15 22-15-38](https://user-images.githubusercontent.com/56371872/99203180-7bc1bb80-2790-11eb-8a39-166d87883b53.png)

I've made some progress in regards to the process of generating the .bam files. From Blender, you can export each "sequence" ("orientation", "cycle", these terms designate the same thing) as an .avi file. This is much more convenient. Instead of having a billion individual .bmp files, you can have less than ten .avi files:

![Screenshot from 2020-11-15 22-02-04](https://user-images.githubusercontent.com/56371872/99202653-93984000-278e-11eb-9950-ad447ba894be.png)

Here is where Bam Worshop, despite being a very modest program, has a notable advantage over NearInfinity and DLTCEP: it can read .avi files.

![Screenshot from 2020-11-15 22-08-04](https://user-images.githubusercontent.com/56371872/99202823-39e44580-278f-11eb-8783-99532350a2a3.png)

And this solves another problem, one that I mentioned in a previous post: how do we make the black background transparent? With the old method, you had to do this manually for each frame, with a bucket fill. But now it's as simple as going to _Colors -> Convert to Paletted_.

![Screenshot from 2020-11-15 22-10-50](https://user-images.githubusercontent.com/56371872/99202952-b70fba80-278f-11eb-8f7e-2a2e849b44af.png)

The result is applied to all frames at the same time:

![Screenshot from 2020-11-15 22-11-21](https://user-images.githubusercontent.com/56371872/99203037-f8a06580-278f-11eb-966e-4917c62cfc99.png)

**Comment by m7600** [comment]
The next step involves DLTCEP, because Bam Workshop has a problem handling several cycles created by different .avi files (it screws up the colors somewhat). So, having each cycle with their new transparent backgrounds, we open DLTCEP, Edit Bam, and then we load the first cycle. Then we use "Merge BAM" in order to put all of the cycles into a single .bam file.

![Screenshot from 2020-11-15 22-48-15](https://user-images.githubusercontent.com/56371872/99204683-2f2caf00-2795-11eb-81ad-7928f08f235c.png)

The result in game:

![Uploading Screenshot from 2020-11-15 22-42-47.png…]()

**Comment by lynxlynxlynx** [comment]
Orientations: you'll see they're missing by moving around. It looks fine in the new model though.

Can you create a new page on the wiki and start documenting there? So it's all in one place and easily editable (let me know if you need more access):
https://github.com/gemrb/gemrb/wiki

Isn't it a bit dangerous to use black as the future transparency?
There's an outline in the resulting bam. Is there some blending on the border being done on export? It needs to be crisp to be completely removed.
The actor is slightly too big (tall) as well — I suggest you shrink him a bit.

**Comment by m7600** [comment]
[Done](https://github.com/gemrb/gemrb/wiki/Production-workflow-for-sprite-creation). It needs a lot of work still, but I've decided to cut out BAM Workshop from the equation. Everything can now be done using only DLTCEP.

**Comment by lynxlynxlynx** [comment]
Thanks, I'll link it from the website.
Another possible cause for the undesired borders — when downsizing images one must not use any interpolation.

**Comment by chilvence** [comment]
Nice, that's actually looking less complicated than I expected it to be

I think it would be good if there was a sample blend file on that page, so that people can load a working example to follow from - although I understand if you aren't finished with these models, even an empty template would be very handy to get started with.

I have some stuff I need to clear off my plate first, but when I get a chance I will reinstall blender and see if I can streamline the steps in any way

**Comment by lynxlynxlynx** [comment]
He linked it above, just copy it over.

**Comment by chilvence** [comment]
Beg your pardon, I didn't notice the link

I luckily have some old character models I made years ago to play with , managed to import one and get some test renders quite easily.

I am pretty confident I can turn this into a decent production line.

**Comment by m7600** [comment]
Do you guys think that the 3d models should be bundled with GemRB? It might be too much memory. Maybe have them hosted on opengameart.org, or perhaps in another repository for art source files [here](https://github.com/gemrb).

**Comment by chilvence** [comment]
I would personally vote that any source material for the demo should be in a repository so that people can look at it and learn from it use it as reference, tweak and improve it etc, just not the main game repository so that it doesn't bloat the game packages.

**Comment by lynxlynxlynx** [comment]
We can create a new repo, sure, but I don't think it's needed yet. Might be soon though, considering how excited everyone is. The point of the demo is *demo*nstration of our engine's main capabilities, so people can get a quick idea what it's about. For that, the final assets are enough — they can be changed themselves.

**Comment by m7600** [comment]
I made a standing animation for a basic human male. I'm not entirely satisfied with the result, but if you want to take a look at it, you can download it [here](https://github.com/m7600/GemRB-demo-extension/blob/main/BHMSD.bam).

**Comment by lynxlynxlynx** [comment]
Uff, that's very coarse, like there were only 4 frames per cycle. He also moves in a few frames. Transparency/edges are now ok. Arms need to be at less of an angle — nobody stands like that. Size is much better now. The bam center needs to be set lower to the ground, so the foot circle will be placed correctly.

**Comment by m7600** [comment]
@lynxlynxlynx Thanks for the feedback, I'll try to fix it. Here is the [walk animation](https://github.com/m7600/GemRB-demo-extension/blob/main/bhmwk.bam) for the basic human male. It's not optimal, and I haven't fixed the bam center yet.

Should I open a new issue for these work in progress animations?

**Comment by lynxlynxlynx** [comment]
Yes, let's keep this issue for its nominal topic. Open a new one when you need specific feedback.

**Comment by m7600** [comment]
Ok. Link to [#1078](https://github.com/gemrb/gemrb/issues/1078) for discussing the art assets. 

Regarding the production workflow for sprite creation, the ideal solution would be to export the .bam files directly from Blender. I'm not entirely sure that this can be done with a Python script. But I'll see if I can adapt iesh's BAM Converter and integrate it to Blender.

**Comment by lynxlynxlynx** [comment]
We can do that part, so since you're the artist, it's better if you focus on the the data itself.

**Comment by lynxlynxlynx** [comment]
With the latest release, NI has a great animation viewer, so figuring out what does what should be possible without checking the code. Should also help with some of the weirder corner cases. Screenshots in the changelog:
http://www.shsforums.net/topic/45358-nearinfinity/page-52#entry610929

**Comment by lynxlynxlynx** [comment]
Now that we have BAM2 support, this is much easier. No need to muck with limited palettes and there are stitchers like our old bam_composer that support plaintext frame+coordinate specification for each cycle.
https://github.com/Beamdog/bgfileformats/blob/master/bam.go is just one
