### ISSUE TITLE
[subviews] 24-bit stuff in iwd2

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1104]
As soon as you try to leave the first area, the game crashes:

> [SDLVideo/FATAL]: 24bpp is not supported.

If you don't have any saves: start a new game, ctrl-shift-y, go to the next area via stairs in hte NW corner of the map.

Looks like it happens when generating the savegame thumbnails:
```
Thread 1 "gemrb" hit Breakpoint 2, 0x00007ffff5c0b760 in GemRB::error(char const*, char const*, ...)@plt ()
   from ./gemrb/plugins/SDLVideo.so
(gdb) bt
#0  0x00007ffff5c0b760 in GemRB::error(char const*, char const*, ...)@plt () at ./gemrb/plugins/SDLVideo.so
#1  0x00007ffff5c119e4 in GemRB::SDLPixelIterator::InitImp(void*, int, int)
    (this=0x7fffffff90e0, pixel=0x7ffff0f45010, pitch=2400, bpp=3)
    at /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLPixelIterator.h:43
#2  0x00007ffff5c11737 in GemRB::SDLPixelIterator::SDLPixelIterator(SDL_Surface*, GemRB::IPixelIterator::Direction, GemRB::IPixelIterator::Direction, SDL_Rect const&)                                                              
    (this=0x7fffffff90e0, surf=0x2779560, x=GemRB::IPixelIterator::Forward, y=GemRB::IPixelIterator::Forward, clip=...) at /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLPixelIterator.h:97
#3  0x00007ffff5c16249 in GemRB::SDLPixelIterator::SDLPixelIterator(SDL_Surface*, GemRB::IPixelIterator::Direction, GemRB::IPixelIterator::Direction)                                                                               
    (this=0x7fffffff90e0, surf=0x2779560, x=GemRB::IPixelIterator::Forward, y=GemRB::IPixelIterator::Forward)
    at /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLPixelIterator.h:88
#4  0x00007ffff5c15899 in GemRB::SDLSurfaceSprite2D::GetPixel(GemRB::Point const&) const (this=0x2644e50, p=...)
    at /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp:208
#5  0x00007ffff7eaa2e9 in GemRB::Sprite2D::GetPixel(int, int) const (this=0x2644e50, x=0, y=0)
    at /home/kajak/games/gemrb-subviews/gemrb/core/Sprite2D.cpp:58
#6  0x00007ffff7ebe305 in GemRB::Video::SpriteGetPixelSum(GemRB::Holder<GemRB::Sprite2D>, unsigned short, unsigned--Type <RET> for more, q to quit, c to continue without paging--
 short, unsigned int) (this=0x4370d0, sprite=..., xbase=0, ybase=0, ratio=5)
    at /home/kajak/games/gemrb-subviews/gemrb/core/Video.cpp:330
#7  0x00007ffff7ebe0d2 in GemRB::Video::SpriteScaleDown(GemRB::Holder<GemRB::Sprite2D>, unsigned int)
    (this=0x4370d0, sprite=..., ratio=5) at /home/kajak/games/gemrb-subviews/gemrb/core/Video.cpp:277
#8  0x00007ffff7e481ee in GemRB::DoSaveGame(char const*)
    (Path=0x7fffffffc4c0 "/media/kajak/games/iwd2-old/save/000000000-Auto-Save")
    at /home/kajak/games/gemrb-subviews/gemrb/core/SaveGameIterator.cpp:488
#9  0x00007ffff7e476cf in GemRB::SaveGameIterator::CreateSaveGame(int, bool) (this=0x6b7f00, index=0, mqs=false)
    at /home/kajak/games/gemrb-subviews/gemrb/core/SaveGameIterator.cpp:636
#10 0x00007ffff7e06e5e in GemRB::Map::MoveToNewArea(char const*, char const*, unsigned int, int, GemRB::Actor*)
    (this=0xdffd40, area=0x19f0688 "ar1100", entrance=0x19f0691 "FR1000", direction=0, EveryOne=3, actor=
    0xc11c80) at /home/kajak/games/gemrb-subviews/gemrb/core/Map.cpp:494
#11 0x00007ffff7e0761e in GemRB::Map::UseExit(GemRB::Actor*, GemRB::InfoPoint*)
    (this=0xdffd40, actor=0xc11c80, ip=0x19f0460) at /home/kajak/games/gemrb-subviews/gemrb/core/Map.cpp:614
#12 0x00007ffff7e0819e in GemRB::Map::UpdateScripts() (this=0xdffd40)
    at /home/kajak/games/gemrb-subviews/gemrb/core/Map.cpp:848

(gdb) f 8
#8  0x00007ffff7e481ee in GemRB::DoSaveGame (
    Path=0x7fffffffc4c0 "/media/kajak/games/iwd2-old/save/000000000-Auto-Save")
    at /home/kajak/games/gemrb-subviews/gemrb/core/SaveGameIterator.cpp:488
488             preview = core->GetVideoDriver()->SpriteScaleDown(preview, 5);
```

And yeah, it happens in other games as well. Anything that causes an autosave.

**Comment by bradallred** [comment]
you can repro quicker than that by quick saving
