### ISSUE TITLE
Crash when loading game several times

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1165]
#### Bug description
To trigger, load game several times (2 or 3). Reproduced on master, subviews, IWD1 and BG2.

related to #1163 ?

```gdb
[OpenAL]: Music in INITIAL State. AutoStarting

Thread 11 "gemrb" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbbfff640 (LWP 14280)]
GemRB::AmbientMgrAL::AmbientSource::enqueue (this=0x555558374a00)
    at /home/dupontr/Downloads/gemrb_master/gemrb/gemrb/plugins/OpenALAudio/AmbientMgrAL.cpp:260
260		return core->GetAudioDrv()->QueueAmbient(stream, ambient->sounds[nextref]);
(gdb) bt
#0  GemRB::AmbientMgrAL::AmbientSource::enqueue (this=0x555558374a00)
    at /home/dupontr/Downloads/gemrb_master/gemrb/gemrb/plugins/OpenALAudio/AmbientMgrAL.cpp:260
#1  0x00007ffff5f3b3a9 in GemRB::AmbientMgrAL::AmbientSource::tick (
    this=0x555558374a00, ticks=1614060015266, listener=..., timeslice=4194304)
    at /home/dupontr/Downloads/gemrb_master/gemrb/gemrb/plugins/OpenALAudio/AmbientMgrAL.cpp:246
#2  0x00007ffff5f3ad33 in GemRB::AmbientMgrAL::tick (this=0x555555ea26e0, 
    ticks=1614060015266)
    at /home/dupontr/Downloads/gemrb_master/gemrb/gemrb/plugins/OpenALAudio/AmbientMgrAL.cpp:142
#3  0x00007ffff5f3ab45 in GemRB::AmbientMgrAL::play (this=0x555555ea26e0)
    at /home/dupontr/Downloads/gemrb_master/gemrb/gemrb/plugins/OpenALAudio/AmbientMgrAL.cpp:115
#4  0x00007ffff5f402fa in std::__invoke_impl<int, int (GemRB::AmbientMgrAL::*)(), GemRB::AmbientMgrAL*> (
    __f=@0x555555e77a30: (int (GemRB::AmbientMgrAL::*)(GemRB::AmbientMgrAL * const)) 0x7ffff5f3aac0 <GemRB::AmbientMgrAL::play()>, 
    __t=@0x555555e77a28: 0x555555ea26e0)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/invoke.h:73
#5  0x00007ffff5f4023d in std::__invoke<int (GemRB::AmbientMgrAL::*)(), GemRB::AmbientMgrAL*> (
    __fn=@0x555555e77a30: (int (GemRB::AmbientMgrAL::*)(GemRB::AmbientMgrAL * co--Type <RET> for more, q to quit, c to continue without paging--
nst)) 0x7ffff5f3aac0 <GemRB::AmbientMgrAL::play()>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/invoke.h:95
#6  0x00007ffff5f401ad in std::thread::_Invoker<std::tuple<int (GemRB::AmbientMgrAL::*)(), GemRB::AmbientMgrAL*> >::_M_invoke<0ul, 1ul> (this=0x555555e77a28)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/thread:244
#7  0x00007ffff5f4014a in std::thread::_Invoker<std::tuple<int (GemRB::AmbientMgrAL::*)(), GemRB::AmbientMgrAL*> >::operator() (this=0x555555e77a28)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/thread:251
#8  0x00007ffff5f400ee in std::thread::_State_impl<std::thread::_Invoker<std::tuple<int (GemRB::AmbientMgrAL::*)(), GemRB::AmbientMgrAL*> > >::_M_run (
    this=0x555555e77a20)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/thread:195
#9  0x00007ffff7a82eff in ?? ()
   from /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/libstdc++.so.6
#10 0x00007ffff7c06f5e in start_thread () from /lib64/libpthread.so.0
#11 0x00007ffff77721ef in clone () from /lib64/libc.so.6
```

**Comment by lynxlynxlynx** [comment]
Probably a dupe, even thought the trace isn't identical.

**Comment by FrElvire** [comment]
I can always reproduce it. It seems it's not a dupe

**Comment by FrElvire** [comment]
Can't reproduce anymore on master :+1:
