### ISSUE TITLE
[subviews] PST action bar not working because of clock error

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1184]
#### Bug description
In PST, you cannot use much of the action bar right now: Clock is stuck, and the controls to the right don't do much. I found a Python error that looks related.

#### Screenshots
```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File /mnt/shared/Sources/gemrb_subviews/gemrb/GUIScripts/pst/Game.py, line 31, in EnterGame
[Python/ERROR]:     MessageWindow.OnLoad()
[Python/ERROR]:   File /mnt/shared/Sources/gemrb_subviews/gemrb/GUIScripts/pst/MessageWindow.py, line 84, in OnLoad
[Python/ERROR]:     GUICommonWindows.SetupClockWindowControls (ActionsWindow)
[Python/ERROR]: AttributeError: 'module' object has no attribute 'SetupClockWindowControls'
```

**Comment by MarcelHB** [comment]
New error:
```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "D:\Sources\gemrb_subviews\gemrb\GUIScripts\pst/Game.py", line 31, in EnterGame
[Python/ERROR]:     MessageWindow.OnLoad()
[Python/ERROR]:   File "D:\Sources\gemrb_subviews\gemrb\GUIScripts\pst/MessageWindow.py", line 84, in OnLoad
[Python/ERROR]:     SetupClockWindowControls (ActionsWindow)
[Python/ERROR]:   File "D:\Sources\gemrb_subviews\gemrb\GUIScripts\pst/MessageWindow.py", line 97, in SetupClockWindowControls
[Python/ERROR]:     SetPSTGamedaysAndHourToken ()
[Python/ERROR]: NameError: global name 'SetPSTGamedaysAndHourToken' is not defined
```
