### ISSUE TITLE
[subviews] a bunch of view debug leaks

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1220]
Just leaving it running at the main menu is enough to leak quite fast if you have DebugMode = 32:
```gdb
Direct leak of 1343840 byte(s) in 33596 object(s) allocated from:
    #0 0x7fd301722f17 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.6+0xb1f17)
    #1 0x7fd2fc06747c in GemRB::PixelIterator<unsigned int>::Clone() const /home/kajak/games/gemrb-subviews/gemrb/core/Pixels.h:254
    #2 0x7fd2fc05ded6 in GemRB::SDLPixelIterator::SDLPixelIterator(GemRB::SDLPixelIterator const&) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLPixelIterator.h:143
    #3 0x7fd2fc05e2b5 in GemRB::SDLPixelIterator::end(GemRB::SDLPixelIterator const&) (gemrb/plugins/SDLVideo.so+0x1d2b5)
    #4 0x7fd2fc0a0f97 in void GemRB::DrawVLineSurface<(GemRB::SHADER)0>(SDL_Surface*, GemRB::Point, short, GemRB::Region const&, GemRB::Color const&) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLSurfaceDrawing.h:247
    #5 0x7fd2fc076c6a in GemRB::SDL12VideoDriver::DrawRectImp(GemRB::Region const&, GemRB::Color const&, bool, unsigned int) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDL12Video.cpp:503
    #6 0x7fd301413f1f in GemRB::Video::DrawRect(GemRB::Region const&, GemRB::Color const&, bool, unsigned int) /home/kajak/games/gemrb-subviews/gemrb/core/Video.cpp:378
    #7 0x7fd3010af69e in GemRB::View::Draw() /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:284
    #8 0x7fd3010adedb in GemRB::View::DrawSubviews() const /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:200
    #9 0x7fd3010af49d in GemRB::View::Draw() /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:272
    #10 0x7fd3010adedb in GemRB::View::DrawSubviews() const /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:200
    #11 0x7fd3010af49d in GemRB::View::Draw() /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:272
    #12 0x7fd3010d4303 in GemRB::WindowManager::DrawWindows() const /home/kajak/games/gemrb-subviews/gemrb/core/GUI/WindowManager.cpp:608
    #13 0x7fd3011d8ee4 in GemRB::Interface::Main() /home/kajak/games/gemrb-subviews/gemrb/core/Interface.cpp:956
    #14 0x562d7d954803 in main /home/kajak/games/gemrb-subviews/gemrb/GemRB.cpp:73
    #15 0x7fd30091c0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Direct leak of 1343840 byte(s) in 33596 object(s) allocated from:
    #0 0x7fd301722f17 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.6+0xb1f17)
    #1 0x7fd2fc06747c in GemRB::PixelIterator<unsigned int>::Clone() const /home/kajak/games/gemrb-subviews/gemrb/core/Pixels.h:254
    #2 0x7fd2fc05ded6 in GemRB::SDLPixelIterator::SDLPixelIterator(GemRB::SDLPixelIterator const&) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLPixelIterator.h:143
    #3 0x7fd2fc05e2b5 in GemRB::SDLPixelIterator::end(GemRB::SDLPixelIterator const&) (gemrb/plugins/SDLVideo.so+0x1d2b5)
    #4 0x7fd2fc0a0f97 in void GemRB::DrawVLineSurface<(GemRB::SHADER)0>(SDL_Surface*, GemRB::Point, short, GemRB::Region const&, GemRB::Color const&) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLSurfaceDrawing.h:247
    #5 0x7fd2fc0769d3 in GemRB::SDL12VideoDriver::DrawRectImp(GemRB::Region const&, GemRB::Color const&, bool, unsigned int) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDL12Video.cpp:501
    #6 0x7fd301413f1f in GemRB::Video::DrawRect(GemRB::Region const&, GemRB::Color const&, bool, unsigned int) /home/kajak/games/gemrb-subviews/gemrb/core/Video.cpp:378
    #7 0x7fd3010af69e in GemRB::View::Draw() /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:284
    #8 0x7fd3010adedb in GemRB::View::DrawSubviews() const /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:200
    #9 0x7fd3010af49d in GemRB::View::Draw() /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:272
    #10 0x7fd3010adedb in GemRB::View::DrawSubviews() const /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:200
    #11 0x7fd3010af49d in GemRB::View::Draw() /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:272
    #12 0x7fd3010d4303 in GemRB::WindowManager::DrawWindows() const /home/kajak/games/gemrb-subviews/gemrb/core/GUI/WindowManager.cpp:608
    #13 0x7fd3011d8ee4 in GemRB::Interface::Main() /home/kajak/games/gemrb-subviews/gemrb/core/Interface.cpp:956
    #14 0x562d7d954803 in main /home/kajak/games/gemrb-subviews/gemrb/GemRB.cpp:73
    #15 0x7fd30091c0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Direct leak of 335960 byte(s) in 8399 object(s) allocated from:
    #0 0x7fd301722f17 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.6+0xb1f17)
    #1 0x7fd2fc06747c in GemRB::PixelIterator<unsigned int>::Clone() const /home/kajak/games/gemrb-subviews/gemrb/core/Pixels.h:254
    #2 0x7fd2fc05ded6 in GemRB::SDLPixelIterator::SDLPixelIterator(GemRB::SDLPixelIterator const&) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLPixelIterator.h:143
    #3 0x7fd2fc05e2b5 in GemRB::SDLPixelIterator::end(GemRB::SDLPixelIterator const&) (gemrb/plugins/SDLVideo.so+0x1d2b5)
    #4 0x7fd2fc0a0f97 in void GemRB::DrawVLineSurface<(GemRB::SHADER)0>(SDL_Surface*, GemRB::Point, short, GemRB::Region const&, GemRB::Color const&) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLSurfaceDrawing.h:247
    #5 0x7fd2fc0769d3 in GemRB::SDL12VideoDriver::DrawRectImp(GemRB::Region const&, GemRB::Color const&, bool, unsigned int) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDL12Video.cpp:501
    #6 0x7fd301413f1f in GemRB::Video::DrawRect(GemRB::Region const&, GemRB::Color const&, bool, unsigned int) /home/kajak/games/gemrb-subviews/gemrb/core/Video.cpp:378
    #7 0x7fd3010af69e in GemRB::View::Draw() /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:284
    #8 0x7fd3010adedb in GemRB::View::DrawSubviews() const /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:200
    #9 0x7fd3010af49d in GemRB::View::Draw() /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:272
    #10 0x7fd3010d4303 in GemRB::WindowManager::DrawWindows() const /home/kajak/games/gemrb-subviews/gemrb/core/GUI/WindowManager.cpp:608
    #11 0x7fd3011d8ee4 in GemRB::Interface::Main() /home/kajak/games/gemrb-subviews/gemrb/core/Interface.cpp:956
    #12 0x562d7d954803 in main /home/kajak/games/gemrb-subviews/gemrb/GemRB.cpp:73
    #13 0x7fd30091c0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Direct leak of 335960 byte(s) in 8399 object(s) allocated from:
    #0 0x7fd301722f17 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.6+0xb1f17)
    #1 0x7fd2fc06747c in GemRB::PixelIterator<unsigned int>::Clone() const /home/kajak/games/gemrb-subviews/gemrb/core/Pixels.h:254
    #2 0x7fd2fc05ded6 in GemRB::SDLPixelIterator::SDLPixelIterator(GemRB::SDLPixelIterator const&) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLPixelIterator.h:143
    #3 0x7fd2fc05e2b5 in GemRB::SDLPixelIterator::end(GemRB::SDLPixelIterator const&) (gemrb/plugins/SDLVideo.so+0x1d2b5)
    #4 0x7fd2fc0a0f97 in void GemRB::DrawVLineSurface<(GemRB::SHADER)0>(SDL_Surface*, GemRB::Point, short, GemRB::Region const&, GemRB::Color const&) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLSurfaceDrawing.h:247
    #5 0x7fd2fc076c6a in GemRB::SDL12VideoDriver::DrawRectImp(GemRB::Region const&, GemRB::Color const&, bool, unsigned int) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDL12Video.cpp:503
    #6 0x7fd301413f1f in GemRB::Video::DrawRect(GemRB::Region const&, GemRB::Color const&, bool, unsigned int) /home/kajak/games/gemrb-subviews/gemrb/core/Video.cpp:378
    #7 0x7fd3010af5e0 in GemRB::View::Draw() /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:279
    #8 0x7fd3010d4303 in GemRB::WindowManager::DrawWindows() const /home/kajak/games/gemrb-subviews/gemrb/core/GUI/WindowManager.cpp:608
    #9 0x7fd3011d8ee4 in GemRB::Interface::Main() /home/kajak/games/gemrb-subviews/gemrb/core/Interface.cpp:956
    #10 0x562d7d954803 in main /home/kajak/games/gemrb-subviews/gemrb/GemRB.cpp:73
    #11 0x7fd30091c0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Direct leak of 335960 byte(s) in 8399 object(s) allocated from:
    #0 0x7fd301722f17 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.6+0xb1f17)
    #1 0x7fd2fc06747c in GemRB::PixelIterator<unsigned int>::Clone() const /home/kajak/games/gemrb-subviews/gemrb/core/Pixels.h:254
    #2 0x7fd2fc05ded6 in GemRB::SDLPixelIterator::SDLPixelIterator(GemRB::SDLPixelIterator const&) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLPixelIterator.h:143
    #3 0x7fd2fc05e2b5 in GemRB::SDLPixelIterator::end(GemRB::SDLPixelIterator const&) (gemrb/plugins/SDLVideo.so+0x1d2b5)
    #4 0x7fd2fc0a0f97 in void GemRB::DrawVLineSurface<(GemRB::SHADER)0>(SDL_Surface*, GemRB::Point, short, GemRB::Region const&, GemRB::Color const&) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLSurfaceDrawing.h:247
    #5 0x7fd2fc0769d3 in GemRB::SDL12VideoDriver::DrawRectImp(GemRB::Region const&, GemRB::Color const&, bool, unsigned int) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDL12Video.cpp:501
    #6 0x7fd301413f1f in GemRB::Video::DrawRect(GemRB::Region const&, GemRB::Color const&, bool, unsigned int) /home/kajak/games/gemrb-subviews/gemrb/core/Video.cpp:378
    #7 0x7fd3010af5e0 in GemRB::View::Draw() /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:279
    #8 0x7fd3010d4303 in GemRB::WindowManager::DrawWindows() const /home/kajak/games/gemrb-subviews/gemrb/core/GUI/WindowManager.cpp:608
    #9 0x7fd3011d8ee4 in GemRB::Interface::Main() /home/kajak/games/gemrb-subviews/gemrb/core/Interface.cpp:956
    #10 0x562d7d954803 in main /home/kajak/games/gemrb-subviews/gemrb/GemRB.cpp:73
    #11 0x7fd30091c0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Direct leak of 335960 byte(s) in 8399 object(s) allocated from:
    #0 0x7fd301722f17 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.6+0xb1f17)
    #1 0x7fd2fc06747c in GemRB::PixelIterator<unsigned int>::Clone() const /home/kajak/games/gemrb-subviews/gemrb/core/Pixels.h:254
    #2 0x7fd2fc05ded6 in GemRB::SDLPixelIterator::SDLPixelIterator(GemRB::SDLPixelIterator const&) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLPixelIterator.h:143
    #3 0x7fd2fc05e2b5 in GemRB::SDLPixelIterator::end(GemRB::SDLPixelIterator const&) (gemrb/plugins/SDLVideo.so+0x1d2b5)
    #4 0x7fd2fc0a0f97 in void GemRB::DrawVLineSurface<(GemRB::SHADER)0>(SDL_Surface*, GemRB::Point, short, GemRB::Region const&, GemRB::Color const&) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLSurfaceDrawing.h:247
    #5 0x7fd2fc076c6a in GemRB::SDL12VideoDriver::DrawRectImp(GemRB::Region const&, GemRB::Color const&, bool, unsigned int) /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDL12Video.cpp:503
    #6 0x7fd301413f1f in GemRB::Video::DrawRect(GemRB::Region const&, GemRB::Color const&, bool, unsigned int) /home/kajak/games/gemrb-subviews/gemrb/core/Video.cpp:378
    #7 0x7fd3010af69e in GemRB::View::Draw() /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:284
    #8 0x7fd3010adedb in GemRB::View::DrawSubviews() const /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:200
    #9 0x7fd3010af49d in GemRB::View::Draw() /home/kajak/games/gemrb-subviews/gemrb/core/GUI/View.cpp:272
    #10 0x7fd3010d4303 in GemRB::WindowManager::DrawWindows() const /home/kajak/games/gemrb-subviews/gemrb/core/GUI/WindowManager.cpp:608
    #11 0x7fd3011d8ee4 in GemRB::Interface::Main() /home/kajak/games/gemrb-subviews/gemrb/core/Interface.cpp:956
    #12 0x562d7d954803 in main /home/kajak/games/gemrb-subviews/gemrb/GemRB.cpp:73
    #13 0x7fd30091c0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
```

**Comment by bradallred** [comment]
that should fix it

**Comment by lynxlynxlynx** [comment]
Yep. :)
