### ISSUE TITLE
Python exception on exit

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1284]
When exiting from the game back to the main menu, there's a harmless exception thrown:
```
[GUIScript/ERROR]: Runtime Error:                                                                                 
[Python/ERROR]: Traceback (most recent call last):                                                                
[Python/ERROR]:   File "../gemrb/GUIScripts/GUICommonWindows.py", line 1386, in <lambda>                          
[Python/ERROR]:     window.SetAction(lambda: TopWindowClosed(window), ACTION_WINDOW_CLOSED)                       
[Python/ERROR]:   File "../gemrb/GUIScripts/GUICommonWindows.py", line 1360, in TopWindowClosed                   
[Python/ERROR]:     SelectionChanged()                                                                            
[Python/ERROR]:   File "../gemrb/GUIScripts/GUICommonWindows.py", line 1916, in SelectionChanged                  
[Python/ERROR]:     UpdateActionsWindow ()                                                                        
[Python/ERROR]:   File "../gemrb/GUIScripts/GUICommonWindows.py", line 662, in UpdateActionsWindow                
[Python/ERROR]:     CurrentWindow.SetupControls (globals(), pc, ActionBarControlOffset)                           
[Python/ERROR]:   File "../gemrb/GUIScripts/MetaClasses.py", line 61, in handler                                  
[Python/ERROR]:     raise type(e)(str(e) + "\nMethod Docs:\n" + str(f.__doc__))                                   
[Python/ERROR]: RuntimeError: Can't find GameControl!                                                             
Method Docs:                                                                                                      
===== Window_SetupControls =====  
```
Easy to cut short, though I don't know since when this started happening — odd that I didn't notice sooner.

**Comment by bradallred** [comment]
which game? I didnt see this, but it looks like `GUICommonWindows.CloseTopWindow ()` needs to be called prior to `GemRB.QuitGame ()`

**Comment by lynxlynxlynx** [comment]
At least bg1 and bg2 and if it wasn't clear, you have to quit through the options window.

**Comment by bradallred** [comment]
yeah, I tried quitting a loaded save from the GUIOPT menu in BG2 and didn't get this. Same with BG1 just now.

**Comment by lynxlynxlynx** [comment]
I don't know what's different for you, but this happens on both of my machines. Some more testing, in bg2, I can only reproduce from TOB, not SOA though.

**Comment by bradallred** [comment]
that fixes the TOB error on exit. Annoyingly it seeps that opening GUIOPT immediately closes it the first time you open it. no idea what would be causing that, but it also seems limited to TOB.
