### ISSUE TITLE
Crash when navigating a PC (BG1)

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1307]
I start BG and enter a game. I attempt to move one of my PCs and boom:

```gdb
#5  0x00007ff873060fc9 in ?? ()
   from C:\Program Files\MSYS2\mingw64\bin\libstdc++-6.dll
#6  0x00007ff83c74ad27 in __gnu_cxx::__stoa<long, int, char, int> (
    __convf=0x7ff83c746388 <strtol>,
    __name=0x7ff83c778151 <GemRB::StatValues+2033> "stoi",
    __str=0xa937fff330 "*", __idx=0x0)
    at C:/Program Files/MSYS2/mingw64/include/c++/10.3.0/ext/string_conversions.h:83
#7  0x00007ff83c6b6e5b in std::__cxx11::stoi (__base=0, __idx=0x0, __str="*")
    at C:/Program Files/MSYS2/mingw64/include/c++/10.3.0/bits/basic_string.h:186
#8  GemRB::Interface::ResolveStatBonus (this=0x1ff5d7c7930, actor=actor@entry=
    0x1ff70a28b40, tablename=0x1ff79b0fc30 "dsclass",
    tablename@entry=0x7ff8525571aa "dstable", flags=flags@entry=0,
    value=value@entry=0) at D:/Sources/gemrb/gemrb/core/Interface.cpp:4817
#9  0x00007ff852545fc8 in fx_find_traps (target=0x1ff70a28b40,
    fx=0x1ff79b0c370)
    at D:/Sources/gemrb/gemrb/plugins/FXOpcodes/FXOpcodes.cpp:4606
#10 0x00007ff83c64158a in GemRB::EffectDesc::operator() (fx=0x1ff79b0c370,
    a=0x1ff70a28b40, s=<optimized out>, this=<optimized out>)
    at D:/Sources/gemrb/gemrb/core/EffectQueue.h:184
#11 GemRB::EffectQueue::ApplyEffect (this=this@entry=0x1ff79b0c8b0,
    target=target@entry=0x1ff70a28b40, fx=fx@entry=0x1ff79b0c370,
    first_apply=first_apply@entry=1, resistance=resistance@entry=1)
    at D:/Sources/gemrb/gemrb/core/EffectQueue.cpp:1300
#12 0x00007ff83c642a2e in GemRB::EffectQueue::ApplyEffect (resistance=1,
    first_apply=1, fx=0x1ff79b0c370, target=0x1ff70a28b40, this=0x1ff79b0c8b0)
    at D:/Sources/gemrb/gemrb/core/EffectQueue.cpp:1186
#13 GemRB::EffectQueue::AddEffect (this=this@entry=0x1ff79b0c8b0,
    fx=0x1ff79b0c370, self=0x1ff70a28b40,
    pretarget=pretarget@entry=0x1ff70a28b40, dest=...)
    at D:/Sources/gemrb/gemrb/core/EffectQueue.cpp:670
#14 0x00007ff83c643575 in GemRB::EffectQueue::AddAllEffects (
    this=this@entry=0x1ff79b0c8b0, target=target@entry=0x1ff70a28b40,
    destination=...) at D:/Sources/gemrb/gemrb/core/EffectQueue.cpp:767
#15 0x00007ff83c6b1a21 in GemRB::Interface::ApplyEffectQueue (
    this=<optimized out>, fxqueue=0x1ff79b0c8b0, actor=0x1ff70a28b40,
    caster=0x1ff70a28b40, p=...)
    at D:/Sources/gemrb/gemrb/core/Interface.cpp:4332
#16 0x00007ff83c6b1ad0 in GemRB::Interface::ApplySpell (this=0x1ff5d7c7930,
    resname=resname@entry=0x7ff83c77dd7f <GemRB::SPathDelimiter+5931> "detect", actor=actor@entry=0x1ff70a28b40, caster=caster@entry=0x1ff70a28b40,
    level=level@entry=0) at D:/Sources/gemrb/gemrb/core/Interface.cpp:4275
#17 0x00007ff83c701921 in GemRB::Actor::UpdateModalState (this=0x1ff70a28b40,
    gameTime=31845) at D:/Sources/gemrb/gemrb/core/Scriptable/Actor.cpp:7884
#18 0x00007ff83c701e36 in GemRB::Actor::UpdateModalState (gameTime=1,
    this=0x1ff70a28b40)
    at D:/Sources/gemrb/gemrb/core/Scriptable/Actor.cpp:7873
#19 GemRB::Actor::UpdateActorState (this=this@entry=0x1ff70a28b40)
    at D:/Sources/gemrb/gemrb/core/Scriptable/Actor.cpp:7868
#20 0x00007ff83c6d0d70 in GemRB::Map::UpdateScripts (this=0x1ff72ae2600)
    at D:/Sources/gemrb/gemrb/core/Map.cpp:764
#21 0x00007ff83c67b94d in GemRB::Game::UpdateScripts (this=0x1ff709da6b0)
    at D:/Sources/gemrb/gemrb/core/Game.cpp:1560
#22 0x00007ff83c6b107d in GemRB::Interface::GameLoop (
    this=this@entry=0x1ff5d7c7930)
    at D:/Sources/gemrb/gemrb/core/Interface.cpp:2577
#23 0x00007ff83c6bf382 in GemRB::Interface::Main (this=0x1ff5d7c7930)
    at D:/Sources/gemrb/gemrb/core/Interface.cpp:929
#24 0x00007ff7ac702ad4 in main (argc=3, argv=0x1ff5d612a70)
    at D:/Sources/gemrb/platforms/windows/GemRB.cpp:53
```

**Comment by MarcelHB** [comment]
Cannot reproduce this anymore.
