### ISSUE TITLE
Crash when exiting IWD2 from the main menu 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1308]
When starting IWD2, and then exiting the game again, there is a segfault observed:

```gdb
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff83c6a955b in GemRB::GlobalTimer::~GlobalTimer (this=0x29001397c30,
    __in_chrg=<optimized out>)
    at D:/Sources/gemrb/gemrb/core/GlobalTimer.cpp:41
41                      delete anim;
(gdb) bt
#0  0x00007ff83c6a955b in GemRB::GlobalTimer::~GlobalTimer (
    this=0x29001397c30, __in_chrg=<optimized out>)
    at D:/Sources/gemrb/gemrb/core/GlobalTimer.cpp:41
#1  0x00007ff83c6b2c9c in GemRB::Interface::~Interface (this=0x29001397890,
    __in_chrg=<optimized out>)
    at D:/Sources/gemrb/gemrb/core/Interface.cpp:297
#2  0x00007ff7ac702ae5 in main (argc=1, argv=0x29001203f90)
    at D:/Sources/gemrb/platforms/windows/GemRB.cpp:54
```

No Valgrind on Win, so no further hints on what this may be.

**Comment by MarcelHB** [comment]
Ok, also happens when leaving other games (BG) in some conditions, obviously.

**Comment by MarcelHB** [comment]
I still get a segfault report around line 41.
