### ISSUE TITLE
Crash when navigating a PC (IWD2) 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1309]
Similar to #1307, we don't get very far after entering the game as soon as we do something with the PCs, but this is certainly something different now, with `valid` being 0x0 here:

```gdb
GemRB::CheckVariable (Sender=Sender@entry=0x23bdf220740,
    VarName=0x23bdf2287c4 "LOCALSsavedlocation", Context=Context@entry=0x0,
    valid=valid@entry=0x0)
    at D:/Sources/gemrb/gemrb/core/GameScript/GSUtils.cpp:2247
2247                            *valid = false;
(gdb) bt
#0  GemRB::CheckVariable (Sender=Sender@entry=0x23bdf220740,
    VarName=0x23bdf2287c4 "LOCALSsavedlocation", Context=Context@entry=0x0,
    valid=valid@entry=0x0)
    at D:/Sources/gemrb/gemrb/core/GameScript/GSUtils.cpp:2247
#1  0x00007ff83c695319 in GemRB::CheckPointVariable (
    Sender=Sender@entry=0x23bdf220740, VarName=<optimized out>,
    Context=Context@entry=0x0, valid=valid@entry=0x0)
    at D:/Sources/gemrb/gemrb/core/GameScript/GSUtils.cpp:2277
#2  0x00007ff83c685025 in GemRB::GameScript::FaceSavedLocation (
    Sender=0x23bdf220740, parameters=0x23bdf228790)
    at D:/Sources/gemrb/gemrb/core/GameScript/Actions.cpp:1844
#3  0x00007ff83c69cb75 in GemRB::GameScript::ExecuteAction (
    Sender=0x23bdf220740, aC=0x23bdf228790)
    at D:/Sources/gemrb/gemrb/core/GameScript/GameScript.cpp:2503
#4  0x00007ff83c714061 in GemRB::Scriptable::ProcessActions (
    this=this@entry=0x23bdf220740)
    at D:/Sources/gemrb/gemrb/core/Scriptable/Scriptable.cpp:564
#5  0x00007ff83c7141ed in GemRB::Scriptable::Update (this=0x23bdf220740)
    at D:/Sources/gemrb/gemrb/core/Scriptable/Scriptable.cpp:306
#6  0x00007ff83c6d0d68 in GemRB::Map::UpdateScripts (this=0x23bd83a59b0)
    at D:/Sources/gemrb/gemrb/core/Map.cpp:763
#7  0x00007ff83c67b94d in GemRB::Game::UpdateScripts (this=0x23bd60607f0)
    at D:/Sources/gemrb/gemrb/core/Game.cpp:1560
#8  0x00007ff83c6b107d in GemRB::Interface::GameLoop (
    this=this@entry=0x23bc35c7890)
    at D:/Sources/gemrb/gemrb/core/Interface.cpp:2577
#9  0x00007ff83c6bf382 in GemRB::Interface::Main (this=0x23bc35c7890)
    at D:/Sources/gemrb/gemrb/core/Interface.cpp:929
#10 0x00007ff7ac702ad4 in main (argc=1, argv=0x23bc33e3f90)
    at D:/Sources/gemrb/platforms/windows/GemRB.cpp:53
```

**Comment by MarcelHB** [comment]
Looks gone.
