### ISSUE TITLE
AREImporter violates assertion 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1310]
In IWD2, I'm in Targos and go into the very first home. The game terminates over an assertion violation (see debug info at the end: we have missed 16 bytes somewhere):

```gdb
Assertion failed: stream->GetPos() == CreatureOffset, file D:/Sources/gemrb/gemrb/plugins/AREImporter/AREImporter.cpp, line 2288

Thread 1 hit Breakpoint 1, 0x00007ff8927ef1e7 in msvcrt!abort ()
   from C:\Windows\System32\msvcrt.dll
(gdb) bt
#0  0x00007ff8927ef1e7 in msvcrt!abort () from C:\Windows\System32\msvcrt.dll
#1  0x00007ff8927eda1e in msvcrt!_wassert ()
   from C:\Windows\System32\msvcrt.dll
#2  0x00007ff86cc94e5a in GemRB::AREImporter::PutActors (
    this=this@entry=0x20a9f2824b0, stream=stream@entry=0xdfd4fff600,
    map=map@entry=0x20af2b327c0)
    at D:/Sources/gemrb/gemrb/plugins/AREImporter/AREImporter.cpp:2288
#3  0x00007ff86cc95246 in GemRB::AREImporter::PutArea (this=0x20a9f2824b0,
    stream=0xdfd4fff600, map=0x20af2b327c0)
    at D:/Sources/gemrb/gemrb/plugins/AREImporter/AREImporter.cpp:2656
#4  0x00007ff83c6bf533 in GemRB::Interface::SwapoutArea (this=0x20addd97890,
    map=0x20af2b327c0) at D:/Sources/gemrb/gemrb/core/Interface.cpp:4377
#5  0x00007ff83c67b832 in GemRB::Game::DelMap (this=this@entry=0x20af1ab20e0,
    index=index@entry=1, forced=forced@entry=0)
    at C:/Program Files/MSYS2/mingw64/include/c++/10.3.0/bits/stl_vector.h:1043
#6  0x00007ff83c67b9dd in GemRB::Game::UpdateScripts (this=0x20af1ab20e0)
    at D:/Sources/gemrb/gemrb/core/Game.cpp:1587
#7  0x00007ff83c6b10bd in GemRB::Interface::GameLoop (
    this=this@entry=0x20addd97890)
    at D:/Sources/gemrb/gemrb/core/Interface.cpp:2577
#8  0x00007ff83c6bf1e2 in GemRB::Interface::Main (this=0x20addd97890)
    at D:/Sources/gemrb/gemrb/core/Interface.cpp:929
#9  0x00007ff7d9532ad4 in main (argc=1, argv=0x20addbb3f90)
    at D:/Sources/gemrb/platforms/windows/GemRB.cpp:53
(gdb) f 2
#2  0x00007ff86cc94e5a in GemRB::AREImporter::PutActors (
    this=this@entry=0x20a9f2824b0, stream=stream@entry=0xdfd4fff600,
    map=map@entry=0x20af2b327c0)
    at D:/Sources/gemrb/gemrb/plugins/AREImporter/AREImporter.cpp:2288
2288                    assert(stream->GetPos() == CreatureOffset);
(gdb) p CreatureOffset
$1 = 9820
(gdb) p *stream
$3 = {_vptr.DataStream = 0x7ff83c787650 <vtable for GemRB::FileStream+16>,
  Pos = 9804, size = 9804, Encrypted = false, static IsBigEndian = false,
```

**Comment by bradallred** [comment]
assuming you are seeking of the house next to the starting docks, I can get inside there now

I never did hit that assert, but its likely that ASAN was puking up before I got there

**Comment by MarcelHB** [comment]
Yes, looks good now.
