### ISSUE TITLE
[iwd1] crash when changing zone

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1343]
#### Bug description
when selecting new zone on map, segfault happen.

```
[WorldMap/DEBUG]: Updated Area visibility: ar4000 (visited, accessible and visible)
[WorldMap/DEBUG]: Updated Area visibility: ar2100 (accessible and visible)
[WorldMap]: CalculateDistances for Area: ar4000
[WorldMap/DEBUG]: Gathering path information for: ar2100
[WorldMap/DEBUG]: Adding path to 2
[WorldMap/DEBUG]: Walkpath size is: 1
[ResourceManager/ERROR]: Couldn't find 'bntychnc.2da'.

Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.
--Type <RET> for more, q to quit, c to continue without paging--
0x00007ffff6807119 in GemRB_WorldMap_GetDestinationArea (
    self=<GWorldMap at remote 0x7fffa355b0d0>, Python Exception <class 'gdb.error'> There is no member named ob_base.: 
args=)
    at /home/elvire/gemrb/gemrb/gemrb/plugins/GUIScript/GUIScript.cpp:3159
3159						if (area[0]) {
(gdb) bt
#0  0x00007ffff6807119 in GemRB_WorldMap_GetDestinationArea (
    self=<GWorldMap at remote 0x7fffa355b0d0>, Python Exception <class 'gdb.error'> There is no member named ob_base.: 
args=)
    at /home/elvire/gemrb/gemrb/gemrb/plugins/GUIScript/GUIScript.cpp:3159
#1  0x00007ffff66bea5c in PyEval_EvalFrameEx ()
   from /usr/lib64/libpython2.7.so.1.0
#2  0x00007ffff66c281b in PyEval_EvalCodeEx ()
   from /usr/lib64/libpython2.7.so.1.0
#3  0x00007ffff66bf85c in PyEval_EvalFrameEx ()
   from /usr/lib64/libpython2.7.so.1.0
#4  0x00007ffff66c281b in PyEval_EvalCodeEx ()
   from /usr/lib64/libpython2.7.so.1.0
#5  0x00007ffff6639ddb in ?? () from /usr/lib64/libpython2.7.so.1.0
#6  0x00007ffff660b792 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#7  0x00007ffff66b8267 in PyEval_CallObjectWithKeywords ()
   from /usr/lib64/libpython2.7.so.1.0
#8  0x00007ffff682426b in GemRB::CallPython<int, &GemRB::noop<int> > (
    function=<function at remote 0x7fffe82216d0>, args=0x0, 
    retVal=0x7fffffffbbbc)
    at /home/elvire/gemrb/gemrb/gemrb/plugins/GUIScript/PythonCallbacks.h:46
#9  0x00007ffff6822fc5 in GemRB::CallPython (
    function=<function at remote 0x7fffe82216d0>, args=0x0)
    at /home/elvire/gemrb/gemrb/gemrb/plugins/GUIScript/PythonCallbacks.h:66
#10 0x00007ffff682c016 in GemRB::PythonComplexCallback<void, GemRB::Control*>::o--Type <RET> for more, q to quit, c to continue without paging--
perator() (this=0x555560289ee0, arg=0x555563b65c60)
    at /home/elvire/gemrb/gemrb/gemrb/plugins/GUIScript/PythonCallbacks.h:132
#11 0x00007ffff682b70e in std::__invoke_impl<void, GemRB::PythonComplexCallback<void, GemRB::Control*>&, GemRB::Control*> (__f=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/bits/invoke.h:60
#12 0x00007ffff682a877 in std::__invoke_r<void, GemRB::PythonComplexCallback<void, GemRB::Control*>&, GemRB::Control*> (__fn=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/bits/invoke.h:153
#13 0x00007ffff68298d3 in std::_Function_handler<void (GemRB::Control*), GemRB::PythonComplexCallback<void, GemRB::Control*> >::_M_invoke(std::_Any_data const&, GemRB::Control*&&) (__functor=..., __args#0=@0x7fffffffbc80: 0x555563b65c60)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/bits/std_function.h:291
#14 0x00007ffff7d0f95d in std::function<void (GemRB::Control*)>::operator()(GemRB::Control*) const (this=0x555560114ee8, __args#0=0x555563b65c60)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/bits/std_function.h:622
#15 0x00007ffff7d0f0d3 in GemRB::View::ActionResponder<GemRB::Control*>::Responder::operator() (this=0x555560114ee8, responder=0x555563b65c60)
    at /home/elvire/gemrb/gemrb/gemrb/core/GUI/ViewInterfaces.h:74
#16 0x00007ffff7d0cafc in GemRB::Control::PerformAction (this=0x555563b65c60, 
    key=...) at /home/elvire/gemrb/gemrb/gemrb/core/GUI/Control.cpp:111
--Type <RET> for more, q to quit, c to continue without paging--
#17 0x00007ffff7d0d37b in GemRB::Control::OnMouseUp (this=0x555563b65c60, 
    me=..., mod=0) at /home/elvire/gemrb/gemrb/gemrb/core/GUI/Control.cpp:251
#18 0x00007ffff7d6f078 in GemRB::WorldMapControl::OnMouseUp (
    this=0x555563b65c60, me=..., Mod=0)
    at /home/elvire/gemrb/gemrb/gemrb/core/GUI/WorldMapControl.cpp:272
#19 0x00007ffff7d59fd7 in GemRB::View::MouseUp (this=0x555563b65c60, me=..., 
    mod=0) at /home/elvire/gemrb/gemrb/gemrb/core/GUI/View.cpp:760
#20 0x00007ffff7d5fd15 in GemRB::Window::DispatchMouseUp (this=0x55555b572730, 
    target=0x555563b65c60, me=..., mod=0)
    at /home/elvire/gemrb/gemrb/gemrb/core/GUI/Window.cpp:395
#21 0x00007ffff7d5eeeb in GemRB::Window::DispatchEvent (this=0x55555b572730, 
    event=...) at /home/elvire/gemrb/gemrb/gemrb/core/GUI/Window.cpp:547
#22 0x00007ffff7d64e9d in GemRB::WindowManager::DispatchEvent (
    this=0x555555f95110, event=...)
    at /home/elvire/gemrb/gemrb/gemrb/core/GUI/WindowManager.cpp:381
#23 0x00007ffff7d6d4e1 in std::__invoke_impl<bool, bool (GemRB::WindowManager::*&)(GemRB::Event const&), GemRB::WindowManager*&, GemRB::Event const&> (__f=
    @0x555560e2fc00: (bool (GemRB::WindowManager::*)(GemRB::WindowManager * const, const GemRB::Event &)) 0x7ffff7d64db2 <GemRB::WindowManager::DispatchEvent(GemRB::Event const&)>, __t=@0x555560e2fc10: 0x555555f95110)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/bits/invoke.h:73
#24 0x00007ffff7d6d11d in std::__invoke<bool (GemRB::WindowManager::*&)(GemRB::Event const&), GemRB::WindowManager*&, GemRB::Event const&> (__fn=
--Type <RET> for more, q to quit, c to continue without paging--
    @0x555560e2fc00: (bool (GemRB::WindowManager::*)(GemRB::WindowManager * const, const GemRB::Event &)) 0x7ffff7d64db2 <GemRB::WindowManager::DispatchEvent(GemRB::Event const&)>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/bits/invoke.h:95
#25 0x00007ffff7d6c9cf in std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>::__call<bool, GemRB::Event const&, 0ul, 1ul>(std::tuple<GemRB::Event const&>&&, std::_Index_tuple<0ul, 1ul>) (this=0x555560e2fc00, __args=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/functional:416
#26 0x00007ffff7d6c3b7 in std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>::operator()<GemRB::Event const&, bool>(GemRB::Event const&) (this=0x555560e2fc00)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/functional:499
#27 0x00007ffff7d6b5db in std::__invoke_impl<bool, std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>&, GemRB::Event const&>(std::__invoke_other, std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>&, GemRB::Event const&) (__f=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/bits/invoke.h:60
#28 0x00007ffff7d699f7 in std::__invoke_r<bool, std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>&, GemRB::Event const&>(std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>&, GemRB::Event const&) (
--Type <RET> for more, q to quit, c to continue without paging--
    __fn=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/bits/invoke.h:141
#29 0x00007ffff7d684c6 in std::_Function_handler<bool (GemRB::Event const&), std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)> >::_M_invoke(std::_Any_data const&, GemRB::Event const&) (__functor=..., __args#0=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/bits/std_function.h:291
#30 0x00007ffff7d14913 in std::function<bool (GemRB::Event const&)>::operator()(GemRB::Event const&) const (this=0x555561416510, __args#0=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/bits/std_function.h:622
#31 0x00007ffff7d12752 in GemRB::EventMgr::DispatchEvent (this=0x555555f95200, 
    e=...) at /home/elvire/gemrb/gemrb/gemrb/core/GUI/EventMgr.cpp:279
#32 0x00007ffff6557224 in GemRB::SDLVideoDriver::ProcessEvent (
    this=0x555555588c10, event=...)
    at /home/elvire/gemrb/gemrb/gemrb/plugins/SDLVideo/SDLVideo.cpp:211
#33 0x00007ffff6564993 in GemRB::SDL20VideoDriver::ProcessEvent (
    this=0x555555588c10, event=...)
    at /home/elvire/gemrb/gemrb/gemrb/plugins/SDLVideo/SDL20Video.cpp:768
#34 0x00007ffff6556ca9 in GemRB::SDLVideoDriver::PollEvents (
    this=0x555555588c10)
--Type <RET> for more, q to quit, c to continue without paging--
    at /home/elvire/gemrb/gemrb/gemrb/plugins/SDLVideo/SDLVideo.cpp:63
#35 0x00007ffff7eb5e0c in GemRB::Video::SwapBuffers (this=0x555555588c10, 
    fpscap=30) at /home/elvire/gemrb/gemrb/gemrb/core/Video.cpp:165
#36 0x00007ffff7dd3a5d in GemRB::Interface::Main (this=0x55555556eb50)
    at /home/elvire/gemrb/gemrb/gemrb/core/Interface.cpp:946
#37 0x00005555555553a5 in main (argc=3, argv=0x7fffffffdc38)
    at /home/elvire/gemrb/gemrb/gemrb/GemRB.cpp:73
```

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
something is wrong with your python install

**Comment by bradallred** [comment]
I couldn't repro. going to need more info. what game?

**Comment by FrElvire** [comment]
iwd1, yes it's gdb output, but can' reproduce anymore. I will do some more test and close if I can't reproduce....very strange

**Comment by FrElvire** [comment]
can't reproduce
