### ISSUE TITLE
Error/crash when opening bag 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1364]
When opening bag there is a python error and seems to lead to crash.

console : 

```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "../gemrb/GUIScripts/GUISTORE.py", line 260, in OpenStoreWindow
[Python/ERROR]:     Button.SetTooltip (storetips[Action])
[Python/ERROR]: IndexError: tuple index out of range
```

same things with iwd1 and bg2

suspected crash related to this (append when "playing" with bag)

```
[ResourceManager]: Found 'guistbsb.mos' in 'chitin.key'.
[GameData/FATAL]: Saving a store that wasn't cached.
[Thread 0x7fffe88ef640 (LWP 15619) exited]
[Thread 0x7fffe90f0640 (LWP 15612) exited]
[Thread 0x7fffe98f1640 (LWP 15611) exited]
[Thread 0x7fffea0f2640 (LWP 15610) exited]
[Thread 0x7ffff4ca7640 (LWP 15609) exited]
[Thread 0x7fffd2140640 (LWP 15620) exited]
[Thread 0x7ffff75e3640 (LWP 15606) exited]
[Thread 0x7fffd113e640 (LWP 15622) exited]
[Thread 0x7fffd093d640 (LWP 15623) exited]
[Thread 0x7fffd193f640 (LWP 15621) exited]
[Thread 0x7ffff75e7140 (LWP 15602) exited]
--Type <RET> for more, q to quit, c to continue without paging--
[Inferior 1 (process 15602) exited with code 01]
(gdb) bt
No stack.
```
```

[ResourceManager]: Found 'guistbbb.mos' in 'chitin.key'.

Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.
--Type <RET> for more, q to quit, c to continue without paging--
0x00007ffff7e973de in GemRB::Store::GetItem (this=0x555558e4a380, idx=118, 
    usetrigger=true) at /home/elvire/gemrb/gemrb/gemrb/core/Store.cpp:181
181			return items[idx];
(gdb) bt
#0  0x00007ffff7e973de in GemRB::Store::GetItem (this=0x555558e4a380, idx=118, 
    usetrigger=true) at /home/elvire/gemrb/gemrb/gemrb/core/Store.cpp:181
#1  0x00007ffff67d894a in GemRB_IsValidStoreItem (Python Exception <class 'gdb.error'> There is no member named ob_base.: 
args=)
    at /home/elvire/gemrb/gemrb/gemrb/plugins/GUIScript/GUIScript.cpp:7390
#2  0x00007ffff66891dd in PyEval_EvalFrameEx ()
   from /usr/lib64/libpython2.7.so.1.0
#3  0x00007ffff6688af3 in PyEval_EvalFrameEx ()
   from /usr/lib64/libpython2.7.so.1.0
#4  0x00007ffff6688af3 in PyEval_EvalFrameEx ()
   from /usr/lib64/libpython2.7.so.1.0
#5  0x00007ffff6688af3 in PyEval_EvalFrameEx ()
   from /usr/lib64/libpython2.7.so.1.0
#6  0x00007ffff668a81b in PyEval_EvalCodeEx ()
   from /usr/lib64/libpython2.7.so.1.0
#7  0x00007ffff668785c in PyEval_EvalFrameEx ()
   from /usr/lib64/libpython2.7.so.1.0
#8  0x00007ffff668a81b in PyEval_EvalCodeEx ()
   from /usr/lib64/libpython2.7.so.1.0
#9  0x00007ffff6601ddb in ?? () from /usr/lib64/libpython2.7.so.1.0
#10 0x00007ffff65d3792 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#11 0x00007ffff6680267 in PyEval_CallObjectWithKeywords ()
   from /usr/lib64/libpython2.7.so.1.0
#12 0x00007ffff67e900b in GemRB::GUIScript::RunFunction (this=0x5555556612e0, 
--Type <RET> for more, q to quit, c to continue without paging--
    moduleName=0x7ffff7ecf7d1 "GUICommonWindows", 
    functionName=0x7ffff7ecf7c0 "SelectionChanged", pArgs=0x0, 
    report_error=false)
    at /home/elvire/gemrb/gemrb/gemrb/plugins/GUIScript/GUIScript.cpp:13787
#13 0x00007ffff67e90ce in GemRB::GUIScript::RunFunction (this=0x5555556612e0, 
    moduleName=0x7ffff7ecf7d1 "GUICommonWindows", 
    functionName=0x7ffff7ecf7c0 "SelectionChanged", report_error=false, 
    intparam=-1)
    at /home/elvire/gemrb/gemrb/gemrb/plugins/GUIScript/GUIScript.cpp:13805
#14 0x00007ffff7dc3dba in GemRB::Interface::HandleEvents (this=0x55555556eb50)
    at /home/elvire/gemrb/gemrb/gemrb/core/Interface.cpp:348
#15 0x00007ffff7dc6213 in GemRB::Interface::Main (this=0x55555556eb50)
    at /home/elvire/gemrb/gemrb/gemrb/core/Interface.cpp:866
#16 0x00005555555553a5 in main (argc=3, argv=0x7fffffffdc68)
    at /home/elvire/gemrb/gemrb/gemrb/GemRB.cpp:73
(gdb) 
```

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
That's probably also the reason why there are too many icons (store types) displayed.

I can't make it crash, so please let us know if you find a way.

**Comment by FrElvire** [comment]
humm....I can trigger a crash but not reliably, it involved opening bag in inventory and trying to open it in store (multiple times) but can't find a pattern.

The more I try, the less it crash....

**Comment by FrElvire** [comment]
I forgot to write the first symptom I remarked... : you can't open a bag in shop to sell something in

**Comment by lynxlynxlynx** [comment]
Ah, it's from a type change, so there's an underflow of sorts.

**Comment by lynxlynxlynx** [comment]
That should do it. If you still can't open bags in stores or find other issues, please open new reports.
