### ISSUE TITLE
[bug] Game will freeze if entering inventory of a creature that does not have paperdoll

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#140]
BG2. On original engine the game does not freeze when going to inventory. 

```
[ResourceManager/ERROR]: Couldn't find 'NSIMINV.bam'.
[GUISCript/WARNING]: PLT/BAM not found for ref: NSIMINV
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "C:/Users/Cygar/Desktop/Misc Files/Black Isles/_GemRB/GUIScripts/bg2\GUIINV.py", line 231, in RefreshInventoryWindow
[Python/ERROR]:     Color1, Color2, Color3, Color4, Color5, Color6, Color7, 0, 0)
[Python/ERROR]:   File "C:/Users/Cygar/Desktop/Misc Files/Black Isles/_GemRB/GUIScripts\MetaClasses.py", line 60, in <lambda>
[Python/ERROR]:     return lambda self, *args: M(self.WinID, self.ID, *args)
[Python/ERROR]: SystemError: error return without exception set
[ResourceManager/WARNING]: 'NSIMINV.bam' not found...
[Python]: GetActorPaperDoll: Missing paper doll for animation 0xC900 LEVEL1 NSIMINV
[ResourceManager/ERROR]: Couldn't find 'NSIMINV.bam'.
[GUISCript/WARNING]: PLT/BAM not found for ref: NSIMINV
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "C:/Users/Cygar/Desktop/Misc Files/Black Isles/_GemRB/GUIScripts/bg2\GUIINV.py", line 175, in OpenInventoryWindow
[Python/ERROR]:     UpdateInventoryWindow ()
[Python/ERROR]:   File "C:/Users/Cygar/Desktop/Misc Files/Black Isles/_GemRB/GUIScripts/bg2\GUIINV.py", line 192, in UpdateInventoryWindow
[Python/ERROR]:     RefreshInventoryWindow ()
[Python/ERROR]:   File "C:/Users/Cygar/Desktop/Misc Files/Black Isles/_GemRB/GUIScripts/bg2\GUIINV.py", line 231, in RefreshInventoryWindow
[Python/ERROR]:     Color1, Color2, Color3, Color4, Color5, Color6, Color7, 0, 0)
[Python/ERROR]:   File "C:/Users/Cygar/Desktop/Misc Files/Black Isles/_GemRB/GUIScripts\MetaClasses.py", line 60, in <lambda>
[Python/ERROR]:     return lambda self, *args: M(self.WinID, self.ID, *args)
[Python/ERROR]: SystemError: error return without exception set
```

The log comes from entering peasant actor inventory.

**Comment by lynxlynxlynx** [comment]
Should be fixed in the current build, thanks! Please reopen if that's not the case.
