### ISSUE TITLE
[python3.9] Some errors

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1400]
#### Bug description
Using python 3.9.6 to compile and run when loading a save here is some error in console and some elements are missing 

In iwd1 (not bg2)
```
MUSImporter]: Playing MX7000/MX7000A...
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/GUICommonWindows.py", line 595, in UpdateActionsWindow
[Python/ERROR]:     UpdateClock ()
[Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/Clock.py", line 56, in UpdateClock
[Python/ERROR]:     if Clock.IsVisible() == False:
[Python/ERROR]: AttributeError: 'NoneType' object has no attribute 'IsVisible'
[OpenAL]: Music in INITIAL State. AutoStarting
```

left button bar doesn't work, but with keyboard shortcut it's better : option window by example is displayed (iwd1 & bg2) but with some errors (iwd1 only)

```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/GUIOPT.py", line 466, in QuitGamePress
[Python/ERROR]:     GUICommonWindows.CloseTopWindow ()
[Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/GUICommonWindows.py", line 1291, in CloseTopWindow
[Python/ERROR]:     UpdateClock()
[Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/Clock.py", line 56, in UpdateClock
[Python/ERROR]:     if Clock.IsVisible() == False:
[Python/ERROR]: AttributeError: 'NoneType' object has no attribute 'IsVisible'

```

When quitting game, with window cross and quit button, segfault (#1403)

Which version of python3 did you use ? I can if needed make test with 3.6, 3.7 and 3.8

#### Steps to reproduce
1. Use python 3.9(.6) to compile
2. Load a save..'

#### Screenshots
![image](https://user-images.githubusercontent.com/55502325/127958436-f2a8a3d9-7b23-4606-87bb-226ffd30f298.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
What resolution is this at? Looks like a missing control in one of the chus.

**Comment by FrElvire** [comment]
the resolution is 1280x800
issue 1&2 are not present with python 2.7

segmentation fault at exit (3) is also present with python 2.7, #1403 created

**Comment by lynxlynxlynx** [comment]
Is that the first python error that appears in the log though?

**Comment by FrElvire** [comment]
oh yes you're right, I didn't see them...

they append at game load after "validating" party member

```
ResourceManager]: Found 'guilsop.bam' in 'chitin.key'.
[ResourceManager/WARNING]: 'worldm25.wmp' not found...
[GUIScript/ERROR]: Runtime Error:
[Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/GUIPR.py", line 285
[Python/ERROR]:     Window.Close()
[Python/ERROR]: TabError: inconsistent use of tabs and spaces in indentation
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/MetaClasses.py", line 59, in handler
[Python/ERROR]:     return f(*args, **kwargs)
[Python/ERROR]: RuntimeError: Hot key map referenced a moduleName that doesnt exist.
[Python/ERROR]: 
During handling of the above exception, another exception occurred:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/iwd/Game.py", line 32, in EnterGame
[Python/ERROR]:     MessageWindow.OnLoad()
[Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/MessageWindow.py", line 76, in OnLoad
[Python/ERROR]:     GUICommonWindows.SetupMenuWindowControls (OptionsWindow, 1, None)
[Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/GUICommonWindows.py", line 224, in SetupMenuWindowControls
[Python/ERROR]:     Button = InitOptionButton(Window, 'Priest_Spells')
[Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/GUICommonWindows.py", line 115, in InitOptionButton
[Python/ERROR]:     Button.SetHotKey (Index, True)
[Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/MetaClasses.py", line 61, in handler
[Python/ERROR]:     raise type(e)(str(e) + "\nMethod Docs:\n" + str(f.__doc__))
[Python/ERROR]: RuntimeError: Hot key map referenced a moduleName that doesnt exist.
Method Docs:
===== Button_SetHotKey =====

**Prototype:** _GemRB.Button_SetHotKey(char or keymaping[, modifiers=0, global=False])

**Description:** Binds a keyboard key to trigger the control event when its window is focused.
If global is set, the hot key works even if the window does not have focus.
If None is passed as the key, any existing hotkey binding is cleared.

**Parameters:**
 * char - key to bind
 * modifiers - bitfield denoting if modifier keys need to be pressed
   * GEM_MOD_SHIFT (1) - shift
   * GEM_MOD_CTRL (2) - control
   * GEM_MOD_ALT (4) - alt
 * global - boolean toggling focus requirement

**Return value:** N/A
[ResourceManager]: Found 'guils.chu' in 'GemRB Unhardcoded data'.
[ResourceManager]: Searching for 'gprogbar'...
```

and later

```
Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/GUICommonWindows.py", line 595, in UpdateActionsWindow
[Python/ERROR]:     UpdateClock ()
[Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/Clock.py", line 56, in UpdateClock
[Python/ERROR]:     if Clock.IsVisible() == False:
[Python/ERROR]: AttributeError: 'NoneType' object has no attribute 'IsVisible'

```

**Comment by lynxlynxlynx** [comment]
How about now?

**Comment by FrElvire** [comment]
All is now OK :+1:
