### ISSUE TITLE
BG1/BG2 (with BGT): Crash on trying to show the world map while waylaid

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1411]
#### Bug description
When waylaid, opening the map and clicking on the world map button crashes the game.

Tested in both, unmodded BG1 and BG2 with BGT. 
Tested only in the current git version.

Backtrace: 
```
Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e07833 in GemRB::Point::operator- (this=0x7fffffffc4b8, p=...)
    at /home/laula/Games/gemrb/gemrb/core/Region.cpp:42
42        return Point(x - p.x, y - p.y);
(gdb) bt
#0  0x00007ffff7e07833 in GemRB::Point::operator- (this=0x7fffffffc4b8, p=...)
    at /home/laula/Games/gemrb/gemrb/core/Region.cpp:42
#1  0x00007ffff7d1bd7c in GemRB::WorldMapControl::DrawSelf (
    this=0x555563563140, rgn=...)
    at /home/laula/Games/gemrb/gemrb/core/GUI/WorldMapControl.cpp:118
#2  0x00007ffff7d05469 in GemRB::View::Draw (this=0x555563563140)
    at /home/laula/Games/gemrb/gemrb/core/GUI/View.cpp:274
#3  0x00007ffff7d04e6e in GemRB::View::DrawSubviews (this=0x55555dd96db8)
    at /home/laula/Games/gemrb/gemrb/core/GUI/View.cpp:209
#4  0x00007ffff7d05522 in GemRB::View::Draw (this=0x55555dd96db8)
    at /home/laula/Games/gemrb/gemrb/core/GUI/View.cpp:285
#5  0x00007ffff7d04e6e in GemRB::View::DrawSubviews (this=0x55555dd96c90)
    at /home/laula/Games/gemrb/gemrb/core/GUI/View.cpp:209
#6  0x00007ffff7d05522 in GemRB::View::Draw (this=0x55555dd96c90)
    at /home/laula/Games/gemrb/gemrb/core/GUI/View.cpp:285
#7  0x00007ffff7d12772 in GemRB::WindowManager::DrawWindows (
    this=0x5555559bc9e0)
    at /home/laula/Games/gemrb/gemrb/core/GUI/WindowManager.cpp:616
#8  0x00007ffff7d8a3da in GemRB::Interface::Main (this=0x555555570b20)
    at /home/laula/Games/gemrb/gemrb/core/Interface.cpp:783
#9  0x00005555555563b5 in main (argc=3, argv=0x7fffffffdce8)
    at /home/laula/Games/gemrb/gemrb/GemRB.cpp:73
```

#### Steps to reproduce
1. Run back and forth until you get waylaid
2. Open the map and click on the world map button

#### Expected behavior
Don't crash. Show the world map with the position marker between the previous map and the target map. 

#### Screenshots
Original Baldur's Gate 2 (with BGT) showing the world map with the position marker between the two maps

![unknown](https://user-images.githubusercontent.com/68446748/128606201-383a54c4-8e8b-4202-9a08-c355ee1f4116.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

**Comment by bradallred** [comment]
reopen if that didnt fix it
