### ISSUE TITLE
BG1/BG2: Pressing middle mouse button while on the travel map crashes the game 

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1415]
#### Bug description
Pressing middle mouse button while on the travel map crashes the game .
Doesn't happen on 0.8.8 or 0.9.0.

Backtrace (BG1): 
```
Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.
0x00007ffff7d06c62 in GemRB::View::TextInput (this=0x0, te=...) at /home/laula/Games/gemrb/gemrb/core/GUI/View.cpp:722
722		if (eventProxy) {
(gdb) bt
#0  0x00007ffff7d06c62 in GemRB::View::TextInput (this=0x0, te=...) at /home/laula/Games/gemrb/gemrb/core/GUI/View.cpp:722
#1  0x00007ffff7d0bce3 in GemRB::Window::DispatchEvent (this=0x555559ab8950, event=...)
    at /home/laula/Games/gemrb/gemrb/core/GUI/Window.cpp:478
#2  0x00007ffff7d1228d in GemRB::WindowManager::DispatchEvent (this=0x5555559f06b0, event=...)
    at /home/laula/Games/gemrb/gemrb/core/GUI/WindowManager.cpp:419
#3  0x00007ffff7d1ae17 in std::__invoke_impl<bool, bool (GemRB::WindowManager::*&)(GemRB::Event const&), GemRB::WindowManager*&, GemRB::Event const&> (__f=
    @0x55555aadd980: (bool (GemRB::WindowManager::*)(GemRB::WindowManager * const, const GemRB::Event &)) 0x7ffff7d11ed6 <GemRB::WindowManager::DispatchEvent(GemRB::Event const&)>, __t=@0x55555aadd990: 0x5555559f06b0) at /usr/include/c++/11.1.0/bits/invoke.h:74
#4  0x00007ffff7d1a999 in std::__invoke<bool (GemRB::WindowManager::*&)(GemRB::Event const&), GemRB::WindowManager*&, GemRB::Event const&> (__fn=
    @0x55555aadd980: (bool (GemRB::WindowManager::*)(GemRB::WindowManager * const, const GemRB::Event &)) 0x7ffff7d11ed6 <GemRB::WindowManager::DispatchEvent(GemRB::Event const&)>) at /usr/include/c++/11.1.0/bits/invoke.h:96
#5  0x00007ffff7d1a191 in std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>::__call<bool, GemRB::Event const&, 0ul, 1ul>(std::tuple<GemRB::Event const&>&&, std::_Index_tuple<0ul, 1ul>) (this=0x55555aadd980, 
    __args=...) at /usr/include/c++/11.1.0/functional:420
#6  0x00007ffff7d199e5 in std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>::operator()<GemRB::Event const&, bool>(GemRB::Event const&) (this=0x55555aadd980) at /usr/include/c++/11.1.0/functional:503
#7  0x00007ffff7d18a23 in std::__invoke_impl<bool, std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>&, GemRB::Event const&>(std::__invoke_other, std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>&, GemRB::Event const&) (__f=...) at /usr/include/c++/11.1.0/bits/invoke.h:61
#8  0x00007ffff7d16c6b in std::__invoke_r<bool, std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>&, GemRB::Event const&>(std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>&, GemRB::Event const&) (__fn=...) at /usr/include/c++/11.1.0/bits/invoke.h:142
#9  0x00007ffff7d15660 in std::_Function_handler<bool (GemRB::Event const&), std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)> >::_M_invoke(std::_Any_data const&, GemRB::Event const&) (__functor=..., 
    __args#0=...) at /usr/include/c++/11.1.0/bits/std_function.h:291
#10 0x00007ffff7cc1231 in std::function<bool (GemRB::Event const&)>::operator()(GemRB::Event const&) const (this=0x555555fa5fb0, 
    __args#0=...) at /usr/include/c++/11.1.0/bits/std_function.h:560
#11 0x00007ffff7cbf01e in GemRB::EventMgr::DispatchEvent (this=0x5555559f07a0, e=...)
    at /home/laula/Games/gemrb/gemrb/core/GUI/EventMgr.cpp:279
#12 0x00007ffff5e5627c in GemRB::SDL20VideoDriver::ProcessEvent (this=0x55555558ba10, event=...)
    at /home/laula/Games/gemrb/gemrb/plugins/SDLVideo/SDL20Video.cpp:766
#13 0x00007ffff5e49dbf in GemRB::SDLVideoDriver::PollEvents (this=0x55555558ba10)
    at /home/laula/Games/gemrb/gemrb/plugins/SDLVideo/SDLVideo.cpp:63
#14 0x00007ffff7e8ce94 in GemRB::Video::SwapBuffers (this=0x55555558ba10, fpscap=30)
    at /home/laula/Games/gemrb/gemrb/core/Video/Video.cpp:163
#15 0x00007ffff7d8a5c0 in GemRB::Interface::Main (this=0x555555570b20) at /home/laula/Games/gemrb/gemrb/core/Interface.cpp:797
#16 0x00005555555563b5 in main (argc=3, argv=0x7fffffffdd78) at /home/laula/Games/gemrb/gemrb/GemRB.cpp:73
```

#### Steps to reproduce
1. Go to the edge of a map
2. Initiate travel
3. Press the middle mouse button

#### Expected behavior
Not crash.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

**Comment by bradallred** [comment]
to repro you need text on your clipboard :)
