### ISSUE TITLE
[IWD1] crash during battle with salamander

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1422]
short time after combat begins in IWD1 with salamander (ice or fire), game crash

```
[CharAnimations/DEBUG]: Truncating animation ref (wqMH0DDg1) to size.
[ResourceManager/ERROR]: Couldn't find 'wqMH0DDg.bam'.
[ModifyDamage/COMBAT]: Resisted 0 of 1 at 15% resistance to 8
[Actor/COMBAT]: 1 fire damage taken.

[Actor/COMBAT]: Damage animation type: 4
[ResourceManager]: Found 'FIREH.bam' in 'chitin.key'.
[ResourceManager]: Found 'FIREL.bam' in 'chitin.key'.
free(): double free detected in tcache 2
[EffectQueue]: Unknown FX target type: 0

Thread 1 "gemrb" received signal SIGABRT, Aborted.
0x00007ffff75ac721 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff75ac721 in raise () from /lib64/libc.so.6
#1  0x00007ffff7596536 in abort () from /lib64/libc.so.6
#2  0x00007ffff75edd28 in ?? () from /lib64/libc.so.6
#3  0x00007ffff75f577a in ?? () from /lib64/libc.so.6
#4  0x00007ffff75f72e2 in ?? () from /lib64/libc.so.6
#5  0x00007ffff75fa8c4 in free () from /lib64/libc.so.6
#6  0x00007ffff7cb0708 in GemRB::EffectQueue::~EffectQueue (
    this=0x55555bff2110, __in_chrg=<optimized out>)
    at /home/elvire/gemrb/gemrb/gemrb/core/EffectQueue.cpp:325
#7  0x00007ffff7cb0742 in GemRB::EffectQueue::~EffectQueue (
    this=0x55555bff2110, __in_chrg=<optimized out>)
    at /home/elvire/gemrb/gemrb/gemrb/core/EffectQueue.cpp:327
#8  0x00007ffff7da3667 in GemRB::Interface::ApplyEffect (this=0x55555556eb50, 
    effect=0x555559c1cff0, actor=0x5555567b59b0, caster=0x55555708ea20)
    at /home/elvire/gemrb/gemrb/gemrb/core/Interface.cpp:4090
#9  0x00007ffff682b3f1 in fx_salamander_aura (Owner=0x55555708ea20, 
    target=0x55555708ea20, fx=0x55555c324b00)
    at /home/elvire/gemrb/gemrb/gemrb/plugins/IWDOpcodes/IWDOpcodes.cpp:1110
#10 0x00007ffff7cb79fa in GemRB::EffectDesc::operator() (
    this=0x7ffff7fbc6e8 <GemRB::Opcodes+6120>, s=0x55555708ea20, 
    a=0x55555708ea20, fx=0x55555c324b00)
    at /home/elvire/gemrb/gemrb/gemrb/core/EffectQueue.h:184
#11 0x00007ffff7cb3627 in GemRB::EffectQueue::ApplyEffect (
--Type <RET> for more, q to quit, c to continue without paging--
    this=0x55555708f8a8, target=0x55555708ea20, fx=0x55555c324b00, 
    first_apply=0, resistance=1)
    at /home/elvire/gemrb/gemrb/gemrb/core/EffectQueue.cpp:1254
#12 0x00007ffff7cb0e3f in GemRB::EffectQueue::ApplyAllEffects (
    this=0x55555708f8a8, target=0x55555708ea20)
    at /home/elvire/gemrb/gemrb/gemrb/core/EffectQueue.cpp:482
#13 0x00007ffff7e298a5 in GemRB::Actor::RefreshEffects (this=0x55555708ea20, 
    fx=0x0) at /home/elvire/gemrb/gemrb/gemrb/core/Scriptable/Actor.cpp:3162
#14 0x00007ffff7dd3e1a in GemRB::Map::UpdateEffects (this=0x55555b163850)
    at /home/elvire/gemrb/gemrb/gemrb/core/Map.cpp:1839
#15 0x00007ffff7d88d43 in GemRB::GlobalTimer::Update (this=0x55555556eef8)
    at /home/elvire/gemrb/gemrb/gemrb/core/GlobalTimer.cpp:167
#16 0x00007ffff7d9f767 in GemRB::Interface::GSUpdate (this=0x55555556eb50, 
    update_scripts=true)
    at /home/elvire/gemrb/gemrb/gemrb/core/Interface.cpp:2933
#17 0x00007ffff7d9d1f6 in GemRB::Interface::GameLoop (this=0x55555556eb50)
    at /home/elvire/gemrb/gemrb/gemrb/core/Interface.cpp:2386
#18 0x00007ffff7d95a97 in GemRB::Interface::Main (this=0x55555556eb50)
    at /home/elvire/gemrb/gemrb/gemrb/core/Interface.cpp:778
#19 0x00005555555553a5 in main (argc=3, argv=0x7fffffffdc68)
    at /home/elvire/gemrb/gemrb/gemrb/GemRB.cpp:73
```
#### Save

[000000077-fin 5ieme chapitre.zip](https://github.com/gemrb/gemrb/files/6961131/000000077-fin.5ieme.chapitre.zip)

#### Steps to reproduce
1. load save
2. enter cavern to 
begin chapter 6
3. fight against fire salamander

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Great, thanks.
