### ISSUE TITLE
4-byte lightmaps -> assertion failed

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1428]
A user is hitting the new assert:
https://www.gibberlings3.net/forums/topic/33034-crash-when-spell-casting-duplicated-on-two-installs-and-crash-on-npc-leaving-area/?do=findComment&comment=297565

@laulajatar had no problems with the same basic setup, so it's still weird. Lightmaps are not something mods usually touch.

**Comment by bradallred** [comment]
are you sure they are 4bit? 4 bit should still be a BPP of 1 and work fine.

can we get an offender to have a look at?

**Comment by lynxlynxlynx** [comment]
It's been attached to the thread now. Just expand the spoilers in the linked post to see it's reported as 4.

file says:
```
# one of mine
ar4000lm.bmp: PC bitmap, Windows 3.x format, 160 x 160 x 8, image size 25600, 256 important colors, cbSize 26678, bits offset 1078

# his
AR0015LM.BMP: PC bitmap, Windows 3.x format, 320 x 320 x 8, image size 102400, resolution 2834 x 2834 px/m, 256 important colors, cbSize 103478, bits offset 1078
AR6600LM.BMP: PC bitmap, Windows 3.x format, 320 x 320 x 8, resolution 2834 x 2834 px/m, 45 important colors, cbSize 102636, bits offset 234
```
So the input doesn't look 4-bit.

**Comment by bradallred** [comment]
oh, 4 _bytes_ so 32bit

**Comment by Darpaek** [comment]
[WeiDU.log](https://github.com/gemrb/gemrb/files/6984824/WeiDU.log)

My Weidu.log, but I pulled those out of the base game BIFs, not my override.  The GoG Windows game version.

![image](https://user-images.githubusercontent.com/6020153/129410535-fe95235d-7d29-42b4-b87f-9df9f474ccd6.png)

**Comment by lynxlynxlynx** [comment]
@Darpaek try a rebuild now:
```
git pull
make -j3
```

**Comment by Darpaek** [comment]
```
Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.
0x00007ffff7ed1520 in GemRB::Held<GemRB::Palette>::release (
    this=<optimized out>) at /home/darpaek/gemrb/gemrb/core/Holder.h:80
80		~Holder() noexcept
(gdb) bt
#0  0x00007ffff7ed1520 in GemRB::Held<GemRB::Palette>::release (
    this=<optimized out>) at /home/darpaek/gemrb/gemrb/core/Holder.h:80
#1  GemRB::Holder<GemRB::Palette>::~Holder (this=<optimized out>, 
    __in_chrg=<optimized out>) at /home/darpaek/gemrb/gemrb/core/Holder.h:83
#2  GemRB::Map::GetLighting (this=0x55555affb370, p=...)
    at /home/darpaek/gemrb/gemrb/core/Map.cpp:2454
#3  0x00007ffff7edb83b in GemRB::Map::DrawMap (this=this@entry=0x55555affb370, 
    viewport=..., dFlags=dFlags@entry=0)
    at /home/darpaek/gemrb/gemrb/core/Map.cpp:1331
#4  0x00007ffff7e4a3c8 in GemRB::GameControl::DrawSelf (this=0x555558211d20, 
    screen=...) at /home/darpaek/gemrb/gemrb/core/GUI/GameControl.cpp:579
#5  0x00007ffff7e64fd8 in GemRB::View::Draw (this=0x555558211d20)
    at /home/darpaek/gemrb/gemrb/core/GUI/View.cpp:274
#6  0x00007ffff7e65135 in GemRB::View::DrawSubviews (
    this=this@entry=0x5555557f9598)
    at /home/darpaek/gemrb/gemrb/core/GUI/View.cpp:209
#7  0x00007ffff7e64d05 in GemRB::View::Draw (this=0x5555557f9598)
    at /home/darpaek/gemrb/gemrb/core/GUI/View.cpp:285
#8  0x00007ffff7e65135 in GemRB::View::DrawSubviews (
    this=this@entry=0x5555557f9470)
    at /home/darpaek/gemrb/gemrb/core/GUI/View.cpp:209
#9  0x00007ffff7e64d05 in GemRB::View::Draw (this=0x5555557f9470)
    at /home/darpaek/gemrb/gemrb/core/GUI/View.cpp:285
--Type <RET> for more, q to quit, c to continue without paging--
#10 0x00007ffff7e69a44 in GemRB::WindowManager::DrawWindows (
    this=0x5555559aa110)
    at /home/darpaek/gemrb/gemrb/core/GUI/WindowManager.cpp:566
#11 0x00007ffff7e6a785 in GemRB::WindowManager::DrawWindows (
    this=0x5555559aa110) at /usr/include/c++/9/bits/stl_deque.h:1384
#12 0x00007ffff7ebbae3 in GemRB::Interface::Main (this=0x55555556eb50)
    at /home/darpaek/gemrb/gemrb/core/Interface.cpp:782
#13 0x000055555555535b in main (argc=<optimized out>, argv=0x7fffffffe038)
    at /home/darpaek/gemrb/gemrb/GemRB.cpp:73
(gdb) 
```
No luck.  It loads full, I can hear the ambient sound for a moment and then it freezes.  Same for both a save and loading a new game.

![postfix](https://user-images.githubusercontent.com/6020153/129415820-d0c4dcd0-1ad0-43b3-82a2-3369f5eb85dc.png)

**Comment by bradallred** [comment]
one more time please and thanks

**Comment by Darpaek** [comment]
No, thank you.  Thank you both.  You've been dealing with me for days.  I really appreciate it.

Still getting a segmentation thing, but it's a different one, so that's progress.

```
Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.
0x00007ffff5e89799 in PyCallable_Check ()
   from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
(gdb) bt
#0  0x00007ffff5e89799 in PyCallable_Check ()
   from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#1  0x00007ffff61bd964 in GemRB_Window_SetAction (self=<optimized out>, 
    args=<optimized out>)
    at /home/darpaek/gemrb/gemrb/plugins/GUIScript/GUIScript.cpp:1796
#2  0x00007ffff5ed5687 in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#3  0x00007ffff5caaf48 in _PyEval_EvalFrameDefault ()
   from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#4  0x00007ffff5df7e3b in _PyEval_EvalCodeWithName ()
   from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#5  0x00007ffff5ed5114 in _PyFunction_Vectorcall ()
   from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#6  0x00007ffff5ca1d6d in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#7  0x00007ffff5ca3018 in _PyEval_EvalFrameDefault ()
   from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#8  0x00007ffff5df7e3b in _PyEval_EvalCodeWithName ()
   from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#9  0x00007ffff5ed5114 in _PyFunction_Vectorcall ()
   from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#10 0x00007ffff5ed7407 in _PyObject_FastCallDict ()
   from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#11 0x00007ffff61b6e78 in GemRB::GUIScript::RunFunction (this=<optimized out>, 
    moduleName=0x7ffff7f5aae2 "Console", functionName=0x7ffff7f585f0 "OnLoad", 
--Type <RET> for more, q to quit, c to continue without paging--
    pArgs=0x0, report_error=true)
    at /home/darpaek/gemrb/gemrb/plugins/GUIScript/GUIScript.cpp:13714
#12 0x00007ffff61b6f6d in GemRB::GUIScript::RunFunction (this=0x56c8a0, 
    moduleName=0x7ffff7f5aae2 "Console", functionName=0x7ffff7f585f0 "OnLoad", 
    report_error=true, intparam=<optimized out>)
    at /home/darpaek/gemrb/gemrb/plugins/GUIScript/GUIScript.cpp:13732
#13 0x00007ffff7eaf064 in GemRB::Interface::HandleFlags (this=0x41ab50)
    at /home/darpaek/gemrb/gemrb/core/Interface.cpp:497
#14 0x00007ffff7eb14f8 in GemRB::Interface::Main (this=0x41ab50)
    at /home/darpaek/gemrb/gemrb/core/Interface.cpp:767
#15 0x000000000040141c in main (argc=<optimized out>, argv=0x7fffffffe058)
    at /home/darpaek/gemrb/gemrb/GemRB.cpp:73
(gdb) 
```
![postpostfix](https://user-images.githubusercontent.com/6020153/129423256-51420539-8b48-4ce1-a2f4-0180bb449b60.png)

**Comment by bradallred** [comment]
closing this and opening a new issue
