### ISSUE TITLE
 BG2: Crash when trying to enter a house

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1436]
#### Bug description
Trying to enter one house in the docks district in BG2 crashes (?) or hangs the game. 

```
[ResourceManager]: Found 'ar0325HT.bmp' in 'chitin.key'.
gemrb: /home/laula/Games/gemrb/gemrb/plugins/AREImporter/AREImporter.cpp:217: GemRB::Holder<GemRB::Sprite2D> MakeTileProps(const ResRef&, bool): Assertion `propsize == searchmap->Frame.size && propsize == heightmap->Frame.size' failed.

Thread 1 "gemrb" hit Breakpoint 1, 0x00007ffff750774c in abort ()
   from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff750774c in abort () from /usr/lib/libc.so.6
#1  0x00007ffff7507747 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#2  0x00007ffff7516616 in __assert_fail () from /usr/lib/libc.so.6
#3  0x00007ffff5f11803 in MakeTileProps (wedref=..., day_or_night=true)
    at /home/laula/Games/gemrb/gemrb/plugins/AREImporter/AREImporter.cpp:217
#4  0x00007ffff5f12d47 in GemRB::AREImporter::GetMap (this=0x555560517070, resRef=0x55555aa5bb36 "ar0325", day_or_night=true)
    at /home/laula/Games/gemrb/gemrb/plugins/AREImporter/AREImporter.cpp:498
#5  0x00007ffff7d1c9b0 in GemRB::Game::LoadMap (this=0x55555675df30, resRef=..., loadscreen=false)
    at /home/laula/Games/gemrb/gemrb/core/Game.cpp:872
#6  0x00007ffff7d1bebf in GemRB::Game::GetMap (this=0x55555675df30, areaname=..., change=false)
    at /home/laula/Games/gemrb/gemrb/core/Game.cpp:702
#7  0x00007ffff7dbf324 in GemRB::Map::MoveToNewArea (this=0x55555a998110, area=..., entrance=0x55555aa5bb3f "Exit0300", direction=0, 
    EveryOne=5, actor=0x555556bb51f0) at /home/laula/Games/gemrb/gemrb/core/Map.cpp:384
#8  0x00007ffff7dbf993 in GemRB::Map::UseExit (this=0x55555a998110, actor=0x555556bb51f0, ip=0x55555aa5b8e0)
    at /home/laula/Games/gemrb/gemrb/core/Map.cpp:502
#9  0x00007ffff7dc01c0 in GemRB::Map::UpdateScripts (this=0x55555a998110) at /home/laula/Games/gemrb/gemrb/core/Map.cpp:725
#10 0x00007ffff7d1ecfc in GemRB::Game::UpdateScripts (this=0x55555675df30) at /home/laula/Games/gemrb/gemrb/core/Game.cpp:1504
#11 0x00007ffff7d8dfe1 in GemRB::Interface::GameLoop (this=0x555555570b20) at /home/laula/Games/gemrb/gemrb/core/Interface.cpp:2396
#12 0x00007ffff7d863db in GemRB::Interface::Main (this=0x555555570b20) at /home/laula/Games/gemrb/gemrb/core/Interface.cpp:778
#13 0x00005555555563b5 in main (argc=3, argv=0x7fffffffdcd8) at /home/laula/Games/gemrb/gemrb/GemRB.cpp:73
```

```
(gdb) f 3
#3  0x00007ffff5f11803 in MakeTileProps (wedref=..., day_or_night=true)
    at /home/laula/Games/gemrb/gemrb/plugins/AREImporter/AREImporter.cpp:217
217        assert(propsize == searchmap->Frame.size && propsize == heightmap->Frame.size);
(gdb) p searchmap->Frame.size
[ResourceManager]: Searching for 'am1600a2'...
$1 = {w = 52, h = 54}
(gdb) p heightmap->Frame.size
$2 = {w = 48, h = 54}
(gdb) p propsize
$3 = {w = 48, h = 54}
```

#### Steps to reproduce
1. Try to enter that house

#### Expected behavior
Add a clear and concise description of what you expected to happen.

#### Screenshots

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
can I get a screenshot or something so I can know which house?

this is interesting because I dont understand how things could be expected to work with a search map that is larger than expected.

**Comment by lynxlynxlynx** [comment]
It's ar0325 (visible in the trace).

**Comment by Laulajatar** [comment]
I went a couple of commits back to find one that still works, I can do a bisect later if that helps? 

![unknown](https://user-images.githubusercontent.com/68446748/129779589-3122a10b-46dc-4056-bbc4-746d3c8cdf7b.png)

**Comment by bradallred** [comment]
you dont need to bisect, the problem is already known: the search map is larger than expected

**Comment by bradallred** [comment]
It appears like the is a light map bug? possibly corrupted data? or a bug in our BMP importer?
this is what we read in
![image](https://user-images.githubusercontent.com/1126744/129784477-2c78afa8-4c45-4c0f-8fe2-8dba65bb48e1.png)

as you can see it is seemingly cropped

where the search map is not
![image](https://user-images.githubusercontent.com/1126744/129784620-b9924ffe-45cd-4b88-9850-b0c8808f7ea2.png)

since I cant extract the original BMPs for whatever reason can anyone confirm my findings?

**Comment by bradallred** [comment]
BTW if you see any more cases of this please list the AR # so we can compare
