### ISSUE TITLE
[feature] Customize AI Frame Rate

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#144]
BG, BG2, IWD, and IWD2 (not sure about PST) allows for advance option customization which one of the being is setting FPS.
In all four games the ini setting responsible for AI Frame Rate is **Maximum Frame Rate** 

AI Frame allows for change in game dynamics. IMO the game best work when set between 38-43. Game feels a lot smother than hardlocked 30.

Description from the BGConfig.exe

> AI Frame Rate controls the overall speed of the game.  Baldur's Gate II is designed to run with an AI Frame Rate at 30.  Increasing this option on a fast machine will increase the overall speed of the game.  Reducing this option on a slow machine may increase playability by reducing frame-rate slowdown.  WARNING: This option must be equal on all players' machines during a multiplayer game.

**Comment by lynxlynxlynx** [comment]
From another user's testing, I believe this also changes the display FPS (currently hardcoded to ~30 in the video driver). The ai frame rate is hardcoded as AI_UPDATE_TIME, which is definitely 15, so my guess would be it was set to half of that config value.

Maybe a script using [SmallWait](https://gibberlings3.github.io/iesdp/scripting/actions/bg2actions.htm#83) could be made for testing this in the original. One actor with a block that does SmallWait(1) DisplayMessage(...) repeated half the config value times, while another actor with just Wait(1) DisplayMessage(...), to signal a stop after 1 second. Both triggered at the same time, so first a hotkey needs to set a var ... it can get complicated fast.

**Comment by burner1024** [comment]
The other user is probably me.
I don't quite understand, what's needed to test?

There's actual frame rate - displayed fps, and there's `Maximum Frame Rate`, which is a cap on game fps, or "game speed". With CTRL-D, they are displayed:
![Captura de pantalla de 2020-02-13 01-49-13](https://user-images.githubusercontent.com/1279852/74368107-8b793180-4e05-11ea-906b-36f8b4119a12.png)
Game speed is capped by MFR, MFR itself is hard capped at 90, displayed FPS is capped by both game speed and monitor FPS limit:
![Captura de pantalla de 2020-02-13 02-18-30](https://user-images.githubusercontent.com/1279852/74369391-e2800600-4e07-11ea-8550-ed259f06f7ca.png).
![Captura de pantalla de 2020-02-13 02-21-08](https://user-images.githubusercontent.com/1279852/74369368-d8f69e00-4e07-11ea-9f20-f2af5d05b2bd.png)

I always run 60/90, and I'd probably even try 120 if that was possible. So I think this is a very important issue. In fact, it's a deal breaker, preventing me from even attempting a playtest. Bugs and glitches and crashes can be dealt with, but going back to original speed is not an option.

Anyway, from what I remember from the conversation, the issue is quite deeper than just hardcoded parameters. Presumably because the engine was only ever tested with one speed, playing with `AI_UPDATE_TIME` doesn't necessarily provide the desired result. Basically, both increasing _and_ decreasing it make the game slower, only in the first case it's _jumpy_ slow, and in the second it's _smoothy_ slow.
It might be an overall performance issue. (Granted, I'm running it on what could be considered a potato by today's standards, with integrated video. But classic engine works faster even over wine wrapper.)

**Comment by lynxlynxlynx** [comment]
AI speed can't fluctuate or it would make scripting unreliable, therefore MFR was surely only a cap for drawing.

We base everything on AI_UPDATE_TIME and the constants in the gametime tables:
gemrb/unhardcoded/*/gametime.2da

`SDLVideoDriver::SwapBuffers` would need to be changed to take MFR into account (now 33). And of course AI_UPDATE_TIME, but some testing would not hurt first. The one test I suggested was to see if its value is indeed just half of MFR.

**Comment by burner1024** [comment]
> AI speed can't fluctuate or it would make scripting unreliable, therefore MFR was surely only a cap for drawing.

"AI Frame Rate" is just a bad description for it in BGconfig.exe. It's not limited to AI. It's the whole of game process. Drawing, casting, walking - everything. Going from 30 to 60 is literally doubling game speed. (The only exception I can think of is sound/movie playback, because that wouldn't look/sound good).

**Comment by lynxlynxlynx** [comment]
I don't have "AI Frame Rate" in my configured bg2 ini, though I'm not sure if you were implying it's a separate setting. Don't worry about the name though, of course it's not just about some iescripts.

**Comment by burner1024** [comment]
> I don't have "AI Frame Rate" in my configured bg2 ini, though I'm not sure if you were implying it's a separate setting.

I was referring to this (MFR):
> Description from the BGConfig.exe
> 
> > AI Frame Rate controls the overall speed of the game.  Baldur's Gate II is designed to run with an AI Frame Rate at 30.  Increasing this option on a fast machine will increase the overall speed of the game...


But if
> Don't worry about the name though, of course it's not just about some iescripts.

then sorry, I don't understand what do you mean by

> AI speed can't fluctuate or it would make scripting unreliable, therefore MFR was surely only a cap for drawing.

Could you clarify?

**Comment by lynxlynxlynx** [comment]
Ok. So the exe and config only set MFR, right? And it defaults to 30, while AI_UPDATE_TIME is/defaults to 15. So it's natural to think that AI_UPDATE_TIME is not a constant, but MFR/2. On the other hand, the drawing fps can't be ensured to be constant, hence even the name of the variable has "maximum" in it.

**Comment by burner1024** [comment]
> Ok. So the exe and config only set MFR, right? And it defaults to 30, while AI_UPDATE_TIME is/defaults to 15. So it's natural to think that AI_UPDATE_TIME is not a constant, but MFR/2. On the other hand, the drawing fps can't be ensured to be constant, hence even the name of the variable has "maximum" in it.

I agree with everything you said, but I don't see how that can affect scripts.

What I'm saying is:
1. AI_UPDATE_TIME (or its equivalent in original) is constant, but in frames, not in seconds of real time. And given the 15/30 default relationship, I'm reasonably sure there's a tick every second frame.
2. Everything in game is tied to the actual frame rate. Increasing MFR to 60 is basically stuffing 2 seconds of game time into 1 second of real time. The same 60 frames are calculated and displayed, simply twice as fast.
3. That is assuming your graphics card handles 60 fps, of course. If it doesn't, frame rate drops and everything in game slows down. Including scripts, animations, etc. There's no way for a game object to even detect if it's being slowed down "in real time", because there's nothing to compare to. So this can't possibly affect scripts.

If it helps, I could record samples from vanilla on max (60/90) vs GemRB compiled with `AI_UPDATE_TIME 45` and no fps limit. The difference is quite obvious.

**Comment by lynxlynxlynx** [comment]
That's a good question, are the two synchronized and it had Roman timekeeping with time dilation. Not sure it matters in the end. This is something that could be tested the same smallwait/wait way in the original, together with something that would consistently degrade performance.

**Comment by burner1024** [comment]
There's no question in my mind, but I'll test and report.

**Comment by bradallred** [comment]
> assuming your graphics card handles 60 fps
No drawing in the master branch is hardware accelerated. Everything is rendered via software algorithms. Subviews branch with SDL2 is required for any hardware acceleration.

The video driver on the Subviews branch no longer has a hardcoded fps cap because videos are not always 30 fps so that is the first step done.

**Comment by burner1024** [comment]
So here are some test results.
Hotkey() didn't work for me for some reason, so I just set the var on game load. Dlg_bg2_* are logged with Tobex `Log Dialogue Bar=1`

- [dlg_bg2_mfr30.txt](https://github.com/gemrb/gemrb/files/4203812/dlg_bg2_mfr30.txt) standard MFR=30.
- [dlg_bg2_mfr90.txt](https://github.com/gemrb/gemrb/files/4203814/dlg_bg2_mfr90.txt) MFR=90
- [dlg_bg2_mfr90_actual_fps60.txt](https://github.com/gemrb/gemrb/files/4203815/dlg_bg2_mfr90_actual_fps60.txt) MFR=90, but fps dropped to ~60 with glxgears in parallel.
- [gemrb_log_grep_keldorn_jan.txt](https://github.com/gemrb/gemrb/files/4203816/gemrb_log_grep_keldorn_jan.txt) funny thing, display strings are not actually displayed on GemRB. I've no idea why. But I checked the log and it does _log_ displaying them, so I grepped for the lines. Version is 0.8.6-git, without no additional defines or changes.

As far as I can see, everything's pretty consistent on BG2: 15 smallwaits per 1 wait, with any MFR and/or actual frame rate.
GemRB's log looks stranger to me, Jan's lines are doubled, but maybe I don't understand something about it. (And about missing actual DisplayMessages).

TP2 attached: [gemrb_time_test.tp2.zip](https://github.com/gemrb/gemrb/files/4203855/gemrb_time_test.tp2.zip)

Samples:
- [BG2 MFR90](https://www.loom.com/share/6d48067959564a98b8554b5a113880cd). FPS fluctuates a little because of the recording. Also, there's a lag when a Cowled appears.
- [GemRB](https://www.loom.com/share/f7045d738ecf4eaa9bf88f519f545e6e) 0.8.6-git, no special configuration. (Unrelated to the issue at hand, but notice how casting sparks play once. In BG2, they play until the spell is actually launched)
- [GemRB](https://www.loom.com/share/bb2ea99b161d4e8f9d3d051b71ad4187) `AI_UPDATE_TIME 45`,  `-DNOFPSLIMIT=true`. It's even slower.
- GemRB subviews `AI_UPDATE_TIME 45`,  `-DNOFPSLIMIT=true`, SDL2 present.
  Failed to build with `cc1plus: error: -Werror=stringop-truncation: no option -Wstringop-truncation`, so added `-DDISABLE_WERROR=1`
  Failed to load properly:
![Captura de pantalla de 2020-02-14 18-06-33](https://user-images.githubusercontent.com/1279852/74525938-e79e9b80-4f54-11ea-8cda-4288284c19a7.png)
```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/user/games/gemrb/share/gemrb/GUIScripts/bg2/MessageWindow.py", line 103, in UpdateControlStatus
[Python/ERROR]:     GSFlags = GemRB.GetMessageWindowSize()
[Python/ERROR]: AttributeError: 'module' object has no attribute 'GetMessageWindowSize'
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/user/games/gemrb/share/gemrb/GUIScripts/GUIWORLD.py", line 73, in DialogStarted
[Python/ERROR]:     ContinueWindow = OpenDialogButton(9)
[Python/ERROR]:   File "/home/user/games/gemrb/share/gemrb/GUIScripts/GUIWORLD.py", line 48, in OpenDialogButton
[Python/ERROR]:     frame = MsgWin.GetFrame()
[Python/ERROR]: AttributeError: 'NoneType' object has no attribute 'GetFrame'
[DialogHandler/ERROR]: Dialog aborted???
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/user/games/gemrb/share/gemrb/GUIScripts/GUIWORLD.py", line 80, in DialogEnded
[Python/ERROR]:     ContinueWindow.Close ()
[Python/ERROR]: AttributeError: 'NoneType' object has no attribute 'Close'
[ResourceManager]: Found 'w_msha1.vvc' in 'chitin.key'.
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/user/games/gemrb/share/gemrb/GUIScripts/bg2/MessageWindow.py", line 103, in UpdateControlStatus
[Python/ERROR]:     GSFlags = GemRB.GetMessageWindowSize()
[Python/ERROR]: AttributeError: 'module' object has no attribute 'GetMessageWindowSize'
```

**Comment by lynxlynxlynx** [comment]
Crap, all the logs say 15/s. So it's indeed the length of a second that is changing. Thanks for the detailed data.

**Comment by bradallred** [comment]
@burner1024 regarding the python errors: you are using the wrong guiscripts. You can't use the scripts from master on another branch.

**Comment by burner1024** [comment]
> Crap, all the logs say 15/s. So it's indeed the length of a second that is changing. Thanks for the detailed data.

Coming to think about it, it's not that surprising. If game speed wouldn't be tied to actual frame rate, it would basically be client-server architecture, with "actual state" and "displayed state", like in online games. And online games have lag. And why have it, when you can just as well not have it, and save some CPU cycles on top.

> @burner1024 regarding the python errors: you are using the wrong guiscripts. You can't use the scripts from master on another branch.

I just did make clean, switched branch to subviews and built it again. I assumed the files would be overwritten.
Now I tried again, wiping the install dir beforehand. The result is that it's segfaults on launch.

I'm still not clear about the various oddities mentioned. Could you clarify? Should I open an issue about each one:
1. DisplayString from the attached tp2 not being actually displayed.
2. Strange string display order in GemRB log:
    ```
    [GameScript]: Displaying string on: keldorn
    [GameScript]: Displaying string on: keldorn
    [GameScript]: Displaying string on: jan
    [GameScript]: Displaying string on: keldorn
    [GameScript]: Displaying string on: jan
    [GameScript]: Displaying string on: keldorn
    [GameScript]: Displaying string on: keldorn
    ```
3. Subviews not building without `-DDISABLE_WERROR=1`
4. Segfault when launching subviews branch.

**Comment by cygarniczka** [comment]
> Crap, all the logs say 15/s. So it's indeed the length of a second that is changing. Thanks for the detailed data.

This could actually be related to:
https://github.com/gemrb/gemrb/issues/426#issuecomment-578428868
> BGGRAPHICS
> 
> Spams you annoyingly with day/night move clip. BGGRAPHICS seriously messes up time. You would need someone who has that mod installed because this issue needs to be break down on its own. Too many factors just to generalize what the root of the problem could be. Kelsey and Viconia issue should be linked to BGGRAPHIC

S because I had them respawn in Government District after day/night movie clip played.

**Comment by bradallred** [comment]
@burner1024 I'm not sure about the segfaulting or building without `DDISABLE_WERROR=1`. Would you mind opening a couple of issues for them?

**Comment by lynxlynxlynx** [comment]
The compile thing is just a gcc issue, since only newer ones support the required flag. So you'll have to "suffer" without -Werror until an update.

**Comment by burner1024** [comment]
Separate issues created, the crash turned out to be tied to a particular savegame, not subviews branch.
