### ISSUE TITLE
Can't load savegame & errors while building in latest version

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1446]
#### Bug description
On 6ff70cbd32589367835aadd35ccb5e6ead233d2a

When building, I'm getting lots of 
```
In file included from /home/laula/Games/gemrb/gemrb/core/Map.h:27,
                 from /home/laula/Games/gemrb/gemrb/core/Animation.cpp:25:
/home/laula/Games/gemrb/gemrb/core/Bitmap.h: In constructor ‘GemRB::Bitmap::Bitmap(const GemRB::Size&, uint8_t)’:
/home/laula/Games/gemrb/gemrb/core/Bitmap.h:57:28: warning: unused parameter ‘s’ [-Wunused-parameter]
   57 |         Bitmap(const Size& s, uint8_t pattern)
      |                ~~~~~~~~~~~~^
```

If I disable warnings with `-DDISABLE_WERROR=1` it builds, but I can't load a save, not in BG1 and not in BG2. Not sure if related. I got two different crashes, one was: 

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Thread 1 "gemrb" hit Breakpoint 1, 0x00007ffff750674c in abort () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff750674c in abort () from /usr/lib/libc.so.6
#1  0x00007ffff78a6802 in __gnu_cxx::__verbose_terminate_handler ()
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#2  0x00007ffff78b2c8a in __cxxabiv1::__terminate (handler=<optimized out>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#3  0x00007ffff78b1c3a in __cxa_call_terminate (ue_header=0x55555926e040)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_call.cc:54
#4  0x00007ffff78b23bb in __cxxabiv1::__gxx_personality_v0 (version=<optimized out>, actions=6, 
    exception_class=5138137972254386944, ue_header=0x55555926e040, context=<optimized out>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_personality.cc:685
#5  0x00007ffff76bcf44 in _Unwind_RaiseException_Phase2 (exc=0x55555926e040, context=0x7fffffffc840, 
    frames_p=0x7fffffffc930) at /build/gcc/src/gcc/libgcc/unwind.inc:64
#6  0x00007ffff76bd5e2 in _Unwind_RaiseException (exc=0x55555926e040)
    at /build/gcc/src/gcc/libgcc/unwind.inc:136
#7  0x00007ffff78b2f7f in __cxxabiv1::__cxa_throw (obj=<optimized out>, 
    tinfo=0x7ffff7a13e78 <typeinfo for std::bad_alloc>, 
    dest=0x7ffff78b1200 <std::bad_alloc::~bad_alloc()>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:90
#8  0x00007ffff78a63d0 in operator new (sz=<optimized out>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/new_op.cc:54
#9  0x00007ffff7dccc6a in GemRB::Bitmap::Bitmap (this=0x555559282ba0, size=...)
    at /home/laula/Games/gemrb/gemrb/core/Bitmap.h:54
#10 0x00007ffff7dccca4 in GemRB::Bitmap::Bitmap (this=0x555559282ba0, s=..., pattern=0 '\000')
    at /home/laula/Games/gemrb/gemrb/core/Bitmap.h:58
#11 0x00007ffff7dbe014 in GemRB::Map::Map (this=0x555559282930, tm=0x555557e6f970, props=..., sm=...)
    at /home/laula/Games/gemrb/gemrb/core/Map.cpp:406
#12 0x00007ffff5d5ddb0 in GemRB::AREImporter::GetMap (this=0x555555e2ec80, 
    resRef=0x5555561ce8f4 "ar1700", day_or_night=true)
    at /home/laula/Games/gemrb/gemrb/plugins/AREImporter/AREImporter.cpp:509
#13 0x00007ffff7d1bc88 in GemRB::Game::LoadMap (this=0x5555561865f0, resRef=..., loadscreen=true)
    at /home/laula/Games/gemrb/gemrb/core/Game.cpp:872
#14 0x00007ffff7d1b197 in GemRB::Game::GetMap (this=0x5555561865f0, areaname=..., change=true)
    at /home/laula/Games/gemrb/gemrb/core/Game.cpp:702
#15 0x00007ffff7ccda46 in GemRB::GameControl::ChangeMap (this=0x555555f784b0, pc=0x5555561ce660, 
    forced=true) at /home/laula/Games/gemrb/gemrb/core/GUI/GameControl.cpp:2582
#16 0x00007ffff7d842c3 in GemRB::Interface::HandleFlags (this=0x55555556fb20)
    at /home/laula/Games/gemrb/gemrb/core/Interface.cpp:508
#17 0x00007ffff7d85634 in GemRB::Interface::Main (this=0x55555556fb20)
    at /home/laula/Games/gemrb/gemrb/core/Interface.cpp:767
#18 0x00005555555553b5 in main (argc=3, argv=0x7fffffffdcb8)
    at /home/laula/Games/gemrb/gemrb/GemRB.cpp:73
```

on a different save it was 

``` 
Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.
GemRB::Bitmap::BitProxy::operator= (this=0x7fffffffd820, set=true)
    at /home/laula/Games/gemrb/gemrb/core/Bitmap.h:42
42					byte |= (1 << bit);
(gdb) bt
#0  GemRB::Bitmap::BitProxy::operator= (this=0x7fffffffd820, set=true)
    at /home/laula/Games/gemrb/gemrb/core/Bitmap.h:42
#1  0x00007ffff7dca33e in GemRB::Map::ExploreTile (this=0x555559ee2fe0, p=...)
    at /home/laula/Games/gemrb/gemrb/core/Map.cpp:3454
#2  0x00007ffff7dca4e3 in GemRB::Map::ExploreMapChunk (this=0x555559ee2fe0, Pos=..., range=30, los=1)
    at /home/laula/Games/gemrb/gemrb/core/Map.cpp:3492
#3  0x00007ffff7dca607 in GemRB::Map::UpdateFog (this=0x555559ee2fe0)
    at /home/laula/Games/gemrb/gemrb/core/Map.cpp:3509
#4  0x00007ffff7d787bb in GemRB::GlobalTimer::Update (this=0x55555556fec8)
    at /home/laula/Games/gemrb/gemrb/core/GlobalTimer.cpp:166
#5  0x00007ffff7d8f819 in GemRB::Interface::GSUpdate (this=0x55555556fb20, update_scripts=true)
    at /home/laula/Games/gemrb/gemrb/core/Interface.cpp:2934
#6  0x00007ffff7d8d22e in GemRB::Interface::GameLoop (this=0x55555556fb20)
    at /home/laula/Games/gemrb/gemrb/core/Interface.cpp:2387
#7  0x00007ffff7d856b3 in GemRB::Interface::Main (this=0x55555556fb20)
    at /home/laula/Games/gemrb/gemrb/core/Interface.cpp:778
#8  0x00005555555553b5 in main (argc=3, argv=0x7fffffffdcb8)
    at /home/laula/Games/gemrb/gemrb/GemRB.cpp:73
```

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by Laulajatar** [comment]
You're fast... thank you! :D
