### ISSUE TITLE
 [iwd1] Level up error (python error & skills)

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1494]
#### Bug description
At level up, there are some python errors 

```[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/LevelUp.py", line 280, in OpenLevelUpWindow
[Python/ERROR]:     LUProfsSelection.SetupProfsWindow (pc, LUProfsSelection.LUPROFS_TYPE_LEVELUP, LevelUpWindow, RedrawSkills, Level1, Level, 0, False, 0)
[Python/ERROR]:   File "/home/elvire/gemrb/gemrb/build/../gemrb/GUIScripts/LUProfsSelection.py", line 320, in SetupProfsWindow
[Python/ERROR]:     if(ProfsScrollBar):
[Python/ERROR]: UnboundLocalError: local variable 'ProfsScrollBar' referenced before assignment
```

and skills values are not correct.

this part seems ok in BG2.

If needed, a save to reproduce
[000000086-levelup bug.zip](https://github.com/gemrb/gemrb/files/7371213/000000086-levelup.bug.zip)

#### Screenshots
![levelup](https://user-images.githubusercontent.com/55502325/137856118-b5b6eefb-c483-495d-b8d7-352570427846.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by FrElvire** [comment]
There are some changes like no 'other' values in skills but you can't levelup character. 'Accept' is greyed with no point to assign : 

![brad_lvlup](https://user-images.githubusercontent.com/55502325/141057868-45ad1778-2b4c-4542-87fd-d6f508638de3.png)
