### ISSUE TITLE
[BG1] Python GUI exceptions with polish language version

### ISSUE THREAD

**Issue by Isso4820** [gemrb/gemrb#1499]
I'm running GemRB on Linux (current master compiled locally - I've commented out assertions to bypass recent GCC issues #1498) using polish language version of the Baldurs Gate: TotSC (installed from six CDs with `wine`). I've added `Encoding=polish` in the config and I can see it loaded:
```
[ResourceManager]: Found 'polish.ini' in 'GemRB Unhardcoded data'.
[Core]: Loading encoding definition for polish: '/usr/local/share/gemrb/unhardcoded/bg1/polish.ini'
[INIImporter/ERROR]: Bad Line in file: polish.ini, Section: [charset], Entry: '# Characters left from the original encoding'
[INIImporter/ERROR]: Bad Line in file: polish.ini, Section: [charset], Entry: '# Polish characters'
```
After loading a save I see following exception:

```python
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/GUICommonWindows.py", line 602, in UpdateActionsWindow
[Python/ERROR]:     UpdateClock ()
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/Clock.py", line 66, in UpdateClock
[Python/ERROR]:     Clock.SetTooltip (GemRB.GetString (16041)) # refetch the string, since the tokens changed
[Python/ERROR]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf2 in position 4: invalid continuation byte
```
And as a result GUI is incomplete

![baldur0](https://user-images.githubusercontent.com/93745507/140434700-4a3515ca-a218-4cac-8a18-cedc13d740e0.png)

Similarly, entering the inventory results with a different exception:

```python
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/MetaClasses.py", line 59, in handler
[Python/ERROR]:     return f(*args, **kwargs)
[Python/ERROR]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 14: invalid continuation byte
[Python/ERROR]: 
During handling of the above exception, another exception occurred:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/bg1/GUIINV.py", line 42, in <lambda>
[Python/ERROR]:     ScrollBar.SetEvent (IE_GUI_SCROLLBAR_ON_CHANGE, lambda: RefreshInventoryWindow(Window))
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/bg1/GUIINV.py", line 234, in RefreshInventoryWindow
[Python/ERROR]:     ClassTitle = GUICommon.GetActorClassTitle (pc)
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/GUICommon.py", line 313, in GetActorClassTitle
[Python/ERROR]:     ClassTitle = CommonTables.Classes.GetValue (ClassName, "CAP_REF", GTV_REF)
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/MetaClasses.py", line 61, in handler
[Python/ERROR]:     raise type(e)(str(e) + "\nMethod Docs:\n" + str(f.__doc__))
[Python/ERROR]: TypeError: function takes exactly 5 arguments (1 given)
[ResourceManager]: Searching for 'CEMF2INV'...
[ResourceManager/WARNING]: Couldn't find 'CEMF2INV'... Tried CEMF2INV.plt 
[ResourceManager]: Searching for 'WPMSSINV'...
[ResourceManager/WARNING]: Couldn't find 'WPMSSINV'... Tried WPMSSINV.plt 
[ResourceManager]: Searching for 'WPMH4INV'...
[ResourceManager/WARNING]: Couldn't find 'WPMH4INV'... Tried WPMH4INV.plt 
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/MetaClasses.py", line 59, in handler
[Python/ERROR]:     return f(*args, **kwargs)
[Python/ERROR]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 14: invalid continuation byte
[Python/ERROR]: 
During handling of the above exception, another exception occurred:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/GUICommonWindows.py", line 1362, in ret
[Python/ERROR]:     selectionHandler(window)
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/bg1/GUIINV.py", line 141, in UpdateInventoryWindow
[Python/ERROR]:     RefreshInventoryWindow (Window)
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/bg1/GUIINV.py", line 234, in RefreshInventoryWindow
[Python/ERROR]:     ClassTitle = GUICommon.GetActorClassTitle (pc)
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/GUICommon.py", line 313, in GetActorClassTitle
[Python/ERROR]:     ClassTitle = CommonTables.Classes.GetValue (ClassName, "CAP_REF", GTV_REF)
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/MetaClasses.py", line 61, in handler
[Python/ERROR]:     raise type(e)(str(e) + "\nMethod Docs:\n" + str(f.__doc__))
[Python/ERROR]: TypeError: function takes exactly 5 arguments (1 given)
```

![baldur](https://user-images.githubusercontent.com/93745507/140435075-79c52795-6500-4730-8544-4f99a410ac1f.png)

It looks like there are encoding issues, perhaps a result of migration to Python 3 (#101)...? I haven't got this problem with `gemrb-linux-v0.9.0.AppImage` (there were some issues with transparency though, and I was advised on the Discord channel to use a recent build).

**Comment by bradallred** [comment]
yeah, unfortunately its gonna continue like whack-a-mole unless/until we convert all strings to UTF-16. Its a lot of really old C style code that reads like an IDA pro decompilation.

The GUI elements already convert strings via `StringFromCString` so we are kinda halfway there.
