### ISSUE TITLE
BG2: Can't remove selected party member 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1505]
#### Bug description
When trying to reform the party or a new member ask to come to the party I can't selected the one I want. Only the last one is selected and can't be changed.

#### Steps to reproduce
1. With a party try to reform it
2. Select anyone that is not the last
3. See error

#### Expected behavior
Can select anyone.

#### Screenshots

https://user-images.githubusercontent.com/1820598/146706094-1de2a18c-829f-48b4-ba44-0d010123ef88.mp4

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [X] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
it is still broken, the selection works now, but remove from party will still fail for a reason I haven't looked into

**Comment by rsantellan** [comment]
Is worst, know I lost the portraits on the bottom.

![image](https://user-images.githubusercontent.com/1820598/146865691-35be8150-f6da-4fc1-9690-cc6d4c6d0440.png)

**Comment by bradallred** [comment]
@rsantellan I can't reproduce that. If its still a problem open a new issue with reproduction steps and relevant console errors.

**Comment by rsantellan** [comment]
I have this errors.

```
[ResourceManager]: Found 'GUIREC.chu' in 'Override'.
[ResourceManager]: Searching for 'guirecbg'...
[ResourceManager]: Found 'guirecbg.mos' in 'chitin.key'.
[ResourceManager]: Found 'newbutt.bam' in 'chitin.key'.
[ResourceManager]: Found 'bigbutt.bam' in 'chitin.key'.
[ResourceManager]: Found 'magesch.2da' in 'GemRB Unhardcoded data'.
[ResourceManager]: Found 'guigenc6.bam' in 'chitin.key'.
[Python]:       Dual classed
[ResourceManager]: Found 'statdesc.2da' in 'Override'.
[ResourceManager]: Found 'reptxt.2da' in 'chitin.key'.
[Python]:       Dual classed
[Python]: pause state False
[ResourceManager]: Found 'GUIW10.chu' in 'chitin.key'.
[ResourceManager]: Searching for 'guwpkpc0'...
[ResourceManager]: Found 'guwpkpc0.mos' in 'chitin.key'.
[ResourceManager]: Found 'guiwsmb.bam' in 'chitin.key'.
[Python/ERROR]: TypeError: an integer is required (got type NoneType)
[Python/ERROR]: 
The above exception was the direct cause of the following exception:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/rodrigo/games/BaldurGate2/gemrb-myfork-git/gemrb/GUIScripts/MetaClasses.py", line 59, in handler
[Python/ERROR]:     return f(*args, **kwargs)
[Python/ERROR]: SystemError: <built-in function Control_SetVarAssoc> returned a result with an error set
[Python/ERROR]: 
During handling of the above exception, another exception occurred:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/rodrigo/games/BaldurGate2/gemrb-myfork-git/gemrb/GUIScripts/GUIREC.py", line 232, in OpenRecReformPartyWindow
[Python/ERROR]:     GUIWORLD.OpenReformPartyWindow()
[Python/ERROR]:   File "/home/rodrigo/games/BaldurGate2/gemrb-myfork-git/gemrb/GUIScripts/GUIWORLD.py", line 240, in OpenReformPartyWindow
[Python/ERROR]:     Button.SetVarAssoc ("Selected", None)
[Python/ERROR]:   File "/home/rodrigo/games/BaldurGate2/gemrb-myfork-git/gemrb/GUIScripts/MetaClasses.py", line 61, in handler
[Python/ERROR]:     raise type(e)(str(e) + "\nMethod Docs:\n" + str(f.__doc__))
[Python/ERROR]: SystemError: <built-in function Control_SetVarAssoc> returned a result with an error set
Method Docs:
===== Control_SetVarAssoc =====

**Prototype:** GemRB.SetVarAssoc (WindowIndex, ControlIndex, VariableName, LongValue)

**Metaclass Prototype:** SetVarAssoc (VariableName, LongValue)

**Description:** It associates a variable name and an optionally bounded 
value with a control. 
The control uses this associated value differently, depending on the 
control. See more about this in 'data_exchange'.

**Parameters:**
  * WindowIndex, ControlIndex  - the control's reference
  * Variablename - string, a Global Dictionary Name associated with the control
  * LongValue - numeric, a value associated with the control
  * min - numeric, minimum range value (optional)
  * max - numeric, maximum range value (optional)

**Return value:** N/A

**Special:** If the 'DialogChoose' variable was set to -1 or 0 during a dialog session, it will terminate (-1) or pick the first available option (0) from the dialog automatically. (0 is used for 'continue', -1 is used for 'end dialogue').

**See also:** [[guiscript:Button_SetFlags]], [[guiscript:SetVar]], [[guiscript:GetVar]], [[guiscript:data_exchange]], [[guiscript:accessing_gui_controls]]
[GameScript]: Displaying string on: jan
[ResourceManager]: Searching for 'janjan18'...
[ResourceManager]: Found 'janjan18.wav' in 'chitin.key'.
[ResourceManager]: Found 'interact.2da' in 'chitin.key'.
[GameScript]: Displaying string on: valygar
[ResourceManager]: Searching for 'valyga18'...
[ResourceManager]: Found 'valyga18.wav' in 'chitin.key'.
[GameScript]: Displaying string on: jaheira
[ResourceManager]: Searching for 'jaheir18'...
[ResourceManager]: Found 'jaheir18.wav' in 'chitin.key'.
[ResourceManager]: Searching for 'gwcontb0'...
[ResourceManager]: Found 'gwcontb0.mos' in 'chitin.key'.
[ResourceManager]: Searching for 'gam_03'...
[ResourceManager]: Found 'gam_03.wav' in 'chitin.key'.
[ResourceManager]: Searching for 'ARM_02d'...
[ResourceManager]: Found 'ARM_02d.wav' in 'chitin.key'.
[ResourceManager]: Found 'CHMB2g12.bam' in 'chitin.key'.
[ResourceManager]: Found 'pdialog.2da' in 'Override'.
[ResourceManager]: Found 'ea.ids' in 'chitin.key'.
[ResourceManager]: Searching for 'gam_04'...
[ResourceManager]: Found 'gam_04.wav' in 'chitin.key'.
[ResourceManager]: Searching for 'ARM_02c'...
[ResourceManager]: Found 'ARM_02c.wav' in 'chitin.key'.
[ResourceManager]: Found 'valygarp.dlg' in 'Override'.
[ResourceManager]: Found 'CHMB2g18.bam' in 'chitin.key'.
[ResourceManager]: Found 'CDMW2g1.bam' in 'chitin.key'.
[ResourceManager]: Searching for 'guwbtp10'...
[ResourceManager]: Found 'guwbtp10.mos' in 'Cache'.
[ResourceManager]: Searching for 'valyga87'...
[ResourceManager]: Found 'valyga87.wav' in 'chitin.key'.
[ResourceManager]: Searching for 'guwbtp30'...
[ResourceManager]: Found 'guwbtp30.mos' in 'Cache'.
[ResourceManager]: Found 'CLABRN03.2da' in 'Override'.
[ResourceManager]: Found 'SPCL311.spl' in 'Override'.
[ResourceManager]: Searching for 'guwbtp20'...
[ResourceManager]: Found 'guwbtp20.mos' in 'Cache'.
[GameScript]: Displaying string on: minsc
[ResourceManager]: Searching for 'minsc18'...
[ResourceManager]: Found 'minsc18.wav' in 'chitin.key'.
[ResourceManager]: Searching for 'ARM_04f'...
[ResourceManager]: Found 'ARM_04f.wav' in 'chitin.key'.
[ResourceManager]: Found 'CEFF4g12.bam' in 'chitin.key'.
[CharAnimations/DEBUG]: Truncating animation ref (wqMSCD4g1) to size.
[ResourceManager/ERROR]: Couldn't find 'wqMSCD4g.bam'.
[CharAnimations/DEBUG]: Truncating animation ref (wqMH5SCD4g1) to size.
[ResourceManager/ERROR]: Couldn't find 'wqMH5SCD.bam'.
[ResourceManager]: Searching for 'ARM_02a'...
[ResourceManager]: Found 'ARM_02a.wav' in 'chitin.key'.
[ResourceManager]: Searching for 'ARM_04h'...
[ResourceManager]: Found 'ARM_04h.wav' in 'chitin.key'.
[GameScript]: Displaying string on: aerie
[ResourceManager]: Searching for 'aerie18'...
[ResourceManager]: Found 'aerie18.wav' in 'chitin.key'.
```
This is how is shown

https://user-images.githubusercontent.com/1820598/146867228-7bec779c-0574-4d4f-b10a-33d3753a5a47.mp4

This is my save file.
[000000050-Hello mazzy.tar.gz](https://github.com/gemrb/gemrb/files/7749387/000000050-Hello.mazzy.tar.gz)

:

**Comment by bradallred** [comment]
If you can reproduce it with a _clean_ build, open a new issue please.

It doesn't look like you actually rebuilt the GUIScript plugin.

**Comment by rsantellan** [comment]
@bradallred I remove all the build folder and create again. Do I need to do this always ? Sometimes it takes the changes. The only problem with the fix is that it do not close the reform party window after removing someone.

![image](https://user-images.githubusercontent.com/1820598/146869599-e68e0400-ab5f-443d-8081-0990ef22508a.png)

I remove Jaheira but still there to choose it, if I start to clicking around the portrait will be gone. Is this another issue or the same ?

**Comment by bradallred** [comment]
The changes should have been picked up when you reran make, assuming that's how you build. There could be issues with the plugin path loading plugins from somewhere other than the newly built ones. That all depends on your config and how you run.

when in doubt `make clean && make` should be sufficient for any build issues. Plugin loading is something else, but we output the paths in the log so you should be able to determine if that is your issue.
