### ISSUE TITLE
[bg] segfault attempting to talk to Voice of the West 

### ISSUE THREAD

**Issue by TheCycoONE** [gemrb/gemrb#1598]
#### Bug description
```
./bg.sh: line 3:   739 Segmentation fault      (core dumped) ./gemrb/gemrb -c /home/stephen/baldurs_gate/bg.cfg
```

Stacktrace
```
(gdb) bt
#0  0x0000ffffa3727e0c in GemRB::DLGImporter::Import (this=0xaaaaff1fb3d0, str=0x0)
    at /home/stephen/gemrb/gemrb/plugins/DLGImporter/DLGImporter.cpp:32
#1  0x0000ffffa4ec2268 in GemRB::ImporterBase::Open (this=0xaaaaff1fb3d0, stream=0x0)
    at /home/stephen/gemrb/gemrb/core/Plugin.h:77
#2  0x0000ffffa4ec0214 in GemRB::DialogHandler::InitDialog (this=0xaaaafaaf7d30, spk=0xaaaafac44fa0, 
    tgt=0xaaaafe449660, dialogRef=..., si=4294967295) at /home/stephen/gemrb/gemrb/core/DialogHandler.cpp:108
#3  0x0000ffffa4fced04 in GemRB::BeginDialog (Sender=0xaaaafac44fa0, parameters=0xaaaaff1861c0, Flags=169)
    at /home/stephen/gemrb/gemrb/core/GameScript/GSUtils.cpp:1304
#4  0x0000ffffa4fb6cc4 in GemRB::GameScript::NIDSpecial1 (Sender=0xaaaafac44fa0, parameters=0xaaaaff1861c0)
    at /home/stephen/gemrb/gemrb/core/GameScript/Actions.cpp:2109
#5  0x0000ffffa4fddae0 in GemRB::GameScript::ExecuteAction (Sender=0xaaaafac44fa0, aC=0xaaaaff1861c0)
    at /home/stephen/gemrb/gemrb/core/GameScript/GameScript.cpp:2462
#6  0x0000ffffa5113ce0 in GemRB::Scriptable::ProcessActions (this=0xaaaafac44fa0)
    at /home/stephen/gemrb/gemrb/core/Scriptable/Scriptable.cpp:541
#7  0x0000ffffa5112e58 in GemRB::Scriptable::Update (this=0xaaaafac44fa0)
    at /home/stephen/gemrb/gemrb/core/Scriptable/Scriptable.cpp:259
#8  0x0000ffffa50515f8 in GemRB::Map::UpdateScripts (this=0xaaaafe2acef0)
    at /home/stephen/gemrb/gemrb/core/Map.cpp:733
#9  0x0000ffffa4f7d118 in GemRB::Game::UpdateScripts (this=0xaaaafac218f0)
    at /home/stephen/gemrb/gemrb/core/Game.cpp:1472
#10 0x0000ffffa5010df8 in GemRB::Interface::GameLoop (this=0xaaaaf9ad0760)
    at /home/stephen/gemrb/gemrb/core/Interface.cpp:2183
#11 0x0000ffffa500a04c in GemRB::Interface::Main (this=0xaaaaf9ad0760)
    at /home/stephen/gemrb/gemrb/core/Interface.cpp:642
#12 0x0000aaaaba9f4cf4 in main (argc=3, argv=0xffffe76c2d38) at /home/stephen/gemrb/gemrb/GemRB.cpp:66
```

I am playing Baldur's Gate (GOG) with the bgfixpack and hotfix.

#### Steps to reproduce
1. Load the attached [Save](https://github.com/gemrb/gemrb/files/8414414/888888890-voices.tar.gz)
2. Click on any voice of the west wind character
3. segfault

#### Expected behavior
Dialog?

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by TheCycoONE** [comment]
In case it's useful:
```
(gdb) frame 2
#2  0x0000ffffa4ec0214 in GemRB::DialogHandler::InitDialog (this=0xaaaafaaf7d30, spk=0xaaaafac44fa0, 
    tgt=0xaaaafe449660, dialogRef=..., si=4294967295) at /home/stephen/gemrb/gemrb/core/DialogHandler.cpp:108
108             dm->Open(gamedata->GetResource(dialogRef, IE_DLG_CLASS_ID));
(gdb) print dialogRef
$1 = (const GemRB::ResRef &) @0xffffe76c2788: {str = "voiwes\000\000"}
```

**Comment by lynxlynxlynx** [comment]
Thanks, looks like a regression from a smaller recent refactoring.
