### ISSUE TITLE
[bg] Attacking Jondalar during training results in reputation hit 

### ISSUE THREAD

**Issue by TheCycoONE** [gemrb/gemrb#1603]
#### Bug description
Training with Jondalar results in a reputation decrease when you hit him even though it's a training exercise and he attacks you first.
Playing Baldur's Gate with bgfixpack.

Game log: [game.log](https://github.com/gemrb/gemrb/files/8459006/reputation.log)
Save game: [888888892-train.tar.gz](https://github.com/gemrb/gemrb/files/8459008/888888892-train.tar.gz)

#### Steps to reproduce
1. Go to Jondalar (east Candlekeep)
2. Talk to Jondalar to begin training
3. When he and Erik attack you, attack back
4. Once you hit him a dialog comes up that you completed training. See that you took a reputation hit (as in the below screenshot)

#### Expected behavior
No reputation hit, this is a training exercise

#### Screenshots
![2022-04-10_08-04-1649595040](https://user-images.githubusercontent.com/823433/162619134-750cb38a-c54f-41a3-a187-85f92a6efdfc.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by TheCycoONE** [comment]
Stacktrace for Game::SetReputation

```
Thread 1 "gemrb" hit Breakpoint 1, 0x0000fffff7b4fe14 in GemRB::Game::SetReputation(unsigned int)@plt () from /home/stephen/gemrb/build/gemrb/core/libgemrb_core.so.0.9.0-git
(gdb) bt
#0  0x0000fffff7b4fe14 in GemRB::Game::SetReputation(unsigned int)@plt ()
   from /home/stephen/gemrb/build/gemrb/core/libgemrb_core.so.0.9.0-git
#1  0x0000fffff7dc72d8 in GemRB::Actor::Damage (this=0xaaaaaf5dfa60, damage=6, damagetype=16, hitter=
    0xaaaaabcb1040, modtype=0, critical=0, saveflags=0) at /home/stephen/gemrb/gemrb/core/Scriptable/Actor.cpp:4261
#2  0x0000fffff6215144 in fx_damage (target=0xaaaaaf5dfa60, fx=0xaaaaacd58850)
    at /home/stephen/gemrb/gemrb/plugins/FXOpcodes/FXOpcodes.cpp:1386
#3  0x0000fffff7bee354 in GemRB::EffectDesc::operator() (this=0xfffff7fb6008 <GemRB::Globals::Get()::globs+384>, 
    s=0xaaaaabcb1040, a=0xaaaaaf5dfa60, fx=0xaaaaacd58850) at /home/stephen/gemrb/gemrb/core/EffectQueue.h:160
#4  0x0000fffff7be9b18 in GemRB::EffectQueue::ApplyEffect (this=0xaaaaabfbff28, target=0xaaaaaf5dfa60, 
    fx=0xaaaaacd58850, first_apply=1, resistance=1) at /home/stephen/gemrb/gemrb/core/EffectQueue.cpp:1256
#5  0x0000fffff7be789c in GemRB::EffectQueue::AddEffect (this=0xaaaaabfbff28, fx=0xaaaaacd58850, 
    self=0xaaaaabcb1040, pretarget=0xaaaaaf5dfa60, dest=...) at /home/stephen/gemrb/gemrb/core/EffectQueue.cpp:614
#6  0x0000fffff7be7dc8 in GemRB::EffectQueue::AddAllEffects (this=0xaaaaabfbff28, target=0xaaaaaf5dfa60, 
    destination=...) at /home/stephen/gemrb/gemrb/core/EffectQueue.cpp:714
#7  0x0000fffff7d98bdc in GemRB::Projectile::Payload (this=0xaaaaabfbfd90)
    at /home/stephen/gemrb/gemrb/core/Projectile.cpp:558
#8  0x0000fffff7d98fac in GemRB::Projectile::ChangePhase (this=0xaaaaabfbfd90)
    at /home/stephen/gemrb/gemrb/core/Projectile.cpp:628
#9  0x0000fffff7d99a50 in GemRB::Projectile::DoStep (this=0xaaaaabfbfd90)
    at /home/stephen/gemrb/gemrb/core/Projectile.cpp:823
#10 0x0000fffff7d9b33c in GemRB::Projectile::Update (this=0xaaaaabfbfd90)
    at /home/stephen/gemrb/gemrb/core/Projectile.cpp:1248
#11 0x0000fffff7d53df0 in GemRB::Map::DrawMap (this=0xaaaaaf2a8710, viewport=..., dFlags=0)
    at /home/stephen/gemrb/gemrb/core/Map.cpp:1512
#12 0x0000fffff7c168f0 in GemRB::GameControl::DrawSelf (this=0xaaaaabb1b280, screen=...)
    at /home/stephen/gemrb/gemrb/core/GUI/GameControl.cpp:547
#13 0x0000fffff7c58f0c in GemRB::View::Draw (this=0xaaaaabb1b280) at /home/stephen/gemrb/gemrb/core/GUI/View.cpp:263
#14 0x0000fffff7c58974 in GemRB::View::DrawSubviews (this=0xaaaaaae39628)
    at /home/stephen/gemrb/gemrb/core/GUI/View.cpp:198
#15 0x0000fffff7c58f84 in GemRB::View::Draw (this=0xaaaaaae39628) at /home/stephen/gemrb/gemrb/core/GUI/View.cpp:274
```
