### ISSUE TITLE
 Can't select gender of my new character, GUI 'frozen'

### ISSUE THREAD

**Issue by Adrien2002** [gemrb/gemrb#1609]
#### Bug description
OS: FreeBSD 14.0-CURRENT amd64
WM: i3-wm

[GUIScript/ERROR]: Attribute Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/Adrien2002/Games/Baldur's Gate/GUIScripts/bg1/GUICG1.py", line 73, in NextPress
[Python/ERROR]:     GenderWindow.Close()
[Python/ERROR]:   File "/home/Adrien2002/Games/Baldur's Gate/GUIScripts/GUIClasses.py", line 238, in Close
[Python/ERROR]:     RemoveView(self, False)
[Python/ERROR]: AttributeError: Invalid view

#### Steps to reproduce
Create a new character, select the gender of your new character and press "Done"

#### Expected behavior
Continue in the creation of the character as expected

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [  ] 0.9.0
- [  ] 0.8.8

Video Driver (check as many as you know apply)
- [  ] SDL1.2
- [  ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Is this reproducible for you? It works here, but I'm not on BSD.

**Comment by Adrien2002** [comment]
Totally reproducible, I just can't validate the gender clicking on "Done".

**Comment by MarcelHB** [comment]
No luck reproducing as well.

**Comment by bradallred** [comment]
what version of Python?

Also, be sure that you aren't using GUIScripts from a previous build.

**Comment by Adrien2002** [comment]
I built the engine with these options :

```
cmake .. \
-DCMAKE_INSTALL_PREFIX=/home/$USER/Games/Baldur\'s\ Gate/Temp \
-DLIB_DIR=/home/$USER/Games/Baldur\'s\ Gate \
-DBIN_DIR=/home/$USER/Games/Baldur\'s\ Gate \
-DDATA_DIR=/home/$USER/Games/Baldur\'s\ Gate \
-DSYSCONF_DIR=/home/$USER/Games/Baldur\'s\ Gate \
-DUSE_LIBVLC=OFF \
-DSDL_BACKEND=SDL2 \
-DOPENGL_BACKEND=None \
-DOPENAL_INCLUDE_DIR=/usr/local/include/AL

make -j8
make install
```

**Comment by bradallred** [comment]
the only troubleshooting steps that come to mind at this time are:
1. try the latest Python and see if anything changes, even if its a different error
2. try using UBSAN+ASAN to see if maybe we are doing something silly with argument parsing like using a variable of the wrong size

seems like something has to be going wrong before calling `GemRB_RemoveView`

**Comment by Adrien2002** [comment]
Actually, I don't know how to proceed with the ASAN+UBSAN thing.

**Comment by lynxlynxlynx** [comment]
Pass -DSANITIZE=address for ASAN. But also, is this the first python error in the log? Is this a gog install?

**Comment by lynxlynxlynx** [comment]
Later errors don't matter, as things are already busted.

**Comment by bradallred** [comment]
> Pass -DSANITIZE=address for ASAN. But also, is this the first python error in the log? Is this a gog install?

`-DSANITIZE=undefined,address` should add both

**Comment by Adrien2002** [comment]
`-- Options:
--   LAYOUT: fhs
--   NOCOLOR: disabled
--   STATIC_LINK: disabled
--   INSOURCEBUILD: disabled
--   DISABLE_WERROR: disabled
--   WIN32_USE_STDIO: disabled
--   SDL_BACKEND: SDL2
--   PYTHON_VERSION: 3
--   OPENGL_BACKEND: None
**--   SANITIZE: undefined,address**`

`[ 51%] Linking CXX shared library libgemrb_core.so
[ 51%] Built target gemrb_core
[ 51%] Building CXX object gemrb/CMakeFiles/gemrb.dir/GemRB.cpp.o
[ 52%] Linking CXX executable gemrb
[ 52%] Built target gemrb
[ 52%] Building CXX object gemrb/plugins/2DAImporter/CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o
[ 52%] Linking CXX shared module ../2DAImporter.so
ld: error: undefined symbol: __asan_option_detect_stack_use_after_return
>>> referenced by 2DAImporter.cpp:32 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:32)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::p2DAImporter())
>>> referenced by 2DAImporter.cpp:40 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:40)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::~p2DAImporter())
>>> referenced by 2DAImporter.cpp:47 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:47)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::Open(GemRB::DataStream*))
>>> referenced 133 more times

ld: error: undefined symbol: __asan_stack_malloc_2
>>> referenced by 2DAImporter.cpp:32 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:32)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::p2DAImporter())
>>> referenced by format.h:2900 (/home/Adrien2002/Downloads/gemrb/gemrb/includes/fmt/format.h:2900)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > fmt::v8::to_string<char, 500ul>(fmt::v8::basic_memory_buffer<char, 500ul, std::__1::allocator<char> > const&))
>>> referenced by format.h:2092 (/home/Adrien2002/Downloads/gemrb/gemrb/includes/fmt/format.h:2092)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(fmt::v8::appender fmt::v8::detail::write<char, fmt::v8::appender, long long, 0>(fmt::v8::appender, long long))
>>> referenced 22 more times

ld: error: undefined symbol: __asan_memset
>>> referenced by vector:459 (/usr/include/c++/v1/vector:459)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::p2DAImporter())
>>> referenced by vector:459 (/usr/include/c++/v1/vector:459)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::p2DAImporter())
>>> referenced by vector:459 (/usr/include/c++/v1/vector:459)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::p2DAImporter())
>>> referenced 13 more times

ld: error: undefined symbol: __ubsan_vptr_type_cache
>>> referenced by 2DAImporter.cpp:33 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:33)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::p2DAImporter())
>>> referenced by 2DAImporter.cpp:34 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:34)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::p2DAImporter())
>>> referenced by 2DAImporter.cpp:35 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:35)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::p2DAImporter())
>>> referenced 370 more times

ld: error: undefined symbol: __ubsan_handle_dynamic_type_cache_miss
>>> referenced by 2DAImporter.cpp:33 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:33)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::p2DAImporter())
>>> referenced by 2DAImporter.cpp:34 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:34)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::p2DAImporter())
>>> referenced by 2DAImporter.cpp:35 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:35)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::p2DAImporter())
>>> referenced 448 more times

ld: error: undefined symbol: __asan_report_store8
>>> referenced by 2DAImporter.cpp:32 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:32)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::p2DAImporter())
>>> referenced by vector:460 (/usr/include/c++/v1/vector:460)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::p2DAImporter())
>>> referenced by vector:460 (/usr/include/c++/v1/vector:460)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::p2DAImporter())
>>> referenced 492 more times

ld: error: undefined symbol: __asan_handle_no_return
>>> referenced by 2DAImporter.cpp:0 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:0)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::p2DAImporter())
>>> referenced by vector:901 (/usr/include/c++/v1/vector:901)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(std::__1::vector<char*, std::__1::allocator<char*> >::__annotate_delete() const)
>>> referenced by vector:901 (/usr/include/c++/v1/vector:901)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(std::__1::vector<std::__1::vector<char*, std::__1::allocator<char*> >, std::__1::allocator<std::__1::vector<char*, std::__1::allocator<char*> > > >::__annotate_delete() const)
>>> referenced 137 more times

ld: error: undefined symbol: __asan_stack_malloc_1
>>> referenced by 2DAImporter.cpp:40 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:40)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::~p2DAImporter())
>>> referenced by vector:1605 (/usr/include/c++/v1/vector:1605)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(std::__1::vector<char*, std::__1::allocator<char*> >::reserve(unsigned long))
>>> referenced by vector:1605 (/usr/include/c++/v1/vector:1605)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(std::__1::vector<std::__1::vector<char*, std::__1::allocator<char*> >, std::__1::allocator<std::__1::vector<char*, std::__1::allocator<char*> > > >::reserve(unsigned long))
>>> referenced 46 more times

ld: error: undefined symbol: __ubsan_handle_type_mismatch_v1
>>> referenced by wrap_iter.h:92 (/usr/include/c++/v1/__iterator/wrap_iter.h:92)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::~p2DAImporter())
>>> referenced by vector:1572 (/usr/include/c++/v1/vector:1572)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::Open(GemRB::DataStream*))
>>> referenced by 2DAImporter.cpp:76 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:76)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::Open(GemRB::DataStream*))
>>> referenced 252 more times

ld: error: undefined symbol: __ubsan_handle_pointer_overflow
>>> referenced by wrap_iter.h:108 (/usr/include/c++/v1/__iterator/wrap_iter.h:108)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::~p2DAImporter())
>>> referenced by 2DAImporter.cpp:57 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:57)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::Open(GemRB::DataStream*))
>>> referenced by vector:1572 (/usr/include/c++/v1/vector:1572)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::Open(GemRB::DataStream*))
>>> referenced 395 more times

ld: error: undefined symbol: __asan_report_load8
>>> referenced by wrap_iter.h:92 (/usr/include/c++/v1/__iterator/wrap_iter.h:92)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::~p2DAImporter())
>>> referenced by 2DAImporter.cpp:42 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:42)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::~p2DAImporter())
>>> referenced by wrap_iter.h:108 (/usr/include/c++/v1/__iterator/wrap_iter.h:108)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::~p2DAImporter())
>>> referenced 927 more times

ld: error: undefined symbol: __asan_stack_malloc_3
>>> referenced by 2DAImporter.cpp:47 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:47)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::Open(GemRB::DataStream*))
>>> referenced by format.h:1277 (/home/Adrien2002/Downloads/gemrb/gemrb/includes/fmt/format.h:1277)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(fmt::v8::appender fmt::v8::detail::write_exponent<char, fmt::v8::appender>(int, fmt::v8::appender))
>>> referenced by format-inl.h:558 (/home/Adrien2002/Downloads/gemrb/gemrb/includes/fmt/format-inl.h:558)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(fmt::v8::detail::bigint::square())
>>> referenced 1 more times

ld: error: undefined symbol: __ubsan_handle_add_overflow
>>> referenced by 2DAImporter.cpp:107 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:107)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::Open(GemRB::DataStream*))
>>> referenced by format.h:947 (/home/Adrien2002/Downloads/gemrb/gemrb/includes/fmt/format.h:947)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(int fmt::v8::detail::count_digits_fallback<unsigned __int128>(unsigned __int128))
>>> referenced by format.h:0 (/home/Adrien2002/Downloads/gemrb/gemrb/includes/fmt/format.h:0)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(int fmt::v8::detail::count_digits_fallback<unsigned __int128>(unsigned __int128))
>>> referenced 64 more times

ld: error: undefined symbol: __asan_set_shadow_f5
>>> referenced by 2DAImporter.cpp:112 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:112)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::Open(GemRB::DataStream*))
>>> referenced by format.h:2989 (/home/Adrien2002/Downloads/gemrb/gemrb/includes/fmt/format.h:2989)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(void fmt::v8::detail::vformat_to<char>(fmt::v8::detail::buffer<char>&, fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<std::__1::conditional<std::is_same<fmt::v8::type_identity<char>::type, char>::value, fmt::v8::appender, std::__1::back_insert_iterator<fmt::v8::detail::buffer<fmt::v8::type_identity<char>::type> > >::type, fmt::v8::type_identity<char>::type> >, fmt::v8::detail::locale_ref))
>>> referenced by format.h:1627 (/home/Adrien2002/Downloads/gemrb/gemrb/includes/fmt/format.h:1627)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(fmt::v8::appender fmt::v8::detail::write_int_noinline<char, fmt::v8::appender, unsigned int>(fmt::v8::appender, fmt::v8::detail::write_int_arg<unsigned int>, fmt::v8::basic_format_specs<char> const&, fmt::v8::detail::locale_ref))
>>> referenced 36 more times

ld: error: undefined symbol: __asan_report_store1
>>> referenced by 2DAImporter.cpp:64 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:64)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::Open(GemRB::DataStream*))
>>> referenced by core.h:0 (/home/Adrien2002/Downloads/gemrb/gemrb/includes/fmt/core.h:0)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(void fmt::v8::detail::vformat_to<char>(fmt::v8::detail::buffer<char>&, fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<std::__1::conditional<std::is_same<fmt::v8::type_identity<char>::type, char>::value, fmt::v8::appender, std::__1::back_insert_iterator<fmt::v8::detail::buffer<fmt::v8::type_identity<char>::type> > >::type, fmt::v8::type_identity<char>::type> >, fmt::v8::detail::locale_ref))
>>> referenced by core.h:2092 (/home/Adrien2002/Downloads/gemrb/gemrb/includes/fmt/core.h:2092)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(void fmt::v8::detail::vformat_to<char>(fmt::v8::detail::buffer<char>&, fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<std::__1::conditional<std::is_same<fmt::v8::type_identity<char>::type, char>::value, fmt::v8::appender, std::__1::back_insert_iterator<fmt::v8::detail::buffer<fmt::v8::type_identity<char>::type> > >::type, fmt::v8::type_identity<char>::type> >, fmt::v8::detail::locale_ref))
>>> referenced 226 more times

ld: error: undefined symbol: __asan_report_load1
>>> referenced by 2DAImporter.cpp:56 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:56)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::Open(GemRB::DataStream*))
>>> referenced by 2DAImporter.cpp:81 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:81)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::Open(GemRB::DataStream*))
>>> referenced by 2DAImporter.h:77 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.h:77)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(GemRB::p2DAImporter::QueryField(unsigned long, unsigned long) const)
>>> referenced 222 more times

ld: error: undefined symbol: __asan_before_dynamic_init
>>> referenced by 2DAImporter.cpp:0 (/home/Adrien2002/Downloads/gemrb/gemrb/plugins/2DAImporter/2DAImporter.cpp:0)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(_GLOBAL__sub_I_2DAImporter.cpp)

ld: error: undefined symbol: __asan_after_dynamic_init
>>> referenced by CString.h:0 (/home/Adrien2002/Downloads/gemrb/gemrb/core/Strings/CString.h:0)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(_GLOBAL__sub_I_2DAImporter.cpp)

ld: error: undefined symbol: __asan_stack_malloc_5
>>> referenced by Logging.h:45 (/home/Adrien2002/Downloads/gemrb/gemrb/core/Logging/Logging.h:45)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(void GemRB::Log<char (&) [16]>(GemRB::log_level, char const*, char const*, char (&) [16]))
>>> referenced by format-inl.h:2227 (/home/Adrien2002/Downloads/gemrb/gemrb/includes/fmt/format-inl.h:2227)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(fmt::v8::detail::format_dragon(fmt::v8::detail::fp, bool, int, fmt::v8::detail::buffer<char>&, int&))
>>> referenced by core.h:2573 (/home/Adrien2002/Downloads/gemrb/gemrb/includes/fmt/core.h:2573)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(char const* fmt::v8::detail::parse_replacement_field<char, void fmt::v8::detail::vformat_to<char>(fmt::v8::detail::buffer<char>&, fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<std::__1::conditional<std::is_same<fmt::v8::type_identity<char>::type, char>::value, fmt::v8::appender, std::__1::back_insert_iterator<fmt::v8::detail::buffer<fmt::v8::type_identity<char>::type> > >::type, fmt::v8::type_identity<char>::type> >, fmt::v8::detail::locale_ref)::format_handler&>(char const*, char const*, void fmt::v8::detail::vformat_to<char>(fmt::v8::detail::buffer<char>&, fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<std::__1::conditional<std::is_same<fmt::v8::type_identity<char>::type, char>::value, fmt::v8::appender, std::__1::back_insert_iterator<fmt::v8::detail::buffer<fmt::v8::type_identity<char>::type> > >::type, fmt::v8::type_identity<char>::type> >, fmt::v8::detail::locale_ref)::format_handler&))

ld: error: undefined symbol: __asan_set_shadow_f8
>>> referenced by Logging.h:45 (/home/Adrien2002/Downloads/gemrb/gemrb/core/Logging/Logging.h:45)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(void GemRB::Log<char (&) [16]>(GemRB::log_level, char const*, char const*, char (&) [16]))
>>> referenced by format-inl.h:2590 (/home/Adrien2002/Downloads/gemrb/gemrb/includes/fmt/format-inl.h:2590)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(void GemRB::Log<char (&) [16]>(GemRB::log_level, char const*, char const*, char (&) [16]))
>>> referenced by format-inl.h:2590 (/home/Adrien2002/Downloads/gemrb/gemrb/includes/fmt/format-inl.h:2590)
>>>               CMakeFiles/2DAImporter.dir/2DAImporter.cpp.o:(void GemRB::Log<char (&) [16]>(GemRB::log_level, char const*, char const*, char (&) [16]))
>>> referenced 30 more times

ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[2]: stopped in /usr/home/Adrien2002/Downloads/gemrb/build
*** Error code 1

Stop.
make[1]: stopped in /usr/home/Adrien2002/Downloads/gemrb/build
*** Error code 1

Stop.
make: stopped in /usr/home/Adrien2002/Downloads/gemrb/build`

Is this error related to the code of the engine? Or is it FreeBSD related?

I've checked on our repository and I found the Makefile located in our 'Ports' package manager. No patch used, only this file to build the engine : https://cgit.freebsd.org/ports/plain/games/gemrb/Makefile

Except for the : 
```
USES=		cmake compiler:c11 gnome iconv localbase openal:al,alut \
		python:3.6+ sdl **shebangfix**
**SHEBANG_FILES=	admin/extend2da.py**
```
I don't see much difference between this Ports package and building it myself in my Downloads folder! That's why I wanted to give a try and being able to enjoy the best out of your work on GemRB myself.

**Comment by bradallred** [comment]
this is unrelated to this project. you are missing the sanitizer packages (or cmake doesnt locate them correctly)

**Comment by Adrien2002** [comment]
I get it, I'll try to locate it and use it then I'll come back to you

**Comment by bradallred** [comment]
actually, this isnt a cmake thing since we are relying on the compilers having support for the `-fsanitize` option, so yeah, missing the packages it seems.

**Comment by lynxlynxlynx** [comment]
Can you retry now? There were some undefined behaviour fixes since your report and that might help.

**Comment by lynxlynxlynx** [comment]
Closing due to inactivity and changed circumstances. Please reopen if you hit it again with the latest code.
