### ISSUE TITLE
Avoid callback errors on exit

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1668]
If you have a top window open and exit, the various handlers will try to run:
```python
[GUIScript/ERROR]: Runtime Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/kajak/games/gemrb/build/../gemrb/GUIScripts/bg2/GUIINV.py", line 111, in UpdateInventoryWindow
[Python/ERROR]:     pc = GemRB.GameGetSelectedPCSingle ()
[Python/ERROR]: RuntimeError: No game loaded!
[Python]: pause state None
[GUIScript/ERROR]: Runtime Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/kajak/games/gemrb/build/../gemrb/GUIScripts/GUICommonWindows.py", line 1383, in <lambda>
[Python/ERROR]:     window.SetAction(lambda: TopWindowClosed(window), ACTION_WINDOW_CLOSED)
[Python/ERROR]:   File "/home/kajak/games/gemrb/build/../gemrb/GUIScripts/GUICommonWindows.py", line 1334, in TopWindowClosed
[Python/ERROR]:     if not CommonWindow.IsGameGUIHidden() and GemRB.GetView ("ACTWIN") and not (GameCheck.IsIWD2() or GameCheck.IsPST()):
[Python/ERROR]:   File "/home/kajak/games/gemrb/build/../gemrb/GUIScripts/CommonWindow.py", line 28, in IsGameGUIHidden
[Python/ERROR]:     return GemRB.GetGUIFlags() & GS_HIDEGUI
[Python/ERROR]: RuntimeError: No game loaded!
```

Don't know when it started happening, but I suspect we could easily not try to run them if any/some of QF_KILL / QF_QUITGAME / QF_EXITGAME are set.

**Comment by bradallred** [comment]
this is interesting, because I thought we handled this:
https://github.com/gemrb/gemrb/blob/11b55676ec215f3960ef586c046e12cf3f1d9f84/gemrb/core/Interface.cpp#L438-L446

I would think that `CloseAllWindows` would invoke the close handler prior to `QuitGame`.

**Comment by bradallred** [comment]
Ah, so the error only happens when quitting via `AskAndExit`. This is because we end up calling `GemRB_Quit`, which calls `Interface::ExitGemRB`, which sets `QF_KILL`, instead of `QF_QUITGAME` or `QF_EXITGAME`... not sure why that is tho.

**Comment by bradallred** [comment]
I'm not sure what the difference between `QF_QUITGAME` and `QF_EXITGAME` is supposed to be, but this seems to work as I expect.

```diff
diff --git a/gemrb/core/Interface.cpp b/gemrb/core/Interface.cpp
index 732ebf85b..26852435e 100644
--- a/gemrb/core/Interface.cpp
+++ b/gemrb/core/Interface.cpp
@@ -451,7 +451,12 @@ void Interface::HandleFlags() noexcept
 		winmgr->GetGameWindow()->SetVisible(false);
 		//clear cutscenes; clear fade/screenshake effects
 		timer = GlobalTimer();
-		QuitFlag &= ~(QF_QUITGAME|QF_EXITGAME);
+		QuitFlag &= ~QF_QUITGAME;
+	}
+	
+	if (QuitFlag & QF_EXITGAME) {
+		QuitFlag = QF_KILL;
+		return;
 	}
 
 	if (QuitFlag&QF_LOADGAME) {
@@ -2198,17 +2203,10 @@ void Interface::AskAndExit()
 		guiscript->RunFunction("GUIOPT", "OpenQuitMsgWindow");
 		Log(MESSAGE, "Info", "Press ctrl-c (or close the window) again to quit GemRB.\n");
 	} else {
-		ExitGemRB();
+		QuitFlag |= QF_EXITGAME;
 	}
 }
 
-void Interface::ExitGemRB()
-{
-	const Console* console = GetControl<Console>("CONSOLE_CTL", 1);
-	if (console) console->SaveHistory();
-
-	QuitFlag |= QF_KILL;
-}
 /** Returns the variables dictionary */
 Variables* Interface::GetDictionary() const
 {
diff --git a/gemrb/core/Interface.h b/gemrb/core/Interface.h
index cd81a7f04..02a811dda 100644
--- a/gemrb/core/Interface.h
+++ b/gemrb/core/Interface.h
@@ -162,12 +162,12 @@ public:
 
 //quitflags
 #define QF_NORMAL        0
-#define QF_QUITGAME      1
-#define QF_EXITGAME      2
+#define QF_QUITGAME      1 // Exit current game
+#define QF_EXITGAME      2 // Exit current game and then set QF_KILL
 #define QF_CHANGESCRIPT  4
 #define QF_LOADGAME      8
 #define QF_ENTERGAME     16
-#define QF_KILL			32
+#define QF_KILL			32 // Exit GemRB
 
 //events that are called out of drawwindow
 //they wait until the condition is right
@@ -778,7 +778,6 @@ public:
 	/** returns true if the game is paused */
 	bool IsFreezed() const;
 	void AskAndExit();
-	void ExitGemRB(void);
 	/** CheatKey support */
 	inline void EnableCheatKeys(int Flag)
 	{
diff --git a/gemrb/plugins/GUIScript/GUIScript.cpp b/gemrb/plugins/GUIScript/GUIScript.cpp
index 5adcad086..ce098d4cb 100644
--- a/gemrb/plugins/GUIScript/GUIScript.cpp
+++ b/gemrb/plugins/GUIScript/GUIScript.cpp
@@ -4007,8 +4007,7 @@ PyDoc_STRVAR( GemRB_Quit__doc,
 
 static PyObject* GemRB_Quit(PyObject * /*self*/, PyObject * /*args*/)
 {
-	core->ExitGemRB();
-
+	core->QuitFlag |= QF_EXITGAME;
 	Py_RETURN_NONE;
 }
 
```

**Comment by bradallred** [comment]
Unrelated, but is there a reason we don't simply have the `Console` destructor call `Console::SaveHistory`?

**Comment by lynxlynxlynx** [comment]
It was before my time, but isn't the difference between the two that one is set when we want to shut down and one when just exit the current game back to the main menu? You added the _KILL later, that's why it can seem there's overlap. The patch looks fine.

Console dtor: yeah, it would better fit there.
