### ISSUE TITLE
BG2: Crash when Viekang gets struck by lightning

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1720]
#### Bug description

In Vyatri's Pub, Trademeet (AR2010), you will encounter Viekang. The dialog starts, you say something and after that something magical hits him.

And I get hit by a crash. Technically, this here is SIGTRAP/breakpoint-something magic on Windows, but continuing will terminate nontheless. Maybe I can later get another impression by Valgrind on Linux

```
Thread 1 received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffb056cf633 in ntdll!RtlIsZeroMemory () from C:\Windows\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ffb056cf633 in ntdll!RtlIsZeroMemory () from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00007ffb056d83f2 in ntdll!RtlpNtSetValueKey () from C:\Windows\SYSTEM32\ntdll.dll
#2  0x00007ffb056d86da in ntdll!RtlpNtSetValueKey () from C:\Windows\SYSTEM32\ntdll.dll
#3  0x00007ffb056de361 in ntdll!RtlpNtSetValueKey () from C:\Windows\SYSTEM32\ntdll.dll
#4  0x00007ffb056d8300 in ntdll!RtlpNtSetValueKey () from C:\Windows\SYSTEM32\ntdll.dll
#5  0x00007ffb055fd95f in ntdll!RtlAllocateHeap () from C:\Windows\SYSTEM32\ntdll.dll
#6  0x00007ffb055fb44d in ntdll!RtlAllocateHeap () from C:\Windows\SYSTEM32\ntdll.dll
#7  0x00007ffb056c8c38 in ntdll!RtlRegisterSecureMemoryCacheCallback () from C:\Windows\SYSTEM32\ntdll.dll
#8  0x00007ffb055fd255 in ntdll!RtlAllocateHeap () from C:\Windows\SYSTEM32\ntdll.dll
#9  0x00007ffb055fb44d in ntdll!RtlAllocateHeap () from C:\Windows\SYSTEM32\ntdll.dll
#10 0x00007ffb04bb9d40 in msvcrt!malloc () from C:\Windows\System32\msvcrt.dll
#11 0x00007ffaa367aa6c in ?? () from C:\MSYS2\mingw64\bin\libstdc++-6.dll
#12 0x00007ffa9a571e3a in GemRB::SDLVideoDriver::CreateSprite (this=0x1ee52a81a30, rgn=..., pixels=0x1ee66e589f0, fmt=...) at D:/Sources/gemrb/gemrb/plugins/SDLVideo/SDLVideo.cpp:248
#13 0x00007ffa7e10751e in GemRB::CreateLight (size=..., intensity=0 '\000') at D:/Sources/gemrb/gemrb/core/Light.cpp:79
#14 0x00007ffa7e1e405c in GemRB::ScriptedAnimation::UpdatePhase (this=0x1ee72270950) at D:/Sources/gemrb/gemrb/core/ScriptedAnimation.cpp:476
#15 0x00007ffa7e1e4731 in GemRB::ScriptedAnimation::UpdateDrawingState (this=0x1ee72270950, orientation=GemRB::NE) at D:/Sources/gemrb/gemrb/core/ScriptedAnimation.cpp:583
#16 0x00007ffa7e199025 in GemRB::Actor::UpdateDrawingState (this=0x1ee720f6380) at D:/Sources/gemrb/gemrb/core/Scriptable/Actor.cpp:7958
#17 0x00007ffa7e114ae1 in GemRB::Map::DrawMap (this=0x1ee7209da40, viewport=..., dFlags=0) at D:/Sources/gemrb/gemrb/core/Map.cpp:1464
#18 0x00007ffa7dfce66f in GemRB::GameControl::DrawSelf (this=0x1ee641e8d80, screen=...) at D:/Sources/gemrb/gemrb/core/GUI/GameControl.cpp:550
#19 0x00007ffa7e010570 in GemRB::View::Draw (this=0x1ee641e8d80) at D:/Sources/gemrb/gemrb/core/GUI/View.cpp:263
#20 0x00007ffa7e00ff20 in GemRB::View::DrawSubviews (this=0x1ee55ede820) at D:/Sources/gemrb/gemrb/core/GUI/View.cpp:198
#21 0x00007ffa7e01061a in GemRB::View::Draw (this=0x1ee55ede820) at D:/Sources/gemrb/gemrb/core/GUI/View.cpp:274
#22 0x00007ffa7e00ff20 in GemRB::View::DrawSubviews (this=0x1ee55ede700) at D:/Sources/gemrb/gemrb/core/GUI/View.cpp:198
#23 0x00007ffa7e01061a in GemRB::View::Draw (this=0x1ee55ede700) at D:/Sources/gemrb/gemrb/core/GUI/View.cpp:274
#24 0x00007ffa7e01f440 in GemRB::WindowManager::DrawWindows (this=0x1ee55fcdd00) at D:/Sources/gemrb/gemrb/core/GUI/WindowManager.cpp:577
#25 0x00007ffa7e0c35a8 in GemRB::Interface::Main (this=0x1ee52a47600) at D:/Sources/gemrb/gemrb/core/Interface.cpp:647
#26 0x00007ff7b8d816c2 in main (argc=3, argv=0x1ee52a444e0) at D:/Sources/gemrb/platforms/windows/GemRB.cpp:53
(gdb) c
Continuing.
gdb: unknown target exception 0xc0000374 at 0x7ffb056cf6a9
Thread 1 received signal ?, Unknown signal.
```

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Can reproduce:
```c
#0  __GI_abort () at ./stdlib/abort.c:49
#1  0x00007ffff74bc6f6 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff760eb8c "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#2  0x00007ffff74d3d7c in malloc_printerr (str=str@entry=0x7ffff760c711 "corrupted size vs. prev_size")
    at ./malloc/malloc.c:5664
#3  0x00007ffff74d4862 in unlink_chunk (p=p@entry=0x55556ba8fc60, av=0x7ffff764cc80 <main_arena>)
    at ./malloc/malloc.c:1629
#4  0x00007ffff74d76ab in _int_malloc (av=av@entry=0x7ffff764cc80 <main_arena>, bytes=bytes@entry=512)
    at ./malloc/malloc.c:4307
#5  0x00007ffff74d81b9 in __GI___libc_malloc (bytes=512) at ./malloc/malloc.c:3329
#6  0x00007ffff7729a0c in operator new(unsigned long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff7d635c4 in __gnu_cxx::new_allocator<std::shared_ptr<GemRB::Wall_Polygon> >::allocate (
    this=0x7fffffffcc68, __n=32) at /usr/include/c++/10/ext/new_allocator.h:121
#8  0x00007ffff7d6145f in std::allocator_traits<std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::allocate (__a=..., __n=32) at /usr/include/c++/10/bits/alloc_traits.h:460
#9  0x00007ffff7d5e17c in std::_Vector_base<std::shared_ptr<GemRB::Wall_Polygon>, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::_M_allocate (this=0x7fffffffcc68, __n=32) at /usr/include/c++/10/bits/stl_vector.h:346
#10 0x00007ffff7d5a23b in std::vector<std::shared_ptr<GemRB::Wall_Polygon>, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::_M_realloc_insert<std::shared_ptr<GemRB::Wall_Polygon> const&> (this=0x7fffffffcc68, 
    __position=<error reading variable: Cannot access memory at address 0xa9>)
    at /usr/include/c++/10/bits/vector.tcc:440
#11 0x00007ffff7d55f0e in std::vector<std::shared_ptr<GemRB::Wall_Polygon>, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::push_back (this=0x7fffffffcc68, 
    __x=std::shared_ptr<GemRB::Wall_Polygon> (use count 2, weak count 0) = {...})
    at /usr/include/c++/10/bits/stl_vector.h:1198
#12 0x00007ffff7d46318 in GemRB::Map::WallsIntersectingRegion (this=0x55556c81bee0, r=..., 
    includeDisabled=false, loc=0x55556ca0bebc) at /home/kajak/games/gemrb/gemrb/core/Map.cpp:1707
#13 0x00007ffff7d469d2 in GemRB::Map::SetDrawingStencilForScriptable (this=0x55556c81bee0, 
    scriptable=0x55556ca0bd60, vp=...) at /home/kajak/games/gemrb/gemrb/core/Map.cpp:1790
#14 0x00007ffff7d452c9 in GemRB::Map::DrawMap (this=0x55556c81bee0, viewport=..., dFlags=0)
    at /home/kajak/games/gemrb/gemrb/core/Map.cpp:1468
```
So not quite the same. But I also got a few crashes on yanking actors, those mostly in drawing.

Valgrind complains about the usual Font stuff. First potentially relevant thing (looks new as well) is too early:
```c
=330019== Conditional jump or move depends on uninitialised value(s)
==330019==    at 0x7183CF7: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.18.2)
==330019==    by 0x70355E3: GemRB::SDLSurfaceSprite2D::UpdateSurfacePalette() const (SDLSurfaceSprite2D.cpp:84)
==330019==    by 0x7035BA8: GemRB::SDLSurfaceSprite2D::Invalidate() const (SDLSurfaceSprite2D.cpp:199)
==330019==    by 0x70365D0: GemRB::SDLTextureSprite2D::Invalidate() const (SDLSurfaceSprite2D.cpp:331)
==330019==    by 0x70356F9: GemRB::SDLSurfaceSprite2D::UnlockSprite() const (SDLSurfaceSprite2D.cpp:109)
==330019==    by 0x806852C: GemRB::TISImporter::GetTile(int) (TISImporter.cpp:148)
==330019==    by 0x8067BB0: GemRB::TISImporter::GetTile(std::vector<unsigned short, std::allocator<unsigned short
> > const&, unsigned short*) (TISImporter.cpp:68)
==330019==    by 0x6FB71C8: GemRB::WEDImporter::AddOverlay(GemRB::TileMap*, GemRB::Overlay const*, bool) const (W
EDImporter.cpp:141)
==330019==    by 0x6FB74BA: GemRB::WEDImporter::GetTileMap(GemRB::TileMap*) const (WEDImporter.cpp:177)
==330019==    by 0x7E76680: GemRB::AREImporter::GetMap(GemRB::FixedSizeString<8ul, &strncasecmp> const&, bool) (A
REImporter.cpp:485)
==330019==    by 0x4BEDBC5: GemRB::Game::LoadMap(GemRB::FixedSizeString<8ul, &strncasecmp> const&, bool) (Game.cpp:847)
==330019==    by 0x4BED04E: GemRB::Game::GetMap(GemRB::FixedSizeString<8ul, &strncasecmp> const&, bool) (Game.cpp:685)
==330019==  Uninitialised value was created by a stack allocation
==330019==    at 0x7036E58: GemRB::PixelFormatForSurface(SDL_Surface*, GemRB::Holder<GemRB::Palette>)::{lambda()#1}::operator()() const (SDLPixelIterator.h:46)
==330019==
```

The invalid read happens here:
```c
==330019== Invalid read of size 32
==330019==    at 0x535C55D: __wmemcmp_avx2_movbe (memcmp-avx2-movbe.S:413)
==330019==    by 0x50D595D: std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::compare(wchar_t const*) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30)
==330019==    by 0x4BB799D: bool std::operator==<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, wchar_t const*) (basic_string.h:6199)
==330019==    by 0x4BB6DF1: GemRB::GemMarkupParser::ParseMarkupStringIntoContainer(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, GemRB::TextContainer&) (GemMarkup.cpp:88)
==330019==    by 0x4BA463A: GemRB::TextArea::AppendText(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >) (TextArea.cpp:462)
==330019==    by 0x4B36A2D: GemRB::DisplayMessage::DisplayMarkupString(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >) const (DisplayMessage.cpp:111)
==330019==    by 0x4B38040: GemRB::DisplayMessage::DisplayStringName(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, GemRB::Color const&, GemRB::Scriptable const*) const (DisplayMessage.cpp:312)
==330019==    by 0x4B379C2: GemRB::DisplayMessage::DisplayConstantStringName(unsigned long, GemRB::Color const&, GemRB::Scriptable const*) const (DisplayMessage.cpp:260)
==330019==    by 0x4B37A7D: GemRB::DisplayMessage::DisplayConstantStringName(unsigned long, GemRB::GUIColors, Gem
RB::Scriptable const*) const (DisplayMessage.cpp:267)
==330019==    by 0x4D3EC13: GemRB::pcf_xp(GemRB::Actor*, unsigned int, unsigned int) (Actor.cpp:1229)
==330019==    by 0x4D46DF9: GemRB::Actor::RefreshEffects(bool, std::array<unsigned int, 256ul> const&) (Actor.cpp:2789)
==330019==    by 0x4D46543: GemRB::Actor::AddEffects(GemRB::EffectQueue&&) (Actor.cpp:2690)
==330019==  Address 0x26564450 is 0 bytes inside a block of size 28 alloc'd
==330019==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==330019==    by 0x50D31BB: std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_mutate(unsigned long, unsigned long, wchar_t const*, unsigned long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30)
==330019==    by 0x50D3AA4: std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::operator+=(wchar_t) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30)
==330019==    by 0x4BB739A: GemRB::GemMarkupParser::ParseMarkupStringIntoContainer(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, GemRB::TextContainer&) (GemMarkup.cpp:181)
==330019==    by 0x4BA463A: GemRB::TextArea::AppendText(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >) (TextArea.cpp:462)
==330019==    by 0x4B36A2D: GemRB::DisplayMessage::DisplayMarkupString(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >) const (DisplayMessage.cpp:111)
==330019==    by 0x4B38040: GemRB::DisplayMessage::DisplayStringName(std::__cxx11::basic_string<wchar_t, std::cha
r_traits<wchar_t>, std::allocator<wchar_t> >, GemRB::Color const&, GemRB::Scriptable const*) const (DisplayMessage.cpp:312)
==330019==    by 0x4B379C2: GemRB::DisplayMessage::DisplayConstantStringName(unsigned long, GemRB::Color const&, GemRB::Scriptable const*) const (DisplayMessage.cpp:260)
==330019==    by 0x4B37A7D: GemRB::DisplayMessage::DisplayConstantStringName(unsigned long, GemRB::GUIColors, GemRB::Scriptable const*) const (DisplayMessage.cpp:267)
==330019==    by 0x4D3EC13: GemRB::pcf_xp(GemRB::Actor*, unsigned int, unsigned int) (Actor.cpp:1229)
==330019==    by 0x4D46DF9: GemRB::Actor::RefreshEffects(bool, std::array<unsigned int, 256ul> const&) (Actor.cpp:2789)
==330019==    by 0x4D46543: GemRB::Actor::AddEffects(GemRB::EffectQueue&&) (Actor.cpp:2690)
==330019==
```
And another one when pausing.

Then it crashes with a few identical writes:
```c
==330019== Invalid write of size 1
==330019==    at 0x4CC86B5: GemRB::CreateLight(GemRB::Size const&, unsigned char) (Light.cpp:70)
==330019==    by 0x4DA8A8A: GemRB::ScriptedAnimation::UpdatePhase() (ScriptedAnimation.cpp:476)
==330019==    by 0x4DA91A4: GemRB::ScriptedAnimation::UpdateDrawingState(GemRB::orient_t) (ScriptedAnimation.cpp:583)
==330019==    by 0x4D5D123: GemRB::Actor::UpdateDrawingState() (Actor.cpp:7952)
==330019==    by 0x4CD61F0: GemRB::Map::DrawMap(GemRB::Region const&, unsigned int) (Map.cpp:1464)
==330019==    by 0x4B87DAA: GemRB::GameControl::DrawSelf(GemRB::Region const&, GemRB::Region const&) (GameControl.cpp:550)
==330019==    by 0x4BCBA41: GemRB::View::Draw() (View.cpp:263)
==330019==    by 0x4BCB3B8: GemRB::View::DrawSubviews() (View.cpp:198)
==330019==    by 0x4BCBAFA: GemRB::View::Draw() (View.cpp:274)
==330019==    by 0x4BCB3B8: GemRB::View::DrawSubviews() (View.cpp:198)
==330019==    by 0x4BCBAFA: GemRB::View::Draw() (View.cpp:274)
==330019==    by 0x4BDB44A: GemRB::WindowManager::DrawWindows() const (WindowManager.cpp:577)
==330019==  Address 0x283cec3f is 15 bytes after a block of size 1,600 alloc'd
==330019==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==330019==    by 0x4CC8379: GemRB::CreateLight(GemRB::Size const&, unsigned char) (Light.cpp:48)
==330019==    by 0x4DA8A8A: GemRB::ScriptedAnimation::UpdatePhase() (ScriptedAnimation.cpp:476)
==330019==    by 0x4DA91A4: GemRB::ScriptedAnimation::UpdateDrawingState(GemRB::orient_t) (ScriptedAnimation.cpp:583)
==330019==    by 0x4D5D123: GemRB::Actor::UpdateDrawingState() (Actor.cpp:7952)
==330019==    by 0x4CD61F0: GemRB::Map::DrawMap(GemRB::Region const&, unsigned int) (Map.cpp:1464)
==330019==    by 0x4B87DAA: GemRB::GameControl::DrawSelf(GemRB::Region const&, GemRB::Region const&) (GameControl.cpp:550)
==330019==    by 0x4BCBA41: GemRB::View::Draw() (View.cpp:263)
==330019==    by 0x4BCB3B8: GemRB::View::DrawSubviews() (View.cpp:198)
==330019==    by 0x4BCBAFA: GemRB::View::Draw() (View.cpp:274)
==330019==    by 0x4BCB3B8: GemRB::View::DrawSubviews() (View.cpp:198)
==330019==    by 0x4BCBAFA: GemRB::View::Draw() (View.cpp:274)
```
