### ISSUE TITLE
[bug] Crashes with 'unnamed palette' errors in recent version

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#190]
**Description**
Upon entering areas with certain actors GemRB crashed with the following error:
`[GameData/FATAL]: Unnamed palette, it should be mdog_wa!`
Also crashed with mdog_wi and mber_something error. Opening areas in NearInfinity and removing the dogs in this case makes the areas load fine.

**GemRB version**: 0.85-git as of August 30th. My previous version was 0.85-git as of July 15th, this version does NOT have this error. Game installations BG2 and BGT.

**Steps to reproducer:**
1. Start / load a BG2 game
2. Go to the following areas: Athkatla Docks (AR0300) or the Slums (AR0400)
3. Game should crash immediately upon loading the area

**Comment by MarcelHB** [comment]
Can reproduce this:
```
(gdb) bt
#0  GemRB::GameData::FreePalette (this=0x533e40, pal=@0x12bd81b0: 0x109a6f60,
    name=name@entry=0x22f767 "mdog_wi")
    at ./gemrb/core/GameData.cpp:282
#1  0x0000000069e83d0b in GemRB::CharAnimations::SetupColors (
    this=0x12bd6980, type=<optimized out>)
    at ./gemrb/core/CharAnimations.cpp:428
#2  0x0000000069e8809d in GemRB::CharAnimations::GetAnimation (
    this=this@entry=0x12bd6980, Stance=Stance@entry=1 '\001',
    Orient=<optimized out>, Orient@entry=0 '\000')
    at ./gemrb/core/CharAnimations.cpp:1142
#3  0x0000000069f24080 in GemRB::Actor::UpdateAnimations (
    this=this@entry=0x12bd4b90)
    at ./gemrb/core/Scriptable/Actor.cpp:8197
#4  0x0000000069efecd8 in GemRB::Map::DrawMap (this=this@entry=0x11615360,
    screen=...) at ./gemrb/core/Map.cpp:1193
#5  0x0000000069e9d427 in GemRB::GameControl::DrawInternal (this=0xd820b30,
    screen=...)
    at ./gemrb/core/GUI/GameControl.cpp:506
#6  0x0000000069e96847 in GemRB::Control::Draw (this=this@entry=0xd820b30,
    x=<optimized out>, y=<optimized out>)
    at ./gemrb/core/GUI/Control.cpp:110
#7  0x0000000069eacd69 in GemRB::Window::DrawWindow (
    this=this@entry=0xb56cf20)
    at ./gemrb/core/GUI/Window.cpp:137
#8  0x0000000069eeb4f8 in GemRB::Interface::DrawWindows (
    this=this@entry=0x5324b0, allow_delete=allow_delete@entry=true)
    at ./gemrb/core/Interface.cpp:3097
#9  0x0000000069eec802 in GemRB::Interface::Main (this=0x5324b0)
    at ./gemrb/core/Interface.cpp:1002
#10 0x0000000000402bf8 in main (argc=3, argv=0x5129e0)
    at ./gemrb/GemRB.cpp:99
```

**Comment by lynxlynxlynx** [comment]
Thanks for the report @caillean7 and thanks for the quick fix @MarcelHB!

**Comment by MarcelHB** [comment]
@lynxlynxlynx Is it possible to merge or cherry-pick this fix into the subviews? Still having this issue there.
