### ISSUE TITLE
 PST: starting new game sometimes fails

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2132]
#### Bug description
In 1 of 2 or 3 cases, starting a new game in the mortuary fails about after a second when TNO is supposed to raise from the table.

Not sure what's the non-determinism here, but `Stance` shows different values (legal ones, or illegal ones such as 23, 24). Yet I noticed that `CharAnimations` makes a rather aggressive use of `error`, i. e. terminating the game – I'd say that maybe some things should better emit an error line instead of shutting down?

#### Screenshots
```
Thread 1 hit Breakpoint 1.2, 0x00007ffc0dcef1e7 in msvcrt!abort ()
   from C:\Windows\System32\msvcrt.dll
(gdb) bt
#0  0x00007ffc0dcef1e7 in msvcrt!abort () from C:\Windows\System32\msvcrt.dll
#1  0x00007ffb8e57b19c in ?? () from C:\MSYS2\mingw64\bin\libstdc++-6.dll
#2  0x00007ffb8e569b26 in ?? () from C:\MSYS2\mingw64\bin\libstdc++-6.dll
#3  0x00007ffb8e6a3343 in ?? () from C:\MSYS2\mingw64\bin\libstdc++-6.dll
#4  0x00007ffb7bd0d438 in ?? () from C:\MSYS2\mingw64\bin\libopenal-1.dll
#5  0x00007ffb7bd51bcc in ?? () from C:\MSYS2\mingw64\bin\libopenal-1.dll
#6  0x00007ffb7bc9114c in ?? () from C:\MSYS2\mingw64\bin\libopenal-1.dll
#7  0x00007ffb7bc91229 in ?? () from C:\MSYS2\mingw64\bin\libopenal-1.dll
#8  0x00007ffc0e409a1d in ntdll!RtlActivateActivationContextUnsafeFast ()
   from C:\Windows\SYSTEM32\ntdll.dll
#9  0x00007ffc0e44f1da in ntdll!LdrShutdownProcess () from C:\Windows\SYSTEM32\ntdll.dll
#10 0x00007ffc0e44ef8d in ntdll!RtlExitUserProcess () from C:\Windows\SYSTEM32\ntdll.dll
#11 0x00007ffc0cefe3eb in KERNEL32!FatalExit () from C:\Windows\System32\kernel32.dll
#12 0x00007ffc0dcfa155 in msvcrt!_exit () from C:\Windows\System32\msvcrt.dll
#13 0x00007ffc0dcfa7c5 in msvcrt!_initterm_e () from C:\Windows\System32\msvcrt.dll
#14 0x00007ffb810fa512 in GemRB::error<>(char const*, char const*) (
    owner=0x7ffb81284e9d <GemRB::CycleOffset+189> "CharAnimation",
    format=0x7ffb81284e8b <GemRB::CycleOffset+171> "Illegal stance ID")
    at D:/Sources/gemrb/gemrb/core/Logging/Logging.h:57
#15 0x00007ffb80f1824e in GemRB::CharAnimations::GetAnimation (this=0x27cd3460, Stance=24 '\030',
    Orient=GemRB::NW) at D:/Sources/gemrb/gemrb/core/CharAnimations.cpp:851
#16 0x00007ffb80f9019b in GemRB::PlaySequenceCore (Sender=0x27ccec00, parameters=0x27cd7620,
    value=24) at D:/Sources/gemrb/gemrb/core/GameScript/GSUtils.cpp:356
#17 0x00007ffb80f7c209 in GemRB::GameScript::PlaySequence (Sender=0x27ccec00,
    parameters=0x27cd7620) at D:/Sources/gemrb/gemrb/core/GameScript/Actions.cpp:2150
#18 0x00007ffb80f9d77d in GemRB::GameScript::ExecuteAction (Sender=0x27ccec00, aC=0x27cd7620)
    at D:/Sources/gemrb/gemrb/core/GameScript/GameScript.cpp:2257
#19 0x00007ffb8104512c in GemRB::Scriptable::ProcessActions (this=0x27ccec00)
    at D:/Sources/gemrb/gemrb/core/Scriptable/Scriptable.cpp:513
#20 0x00007ffb8104416d in GemRB::Scriptable::Update (this=0x27ccec00)
    at D:/Sources/gemrb/gemrb/core/Scriptable/Scriptable.cpp:199
#21 0x00007ffb80fe40bc in GemRB::Map::UpdateScripts (this=0x27a9a7c0)
    at D:/Sources/gemrb/gemrb/core/Map.cpp:772
#22 0x00007ffb80f6c911 in GemRB::Game::UpdateScripts (this=0x20970600)
    at D:/Sources/gemrb/gemrb/core/Game.cpp:1577
#23 0x00007ffb80fc7444 in GemRB::Interface::GameLoop (this=0x5ff2b0)
    at D:/Sources/gemrb/gemrb/core/Interface.cpp:1796
#24 0x00007ffb80fc27e5 in GemRB::Interface::Main (this=0x5ff2b0)
    at D:/Sources/gemrb/gemrb/core/Interface.cpp:999
#25 0x00007ff66fc31657 in main (argc=3, argv=0x616400)
    at D:/Sources/gemrb/platforms/windows/GemRB.cpp:63
```

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
Hmm, I was modifying PlaySequenceCore for iwd2 stuff, so it's probably one of those 1-3 commits. TNO uses PlaySequence at least for the getting off the table, since that's a special stance.

**Comment by lynxlynxlynx** [comment]
It's not always happening, since the stance choice is randomised in some scripts.
