### ISSUE TITLE
 IWD2: Cleric class upgrade makes game hang

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2157]
#### Bug description
I have a cleric and want to advance to level 3. Unfortunately, the game hangs after choosing a feat. When interrupting the game, the stack is quite big.

#### Steps to reproduce
Load this game and go for the class upgrade of the cleric (_Nummer Vier_) [000000015-6_Shaegarne_before_lvl3.zip](https://github.com/user-attachments/files/17131834/000000015-6_Shaegarne_before_lvl3.zip)

#### Screenshots
```
(gdb) bt
#0  0x00007ffa05ab458e in msvcrt!memmove () from C:\Windows\System32\msvcrt.dll
#1  0x00007ff982573602 in std::__copy_move<true, true, std::random_access_iterator_tag>::__copy_m<GemRB::CREMemorizedSpell*, GemRB::CREMemorizedSpell*> (__first=0x1d362048, __last=0x1df83480,
    __result=0x1d362040) at C:/MSYS2/mingw64/include/c++/14.2.0/bits/stl_algobase.h:452
#2  0x00007ff98264561b in std::__copy_move_a2<true, GemRB::CREMemorizedSpell**, GemRB::CREMemorizedSpell**> (__first=0x1d362048, __last=0x1df83480, __result=0x1d362040)
    at C:/MSYS2/mingw64/include/c++/14.2.0/bits/stl_algobase.h:521
#3  0x00007ff982643f3b in std::__copy_move_a1<true, GemRB::CREMemorizedSpell**, GemRB::CREMemorizedSpell**> (__first=0x1d362048, __last=0x1df83480, __result=0x1d362040)
    at C:/MSYS2/mingw64/include/c++/14.2.0/bits/stl_algobase.h:548
#4  0x00007ff98263fbb0 in std::__copy_move_a<true, __gnu_cxx::__normal_iterator<GemRB::CREMemorizedSpell**, std::vector<GemRB::CREMemorizedSpell*, std::allocator<GemRB::CREMemorizedSpell*> > >, __gnu_cxx::__normal_iterator<GemRB::CREMemoriz
edSpell**, std::vector<GemRB::CREMemorizedSpell*, std::allocator<GemRB::CREMemorizedSpell*> > > > (__first=0x17616d30, __last=0x1f5a47d0, __result=0x17616cf0)
    at C:/MSYS2/mingw64/include/c++/14.2.0/bits/stl_algobase.h:555
#5  0x00007ff98265f9e4 in std::move<__gnu_cxx::__normal_iterator<GemRB::CREMemorizedSpell**, std::vector<GemRB::CREMemorizedSpell*, std::allocator<GemRB::CREMemorizedSpell*> > >, __gnu_cxx::__normal_iterator<GemRB::CREMemorizedSpell**, std:
:vector<GemRB::CREMemorizedSpell*, std::allocator<GemRB::CREMemorizedSpell*> > > > (__first=0x17616d30, __last=0x1f5a47d0, __result=0x17616cf0)
    at C:/MSYS2/mingw64/include/c++/14.2.0/bits/stl_algobase.h:683
#6  0x00007ff9825e008e in std::vector<GemRB::CREMemorizedSpell*, std::allocator<GemRB::CREMemorizedSpell*> >::_M_erase (this=0x154636f0, __position=0x17616cf0)
    at C:/MSYS2/mingw64/include/c++/14.2.0/bits/vector.tcc:185
#7  0x00007ff9825e0004 in std::vector<GemRB::CREMemorizedSpell*, std::allocator<GemRB::CREMemorizedSpell*> >::erase (this=0x154636f0, __position=0x17616cf0)
    at C:/MSYS2/mingw64/include/c++/14.2.0/bits/stl_vector.h:1537
#8  0x00007ff98245ff05 in GemRB::Spellbook::RemoveMemorization (this=0x154611c8, sm=0x154636d0,
    resRef=...) at D:/Sources/gemrb/gemrb/core/Spellbook.cpp:404
#9  0x00007ff982460501 in GemRB::Spellbook::RemoveSpell (this=0x154611c8, resRef=...,
    onlyknown=false) at D:/Sources/gemrb/gemrb/core/Spellbook.cpp:478
#10 0x00007ff98241bd00 in GemRB::ApplyClab_internal (actor=0x15460450, clab=..., level=3,
    remove=true, diff=1) at D:/Sources/gemrb/gemrb/core/Scriptable/Actor.cpp:623
#11 0x00007ff98241cba8 in GemRB::Actor::ApplyClab (this=0x15460450, clab=..., max=3, remove=0,
    diff=1) at D:/Sources/gemrb/gemrb/core/Scriptable/Actor.cpp:854
#12 0x00007ff98241ca9b in GemRB::Actor::ApplyKit (this=0x15460450, remove=false, baseclass=3,
    diff=1) at D:/Sources/gemrb/gemrb/core/Scriptable/Actor.cpp:842
--Type <RET> for more, q to quit, c to continue without paging--c
#13 0x00007ff98241d482 in GemRB::pcf_level (actor=0x15460450, oldValue=2, newValue=3, baseClass=3)
    at D:/Sources/gemrb/gemrb/core/Scriptable/Actor.cpp:985
#14 0x00007ff98241d646 in GemRB::pcf_level_cleric (actor=0x15460450, oldValue=2, newValue=3)
    at D:/Sources/gemrb/gemrb/core/Scriptable/Actor.cpp:1026
#15 0x00007ff982424d97 in GemRB::Actor::SetStat (this=0x15460450, StatIndex=242, Value=3, pcf=512)
    at D:/Sources/gemrb/gemrb/core/Scriptable/Actor.cpp:2470
#16 0x00007ff982424ea3 in GemRB::Actor::SetBase (this=0x15460450, StatIndex=242, Value=3)
    at D:/Sources/gemrb/gemrb/core/Scriptable/Actor.cpp:2501
#17 0x00007ff994be1a7e in SetCreatureStat (actor=0x15460450, StatID=242, StatValue=3, pcf=true)
    at D:/Sources/gemrb/gemrb/plugins/GUIScript/GUIScript.cpp:268
#18 0x00007ff994bf5d88 in GemRB_SetPlayerStat (args=0x1613ac80)
    at D:/Sources/gemrb/gemrb/plugins/GUIScript/GUIScript.cpp:6178
#19 0x00007ff9cd8dd2eb in ?? () from C:\MSYS2\mingw64\bin\libpython3.11.dll
#20 0x00007ff9cd89fa4f in ?? () from C:\MSYS2\mingw64\bin\libpython3.11.dll
#21 0x00007ff9cd8a018b in ?? () from C:\MSYS2\mingw64\bin\libpython3.11.dll
#22 0x00007ff9cd957100 in ?? () from C:\MSYS2\mingw64\bin\libpython3.11.dll
#23 0x00007ff9cd955f34 in ?? () from C:\MSYS2\mingw64\bin\libpython3.11.dll
#24 0x00007ff9cd8a04a1 in ?? () from C:\MSYS2\mingw64\bin\libpython3.11.dll
#25 0x00007ff994c4eb92 in GemRB::CallPython<int, &GemRB::noop<int> > (function=0x160aa7a0,
    args=0x161804c0, retVal=0x5fcdfc)
    at D:/Sources/gemrb/gemrb/plugins/GUIScript/PythonCallbacks.h:45
#26 0x00007ff994c4eb4e in GemRB::CallPython (function=0x160aa7a0, args=0x161804c0)
    at D:/Sources/gemrb/gemrb/plugins/GUIScript/PythonCallbacks.h:65
#27 0x00007ff994c5b3d0 in GemRB::PythonComplexCallback<void, GemRB::Control*>::operator() (
    this=0x26f47530, arg=0x26ab63d0)
    at D:/Sources/gemrb/gemrb/plugins/GUIScript/PythonCallbacks.h:127
#28 0x00007ff994c7246c in std::__invoke_impl<void, GemRB::PythonComplexCallback<void, GemRB::Control*>&, GemRB::Control*> (__f=...) at C:/MSYS2/mingw64/include/c++/14.2.0/bits/invoke.h:61
#29 0x00007ff994c70d7c in std::__invoke_r<void, GemRB::PythonComplexCallback<void, GemRB::Control*>&, GemRB::Control*> (__fn=...) at C:/MSYS2/mingw64/include/c++/14.2.0/bits/invoke.h:150
#30 0x00007ff994c66899 in std::_Function_handler<void(GemRB::Control*), GemRB::PythonComplexCallback<void, GemRB::Control*> >::_M_invoke (__functor=..., __args#0=@0x5fcf48: 0x26ab63d0)
    at C:/MSYS2/mingw64/include/c++/14.2.0/bits/std_function.h:290
#31 0x00007ff982553968 in std::function<void(GemRB::Control*)>::operator() (this=0x26f48b88,
    __args#0=0x26ab63d0) at C:/MSYS2/mingw64/include/c++/14.2.0/bits/std_function.h:591
#32 0x00007ff982529232 in GemRB::View::ActionResponder<GemRB::Control*>::Responder::operator() (
    this=0x26f48b88, responder=0x26ab63d0) at D:/Sources/gemrb/gemrb/core/GUI/ViewInterfaces.h:74
#33 0x00007ff98234570d in GemRB::Control::PerformAction (this=0x26ab63d0, key=...)
    at D:/Sources/gemrb/gemrb/core/GUI/Control.cpp:101
#34 0x00007ff9823461da in GemRB::Control::OnMouseUp (this=0x26ab63d0, me=..., mod=0)
    at D:/Sources/gemrb/gemrb/core/GUI/Control.cpp:288
#35 0x00007ff982342d03 in GemRB::Button::OnMouseUp (this=0x26ab63d0, me=..., mod=0)
    at D:/Sources/gemrb/gemrb/core/GUI/Button.cpp:527
#36 0x00007ff98236cb6c in GemRB::View::MouseUp (this=0x26ab63d0, me=..., mod=0)
    at D:/Sources/gemrb/gemrb/core/GUI/View.cpp:754
#37 0x00007ff98250ae35 in GemRB::Window::DispatchMouseUp (this=0x1f8e8030, target=0x26ab63d0,
    me=..., mod=0) at D:/Sources/gemrb/gemrb/core/GUI/Window.cpp:400
#38 0x00007ff98236f968 in GemRB::Window::DispatchEvent (this=0x1f8e8030, event=...)
    at D:/Sources/gemrb/gemrb/core/GUI/Window.cpp:558
#39 0x00007ff982371ace in GemRB::WindowManager::DispatchEvent (this=0x4a41440, event=...)
    at D:/Sources/gemrb/gemrb/core/GUI/WindowManager.cpp:416
#40 0x00007ff9826416fe in std::__invoke_impl<bool, bool (GemRB::WindowManager::*&)(GemRB::Event const&), GemRB::WindowManager*&, GemRB::Event const&> (
    __f=@0x26c1ab40: (bool (GemRB::WindowManager::*)(GemRB::WindowManager * const, const GemRB::Event &)) 0x7ff9823719ce <GemRB::WindowManager::DispatchEvent(GemRB::Event const&)>,
    __t=@0x26c1ab50: 0x4a41440) at C:/MSYS2/mingw64/include/c++/14.2.0/bits/invoke.h:74
#41 0x00007ff982667ce3 in std::__invoke<bool (GemRB::WindowManager::*&)(GemRB::Event const&), GemRB::WindowManager*&, GemRB::Event const&> (
    __fn=@0x26c1ab40: (bool (GemRB::WindowManager::*)(GemRB::WindowManager * const, const GemRB::Event &)) 0x7ff9823719ce <GemRB::WindowManager::DispatchEvent(GemRB::Event const&)>)
    at C:/MSYS2/mingw64/include/c++/14.2.0/bits/invoke.h:96
#42 0x00007ff9825b53a4 in std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>::__call<bool, GemRB::Event const&, 0ull, 1ull>(std::tuple<GemRB::Event const&>&&, std::_Index_tuple<0ull,
 1ull>) (this=0x26c1ab40, __args=...)
    at C:/MSYS2/mingw64/include/c++/14.2.0/functional:513
#43 0x00007ff9825b54c1 in std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>::operator()<GemRB::Event const&, bool>(GemRB::Event const&) (
    this=0x26c1ab40) at C:/MSYS2/mingw64/include/c++/14.2.0/functional:598
#44 0x00007ff982641979 in std::__invoke_impl<bool, std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>&, GemRB::Event const&>(std::__invoke_other, std::_Bind<bool (GemRB::WindowManage
r::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>&, GemRB::Event const&) (__f=...)
    at C:/MSYS2/mingw64/include/c++/14.2.0/bits/invoke.h:61
#45 0x00007ff982634f8c in std::__invoke_r<bool, std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)>&, GemRB::Event const&>(std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManage
r*, std::_Placeholder<1>))(GemRB::Event const&)>&, GemRB::Event const&) (__fn=...) at C:/MSYS2/mingw64/include/c++/14.2.0/bits/invoke.h:138
#46 0x00007ff9825a1449 in std::_Function_handler<bool (GemRB::Event const&), std::_Bind<bool (GemRB::WindowManager::*(GemRB::WindowManager*, std::_Placeholder<1>))(GemRB::Event const&)> >::_M_invoke(std::_Any_data const&, GemRB::Event const
&) (__functor=..., __args#0=...)
    at C:/MSYS2/mingw64/include/c++/14.2.0/bits/std_function.h:290
#47 0x00007ff982553868 in std::function<bool(GemRB::Event const&)>::operator() (this=0x1f8c0db0,
    __args#0=...) at C:/MSYS2/mingw64/include/c++/14.2.0/bits/std_function.h:591
#48 0x00007ff982347c66 in GemRB::EventMgr::DispatchEvent (this=0x4a41540, e=...)
    at D:/Sources/gemrb/gemrb/core/GUI/EventMgr.cpp:272
#49 0x00007ff991cd1bac in GemRB::SDLVideoDriver::ProcessEvent (this=0xdddf70, event=...)
    at D:/Sources/gemrb/gemrb/plugins/SDLVideo/SDLVideo.cpp:206
#50 0x00007ff991cd84b3 in GemRB::SDL20VideoDriver::ProcessEvent (this=0xdddf70, event=...)
    at D:/Sources/gemrb/gemrb/plugins/SDLVideo/SDL20Video.cpp:972
#51 0x00007ff991cd1593 in GemRB::SDLVideoDriver::PollEvents (this=0xdddf70)
    at D:/Sources/gemrb/gemrb/plugins/SDLVideo/SDLVideo.cpp:58
#52 0x00007ff98246e7c3 in GemRB::Video::SwapBuffers (this=0xdddf70, fpscap=0)
    at D:/Sources/gemrb/gemrb/core/Video/Video.cpp:160
#53 0x00007ff9823d2034 in GemRB::Interface::Main (this=0x5ff2b0)
    at D:/Sources/gemrb/gemrb/core/Interface.cpp:1020
#54 0x00007ff6c6011647 in main (argc=1, argv=0xfb4be0)
    at D:/Sources/gemrb/platforms/windows/GemRB.cpp:63
```

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
Might be the same thing I see with paladins from level 3 on. Because they get 3 copies of a spell by design (turn undead in their clab), our code currently miscounts them and bumps the memorization count absurdly with each save. Clerics get it from the start, so it could be the exact same thing. Anyway, currently on my plate.

**Comment by lynxlynxlynx** [comment]
Yeah, same thing, he has thousands of memorizations of turn undead even before attempting to level up. Let me know if you want to fix this or some other existing save, it's doable via the console.

**Comment by MarcelHB** [comment]
I fixed that by hand on my save, too, since I had many millions of innate spells already. Which also made loading and exiting take minutes for all the (de)allocation.

But is the cause known and fixed then?

**Comment by MarcelHB** [comment]
Sounds like d0ea67e2aa8dbf6e7a8ba6bce35985c6e076901a did the job.

**Comment by lynxlynxlynx** [comment]
Yes. It's basically a dupe of an older bug we had open on ApplyFeats. I fixed all the obvious code there, but this escaped me ... until I leveled up recently.
