### ISSUE TITLE
IWD2: Segfault on dragon fight in Chult temple

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2183]
#### Bug description
Segmentation fault. Map pointer is apprently `nullptr`.

#### Steps to reproduce
1. Leave IWD2 Chult temple (AR6501) and watch for the dragon fight to begin
2. Occassionally switch between inside and outside while dragon is doing spells and attacks.
3. At some occasion, dragon follows into the basement.
4. Get outside again.
5. Try to get inside again.

#### Screenshots
```
(gdb) bt
#0  0x00007ffccddfa37c in std::vector<GemRB::Actor*, std::allocator<GemRB::Actor*> >::size (this=0x348) at C:/MSYS2/mingw64/include/c++/14.2.0/bits/stl_vector.h:993
#1  0x00007ffccdcaa8b5 in GemRB::Map::GetActorCount (this=0x0, any=true) at D:/Sources/gemrb/gemrb/core/Map.cpp:2174
#2  0x00007ffccdbedca1 in GemRB::EffectQueue::AffectAllInRange (this=0x5fda30, map=0x0, pos=..., idstype=0, idsvalue=0, range=750, except=0x2f549df0) at D:/Sources/gemrb/gemrb/core/EffectQueue.cpp:2318
#3  0x00007ffcca5d83b2 in fx_area_effect (Owner=0x2f549df0, target=0x2f549df0, fx=0x2f559eb0) at D:/Sources/gemrb/gemrb/plugins/IWDOpcodes/IWDOpcodes.cpp:2527
#4  0x00007ffccddd76f4 in GemRB::EffectDesc::operator() (this=0x7ffccdf41b80 <GemRB::Globals::Get()::globs+13344>, s=0x2f549df0, a=0x2f549df0, fx=0x2f559eb0) at D:/Sources/gemrb/gemrb/core/EffectQueue.h:156
#5  0x00007ffccdbea932 in GemRB::EffectQueue::ApplyEffect (this=0x2f54ac60, target=0x2f549df0, fx=0x2f559eb0, first_apply=0, resistance=1) at D:/Sources/gemrb/gemrb/core/EffectQueue.cpp:1280
#6  0x00007ffccdbe7eba in GemRB::EffectQueue::ApplyAllEffects (this=0x2f54ac60, target=0x2f549df0) at D:/Sources/gemrb/gemrb/core/EffectQueue.cpp:464
#7  0x00007ffccdcd80d1 in GemRB::Actor::RefreshEffects (this=0x2f549df0, first=true, previous=...) at D:/Sources/gemrb/gemrb/core/Scriptable/Actor.cpp:2680
#8  0x00007ffccdcd89ce in GemRB::Actor::RefreshEffects (this=0x2f549df0) at D:/Sources/gemrb/gemrb/core/Scriptable/Actor.cpp:2815
#9  0x00007ffccd70698b in GemRB::AREImporter::GetActor (this=0x2ad09510, str=0x2ad09340, actorMgr=std::shared_ptr<GemRB::ActorMgr> (use count 2, weak count 0) = {...}, map=0x2ea311f0)
    at D:/Sources/gemrb/gemrb/plugins/AREImporter/AREImporter.cpp:1197
#10 0x00007ffccd708ce1 in GemRB::AREImporter::GetMap (this=0x2ad09510, resRef=..., day_or_night=true) at D:/Sources/gemrb/gemrb/plugins/AREImporter/AREImporter.cpp:1562
#11 0x00007ffccdc2a0a1 in GemRB::Game::LoadMap (this=0x20b9a7d0, resRef=..., loadscreen=false) at D:/Sources/gemrb/gemrb/core/Game.cpp:851
#12 0x00007ffccdc29426 in GemRB::Game::GetMap (this=0x20b9a7d0, areaName=..., change=false) at D:/Sources/gemrb/gemrb/core/Game.cpp:671
#13 0x00007ffccdca3c89 in GemRB::Map::MoveToNewArea (this=0x25466580, area=..., entrance=..., direction=0, EveryOne=3, actor=0x22e4d290) at D:/Sources/gemrb/gemrb/core/Map.cpp:520
#14 0x00007ffccdca44b4 in GemRB::Map::UseExit (this=0x25466580, actor=0x22e4d290, ip=0x254f87b0) at D:/Sources/gemrb/gemrb/core/Map.cpp:635
#15 0x00007ffccdca4eb1 in GemRB::Map::UpdateScripts (this=0x25466580) at D:/Sources/gemrb/gemrb/core/Map.cpp:860
#16 0x00007ffccdc2ce81 in GemRB::Game::UpdateScripts (this=0x20b9a7d0) at D:/Sources/gemrb/gemrb/core/Game.cpp:1577
#17 0x00007ffccdc87d24 in GemRB::Interface::GameLoop (this=0x5ff2b0) at D:/Sources/gemrb/gemrb/core/Interface.cpp:1798
#18 0x00007ffccdc83085 in GemRB::Interface::Main (this=0x5ff2b0) at D:/Sources/gemrb/gemrb/core/Interface.cpp:999
#19 0x00007ff7390f1647 in main (argc=1, argv=0x6163e0) at D:/Sources/gemrb/platforms/windows/GemRB.cpp:63
```

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
Nice torture, but easy to fix.
