### ISSUE TITLE
 GUIMG: Cannot remove spell

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2247]
#### Bug description
When trying to remove a mage spell from the book, after confirming, there is a Python error saying:

```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "D:/Sources\gemrb\gemrb\GUIScripts/GUIMG.py", line 304, in RemoveSpell
[Python/ERROR]:     OnMageRemoveSpell(btn)
[Python/ERROR]:   File "D:/Sources\gemrb\gemrb\GUIScripts/GUIMG.py", line 372, in OnMageRemoveSpell
[Python/ERROR]:     GemRB.RemoveSpell (pc, spelltype, level, index)
[Python/ERROR]: TypeError: 'NoneType' object cannot be interpreted as an integer
```

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
Ah, cool, so this isn't limited to ees. index is None there, the lambda expecting to automatically get a button. Should be trivial to fix.
