### ISSUE TITLE
[subviews] SDL2 assertion failure on spell casting

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#227]
**Describe the bug**
After #225, when you choose Magic Missile and cast it, the game crashes at some point.

**To Reproduce**
1. Load a game (IWD2?)
2. Pick a caster and Magic Missle.
3. Cast it on some actor.

**Expected behavior**
No crash.

**Screenshots**
```gdb
Assertion failed: ret == 0, file ./gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp, line 186

Thread 1 hit Breakpoint 1, 0x000007feff0e5383 in msvcrt!abort ()
   from C:\Windows\system32\msvcrt.dll
(gdb) bt
#0  0x000007feff0e5383 in msvcrt!abort () from C:\Windows\system32\msvcrt.dll
#1  0x000007feff0e23ab in msvcrt!_assert ()
   from C:\Windows\system32\msvcrt.dll
#2  0x0000000002ca666a in GemRB::SDLSurfaceSprite2D::GetColorKey (
    this=<optimized out>)
    at ./gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp:181
#3  GemRB::SDLSurfaceSprite2D::GetColorKey (this=<optimized out>)
    at ./gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp:181
#4  0x0000000002ca6b63 in GemRB::SDLSurfaceSprite2D::SetPalette (
    this=0xeee3320, pal=0xeee3990)
    at ./gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp:165
#5  0x0000000069f589fd in GemRB::Video::BlitGameSpriteWithPalette (
    this=0x4dc0b0, spr=0xeee3320, pal=0xeee3990, x=592, y=408, flags=0,
    tint=..., cover=0x0, clip=0x0)
    at ./gemrb/core/Video.cpp:247
#6  0x0000000069f19e23 in GemRB::Projectile::Draw (this=this@entry=0xeed7010,
    spr=0xeee3320, p=..., flags=0, tint=...)
    at ./gemrb/core/Projectile.cpp:1864
#7  0x0000000069f1a09f in GemRB::Projectile::DrawTravel (this=0xeed7010,
    viewport=...)
    at ./gemrb/core/Projectile.cpp:1744
#8  0x0000000069f1b17d in GemRB::Projectile::Draw (this=this@entry=0xeed7010,
    viewport=...)
    at ./gemrb/core/Projectile.cpp:1309
#9  0x0000000069f091d0 in GemRB::Map::DrawMap (this=this@entry=0xa054850,
    viewport=...)
    at ./gemrb/core/Map.cpp:1226
#10 0x0000000069e9e467 in GemRB::GameControl::DrawSelf (this=0x64698f0,
    screen=...)
    at ./gemrb/core/GUI/GameControl.cpp:540
#11 0x0000000069eb1eb8 in GemRB::View::Draw (this=0x64698f0)
    at ./MSYS2/mingw64/include/c++/9.2.0/bits/stl_iterator.h:806
#12 0x0000000069eb1e31 in GemRB::View::DrawSubviews (this=0x4e1220)
    at ./gemrb/core/GUI/View.cpp:158
#13 GemRB::View::Draw (this=0x4e1220)
    at ./gemrb/core/GUI/View.cpp:210
#14 0x0000000069eb1e31 in GemRB::View::DrawSubviews (this=0x4e1130)
    at ./gemrb/core/GUI/View.cpp:158
#15 GemRB::View::Draw (this=0x4e1130)
    at ./gemrb/core/GUI/View.cpp:210
#16 0x0000000069eb5f34 in GemRB::WindowManager::DrawWindows (this=0x4e0940)
    at ./gemrb/core/GUI/WindowManager.cpp:515
#17 0x0000000069ef71e1 in GemRB::Interface::Main (this=0x4d24b0)
    at ./gemrb/core/Interface.cpp:971
#18 0x0000000000402bf8 in main (argc=3, argv=0x392a00)
    at ./gemrb/GemRB.cpp:99
```

**Comment by bradallred** [comment]
Thank you for the easy one :)
