### ISSUE TITLE
[bug] BG2: Crashes when applying spell effects to enemy creatures

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#243]
**Description**
I've been having some Segmentation fault crashes in combat as of late, when enemies casting spells on themselves. 

Case 1: The Shade Lord casts Blade Barrier on himself:
```
...
[GameScript]: Displaying string on: shadel
[ResourceManager]: Found 'SPPR698.spl' in 'chitin.key'.

Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.
fx_cast_spell_on_condition (Owner=0x0, target=0x5555593da0d0, 
    fx=0x555556c786f0)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/plugins/FXOpcodes/FXOpcodes.cpp:6143
6143			if (Owner->Type != ST_ACTOR) {
(gdb) backtrace
#0  fx_cast_spell_on_condition (Owner=0x0, target=0x5555593da0d0, 
    fx=0x555556c786f0)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/plugins/FXOpcodes/FXOpcodes.cpp:6143
#1  0x00007ffff7aaf763 in GemRB::EffectQueue::ApplyEffect (
    this=0x555556968c30, target=0x5555593da0d0, fx=0x555556c786f0, 
    first_apply=<optimized out>, resistance=<optimized out>)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/EffectQueue.cpp:1329
#2  0x00007ffff7ab0467 in GemRB::EffectQueue::AddEffect (
    this=this@entry=0x555556968c30, fx=0x555556c786f0, self=0x0, 
    pretarget=pretarget@entry=0x5555593da0d0, dest=...)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/EffectQueue.cpp:687
#3  0x00007ffff7ab0ad3 in GemRB::EffectQueue::AddAllEffects (
    this=this@entry=0x555556968c30, target=target@entry=0x5555593da0d0, 
    destination=...)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/EffectQueue.cpp:784
#4  0x00007ffff7ac5a65 in GemRB::Interface::ApplyEffectQueue (
    this=this@entry=0x555555768c80, fxqueue=fxqueue@entry=0x555556968c30, 
    actor=actor@entry=0x5555593da0d0, caster=caster@entry=0x0, p=...)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Interface.cpp:5056
---Type <return> to continue, or q <return> to quit---
#5  0x00007ffff7ac5aed in GemRB::Interface::ApplySpell (this=0x555555768c80, 
    resname=resname@entry=0x7fffffffdde7 "SPPR698", 
    actor=actor@entry=0x5555593da0d0, caster=caster@entry=0x0, level=0)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Interface.cpp:4998
#6  0x00007ffff7b0db9b in GemRB::GameScript::ApplySpell (
    Sender=0x5555593da0d0, parameters=0x555559421330)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/GameScript/Actions.cpp:6158
#7  0x00007ffff7b1bc65 in GemRB::GameScript::ExecuteAction (
    Sender=Sender@entry=0x5555593da0d0, aC=0x555559421330)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/GameScript/GameScript.cpp:2427
#8  0x00007ffff7b68a32 in GemRB::Scriptable::AddAction (
    this=this@entry=0x5555593da0d0, aC=<optimized out>)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Scriptable/Scriptable.cpp:468
#9  0x00007ffff7b1bfc7 in GemRB::Response::Execute (this=0x555559420460, 
    Sender=0x5555593da0d0)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/GameScript/GameScript.cpp:2356
#10 0x00007ffff7b1c323 in GemRB::GameScript::Update (this=0x5555594237e0, 
    continuing=continuing@entry=0x7fffffffdf1e, done=done@entry=0x7fffffffdf1f)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/GameScript/GameScri---Type <return> to continue, or q <return> to quit---
pt.cpp:2049
#11 0x00007ffff7b691ef in GemRB::Scriptable::ExecuteScript (
    this=0x5555593da0d0, scriptCount=<optimized out>)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Scriptable/Scriptable.cpp:426
#12 0x00007ffff7b68f72 in GemRB::Scriptable::Update (this=0x5555593da0d0)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Scriptable/Scriptable.cpp:324
#13 0x00007ffff7ae03eb in GemRB::Map::UpdateScripts (this=0x555557b42120)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Map.cpp:768
#14 0x00007ffff7ab66b5 in GemRB::Game::UpdateScripts (this=0x555558712d90)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Game.cpp:1605
#15 0x00007ffff7ac5827 in GemRB::Interface::GameLoop (this=<optimized out>)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Interface.cpp:2979
#16 0x00007ffff7acb275 in GemRB::Interface::Main (this=0x555555768c80)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Interface.cpp:1001
#17 0x0000555555554e12 in main (argc=<optimized out>, argv=0x7fffffffe208)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/GemRB.cpp:99
```

Case 2: A drider from Check the Bodies mod casts Improved Invisibility on himself:
```
...
[GameScript]: Displaying string on: cbdrifal
[ResourceManager]: Found 'SPWI405.spl' in 'chitin.key'.

Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.
fx_cast_spell (Owner=0x0, target=0x5555573c3a70, fx=0x55555798c540)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/plugins/FXOpcodes/FXOpcodes.cpp:4447
4447		if (Owner->Type == ST_ACTOR) {
(gdb) bt
#0  fx_cast_spell (Owner=0x0, target=0x5555573c3a70, fx=0x55555798c540)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/plugins/FXOpcodes/FXOpcodes.cpp:4447
#1  0x00007ffff7aaf763 in GemRB::EffectQueue::ApplyEffect (
    this=0x555555ae1250, target=0x5555573c3a70, fx=0x55555798c540, 
    first_apply=<optimized out>, resistance=<optimized out>)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/EffectQueue.cpp:1329
#2  0x00007ffff7ab0467 in GemRB::EffectQueue::AddEffect (
    this=this@entry=0x555555ae1250, fx=0x55555798c540, self=0x0, 
    pretarget=pretarget@entry=0x5555573c3a70, dest=...)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/EffectQueue.cpp:687
#3  0x00007ffff7ab0ad3 in GemRB::EffectQueue::AddAllEffects (
    this=this@entry=0x555555ae1250, target=target@entry=0x5555573c3a70, 
    destination=...)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/EffectQueue.cpp:784
#4  0x00007ffff7ac5a65 in GemRB::Interface::ApplyEffectQueue (
    this=this@entry=0x555555768c80, fxqueue=fxqueue@entry=0x555555ae1250, 
    actor=actor@entry=0x5555573c3a70, caster=caster@entry=0x0, p=...)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Interface.cpp:5056
#5  0x00007ffff7ac5aed in GemRB::Interface::ApplySpell (this=0x555555768c80, 
---Type <return> to continue, or q <return> to quit---
    resname=resname@entry=0x7fffffffdde7 "SPWI405", 
    actor=actor@entry=0x5555573c3a70, caster=caster@entry=0x0, level=0)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Interface.cpp:4998
#6  0x00007ffff7b0db9b in GemRB::GameScript::ApplySpell (
    Sender=0x5555573c3a70, parameters=0x555557400360)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/GameScript/Actions.cpp:6158
#7  0x00007ffff7b1bc65 in GemRB::GameScript::ExecuteAction (
    Sender=Sender@entry=0x5555573c3a70, aC=0x555557400360)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/GameScript/GameScript.cpp:2427
#8  0x00007ffff7b68a32 in GemRB::Scriptable::AddAction (
    this=this@entry=0x5555573c3a70, aC=<optimized out>)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Scriptable/Scriptable.cpp:468
#9  0x00007ffff7b1bfc7 in GemRB::Response::Execute (this=0x5555573ff850, 
    Sender=0x5555573c3a70)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/GameScript/GameScript.cpp:2356
#10 0x00007ffff7b1c323 in GemRB::GameScript::Update (this=0x55555736b900, 
    continuing=continuing@entry=0x7fffffffdf1e, done=done@entry=0x7fffffffdf1f)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/GameScript/GameScript.cpp:2049
---Type <return> to continue, or q <return> to quit---
#11 0x00007ffff7b691ef in GemRB::Scriptable::ExecuteScript (
    this=0x5555573c3a70, scriptCount=<optimized out>)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Scriptable/Scriptable.cpp:426
#12 0x00007ffff7b68f72 in GemRB::Scriptable::Update (this=0x5555573c3a70)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Scriptable/Scriptable.cpp:324
#13 0x00007ffff7ae03eb in GemRB::Map::UpdateScripts (this=0x555555ab5770)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Map.cpp:768
#14 0x00007ffff7ab66b5 in GemRB::Game::UpdateScripts (this=0x555555bd5f70)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Game.cpp:1605
#15 0x00007ffff7ac5827 in GemRB::Interface::GameLoop (this=<optimized out>)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Interface.cpp:2979
#16 0x00007ffff7acb275 in GemRB::Interface::Main (this=0x555555768c80)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/core/Interface.cpp:1001
#17 0x0000555555554e12 in main (argc=<optimized out>, argv=0x7fffffffe208)
    at /home/nadia/Software/Games/gemrb2019_09_15/gemrb/GemRB.cpp:99
```

Since this installation is heavily modded probably some mod messed this up. I wouldn't have reported this if it had only affected mod creatures from CtB. Please ignore it if it's a waste of time for you.

**Comment by lynxlynxlynx** [comment]
Crashes should never happen, however horrible the data may be (unclear for this case). We can assert correctness when needed, which would have a similar effect, but crashes signal unhandled behaviour. Here somehow the owner of the effect got lost, which clearly shouldn't happen. Both crashes likely have the same cause, since these two effects are similar.

**Comment by caillean7** [comment]
Strangely, I've played through this Shade Lord thing so often on two older installations, it never crashed. But now it actually does on these installations, too.

**Comment by caillean7** [comment]
I'll be damned, it crashes on the unmodded game, too. To reproduce: on a save with the Shade Lord still alive, MoveToArea("AR1400"), Ctrl+J to the altar area (might need to enter the dragon's lair and come back out), fight the Shade Lord. He should cast Blade Barrier when his HP get below 25%.

**Comment by caillean7** [comment]
I checked the latest commits and did some bisecting, turns out it started with https://github.com/gemrb/gemrb/commit/9c39224140501d15bab5ecfa496edbda5bdd1a33 and my "OMG, I killed Elminster!". Prior versions don't crash on both my test cases.

**Comment by lynxlynxlynx** [comment]
Ok, good find, so #206 needs a more complicated fix.

**Comment by caillean7** [comment]
Might be a good idea to revert the changes of https://github.com/gemrb/gemrb/commit/9c39224140501d15bab5ecfa496edbda5bdd1a33 for the time being? The dream xp thing is hardly an issue, while the crashing is rather game-breaking. It surely will also affect other enemies scripted to cast spells on themselves.
