### ISSUE TITLE
[subviews] Opening a bag in HoW broken

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#395]
**Describe the bug**
In IWD HoW, have some kind of bag, let's say BAGH01. Opening the bag causes a script error. Looks related to #370.

```python
[Python]: no control with id=110
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File ".\gemrb\GUIScripts\GUISTORE.py", line 218, in OpenStoreWindow
[Python/ERROR]:     store_funcs[store_buttons[0]] ()
[Python/ERROR]:   File ".\gemrb\GUIScripts\GUICommonWindows.py", line 1377, in ret
[Python/ERROR]:     initer(window)
[Python/ERROR]:   File ".\gemrb\GUIScripts\GUISTORE.py", line 383, in InitStoreShoppingWindow
[Python/ERROR]:     IE_FONT_ALIGN_LEFT|IE_FONT_ALIGN_TOP|IE_FONT_SINGLE_LINE)
[Python/ERROR]:   File ".\gemrb\GUIScripts\GUIClasses.py", line 350, in CreateLabel
[Python/ERROR]:     return self.CreateControl(labelid, IE_GUI_LABEL, 0, 0, frame['w'], frame['h'], args)
[Python/ERROR]:   File ".\gemrb\GUIScripts\GUIClasses.py", line 147, in CreateControl
[Python/ERROR]:     return self.CreateSubview(id, type, frame, *args)
[Python/ERROR]:   File ".\gemrb\GUIScripts\GUIClasses.py", line 159, in CreateSubview
[Python/ERROR]:     view = CreateView(id, type, frame, *args)
[Python/ERROR]: SystemError: error return without exception set
```

**Comment by bradallred** [comment]
can you re run this with a build after 226b5cf to get a better error?

**Comment by lynxlynxlynx** [comment]
no control with id=110 <-- this is the same problematic control as in my last store bug report (aliases).

**Comment by MarcelHB** [comment]
Sure, here you go:
```python
[Python]: no control with id=110
[GUIScript/ERROR]: Runtime Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File ".\GUIScripts\GUISTORE.py", line 218, in OpenStoreWindow
[Python/ERROR]:     store_funcs[store_buttons[0]] ()
[Python/ERROR]:   File ".\GUIScripts\GUICommonWindows.py", line 1377, in ret
[Python/ERROR]:     initer(window)
[Python/ERROR]:   File ".\GUIScripts\GUISTORE.py", line 383, in InitStoreShoppingWindow
[Python/ERROR]:     IE_FONT_ALIGN_LEFT|IE_FONT_ALIGN_TOP|IE_FONT_SINGLE_LINE)
[Python/ERROR]:   File ".\GUIScripts\GUIClasses.py", line 350, in CreateLabel
[Python/ERROR]:     return self.CreateControl(labelid, IE_GUI_LABEL, 0, 0, frame['w'], frame['h'], args)
[Python/ERROR]:   File ".\GUIScripts\GUIClasses.py", line 147, in CreateControl
[Python/ERROR]:     return self.CreateSubview(id, type, frame, *args)
[Python/ERROR]:   File ".\GUIScripts\GUIClasses.py", line 159, in CreateSubview
[Python/ERROR]:     view = CreateView(id, type, frame, *args)
[Python/ERROR]: RuntimeError: Cannot construct object with null ref.
```

**Comment by bradallred** [comment]
> no control with id=110 <-- this is the same problematic control as in my last store bug report (aliases).

but that didn't mater as you can see my fix for that issue still outputs that same message. its just garbage that needs to be cleaned up it wasn't an actual problem in your case at all. I doubt its an issue here either since I see no reference to it in the GUISTORE.

**Comment by lynxlynxlynx** [comment]
If you mean the CHU, then of course not, it's a temporary ID in master.

**Comment by bradallred** [comment]
and it's useless garbage here AFICT. You are going to get that message anytime you open up the store. It can't be a problem unless something tries to reference `STODONAT` and nothing ever does. I mean delete that entry from the map and see that everything still works that works with it and everything that doesn't still doesn't.

**Comment by bradallred** [comment]
@MarcelHB would you mind trying that now?

**Comment by MarcelHB** [comment]
Hm, now I get crashes when loading the game:
```gdb
Thread 1 received signal SIGSEGV, Segmentation fault.
GemRB::Window::RedrawControls (this=0x0, VarName=0x5f2f1d0 "SelectedWindow",
    Sum=0)
    at ./gemrb/core/GUI/Window.cpp:209
209             for (std::set<Control *>::iterator c = Controls.begin(); c != Controls.end(); ++c) {
(gdb) bt
#0  GemRB::Window::RedrawControls (this=0x0,
    VarName=0x5f2f1d0 "SelectedWindow", Sum=0)
    at ./gemrb/core/GUI/Window.cpp:209
#1  0x0000000001068e4d in GemRB_Control_SetVarAssoc (self=<optimized out>,
    args=<optimized out>)
    at ./gemrb/plugins/GUIScript/GUIScript.cpp:1872
#2  0x000000001e0c3de9 in python27!PyCFunction_Call ()
   from C:\Windows\system32\python27.dll
#3  0x000000001e11425a in python27!PyEval_GetGlobals ()
   from C:\Windows\system32\python27.dll
#4  0x000000001e11805f in python27!PyEval_EvalFrameEx ()
   from C:\Windows\system32\python27.dll
#5  0x000000001e119822 in python27!PyEval_EvalCodeEx ()
   from C:\Windows\system32\python27.dll
#6  0x000000001e112e99 in python27!PyEval_GetFuncDesc ()
   from C:\Windows\system32\python27.dll
#7  0x000000001e114804 in python27!PyEval_GetGlobals ()
   from C:\Windows\system32\python27.dll
#8  0x000000001e117f84 in python27!PyEval_EvalFrameEx ()
   from C:\Windows\system32\python27.dll
#9  0x000000001e119822 in python27!PyEval_EvalCodeEx ()
   from C:\Windows\system32\python27.dll
#10 0x000000001e112e99 in python27!PyEval_GetFuncDesc ()
   from C:\Windows\system32\python27.dll
#11 0x000000001e114804 in python27!PyEval_GetGlobals ()
   from C:\Windows\system32\python27.dll
#12 0x000000001e117f84 in python27!PyEval_EvalFrameEx ()
   from C:\Windows\system32\python27.dll
#13 0x000000001e119822 in python27!PyEval_EvalCodeEx ()
   from C:\Windows\system32\python27.dll
#14 0x000000001e112e99 in python27!PyEval_GetFuncDesc ()
   from C:\Windows\system32\python27.dll
#15 0x000000001e114804 in python27!PyEval_GetGlobals ()
   from C:\Windows\system32\python27.dll
#16 0x000000001e117f84 in python27!PyEval_EvalFrameEx ()
   from C:\Windows\system32\python27.dll
#17 0x000000001e119822 in python27!PyEval_EvalCodeEx ()
   from C:\Windows\system32\python27.dll
#18 0x000000001e112e99 in python27!PyEval_GetFuncDesc ()
   from C:\Windows\system32\python27.dll
#19 0x000000001e114804 in python27!PyEval_GetGlobals ()
   from C:\Windows\system32\python27.dll
#20 0x000000001e117f84 in python27!PyEval_EvalFrameEx ()
   from C:\Windows\system32\python27.dll
#21 0x000000001e119822 in python27!PyEval_EvalCodeEx ()
   from C:\Windows\system32\python27.dll
#22 0x000000001e0b58a3 in python27!PyFunction_SetClosure ()
   from C:\Windows\system32\python27.dll
#23 0x000000001e08daf5 in python27!PyObject_Call ()
   from C:\Windows\system32\python27.dll
#24 0x000000001e112c28 in python27!PyEval_CallObjectWithKeywords ()
   from C:\Windows\system32\python27.dll
#25 0x000000000105fcd5 in GemRB::GUIScript::RunFunction (
    this=this@entry=0x794970,
    moduleName=moduleName@entry=0x69f9d16f <GemRB::StatValues+1903> "Game",
    functionName=0x69f9d853 <GemRB::StatValues+3667> "EnterGame",
    pArgs=pArgs@entry=0x0, report_error=report_error@entry=true)
    at ./gemrb/plugins/GUIScript/GUIScript.cpp:13511
#26 0x00000000010603d0 in GemRB::GUIScript::RunFunction (this=0x794970,
    moduleName=0x69f9d16f <GemRB::StatValues+1903> "Game",
    functionName=<optimized out>, report_error=true, intparam=-1)
    at ./gemrb/plugins/GUIScript/GUIScript.cpp:13529
#27 0x0000000069ef43fa in GemRB::Interface::HandleFlags (
    this=this@entry=0x7724b0)
    at ./gemrb/core/Interface.cpp:590
#28 0x0000000069ef81b8 in GemRB::Interface::Main (this=0x7724b0)
    at ./gemrb/core/Interface.cpp:963
#29 0x0000000000402bf8 in main (argc=3, argv=0x752a40)
    at ./gemrb/GemRB.cpp:99
```

**Comment by bradallred** [comment]
this now might be another manifestation of the whole #386 at this point. I'll have to dl IWD and get that fixed.

**Comment by bradallred** [comment]
@MarcelHB the NULL dereference is fixed, but I have no idea if there is something else for IWD1. I'm checking the other games I do have installed.

**Comment by MarcelHB** [comment]
Can I help by doing something particular, then?

**Comment by bradallred** [comment]
not at this time. I see something wrong that might fix this.

**Comment by bradallred** [comment]
ok, I think this should work now.

**Comment by bradallred** [comment]
Well, it _might_ work now. It seems the problem I am encountering now is unrelated to this or the changes surrounding this issue.

**Comment by bradallred** [comment]
ok, it's a master bug. opening a new issue.

**Comment by bradallred** [comment]
@MarcelHB is this still an issue?

**Comment by MarcelHB** [comment]
Will test it later.

**Comment by MarcelHB** [comment]
The script error is gone, yes.

But there is different issue of functional nature now. I must test how this is related to master first, I'll put it in a new report then.
