### ISSUE TITLE
[subviews] Python error on PST portrait window code

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#443]
When starting a game in PST, you get this error and some hanging UI (action bar, portraits not working):

```python
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File ".\gemrb\GUIScripts\pst\Game.py", line 35, in EnterGame
[Python/ERROR]:     MessageWindow.OnLoad()
[Python/ERROR]:   File ".\gemrb\GUIScripts\pst\MessageWindow.py", line 65, in OnLoad
[Python/ERROR]:     PortraitWindow = GUICommonWindows.OpenPortraitWindow (1, WINDOW_BOTTOM|WINDOW_HCENTER)
[Python/ERROR]:   File ".\gemrb\GUIScripts\GUICommonWindows.py", line 1638, in OpenPortraitWindow
[Python/ERROR]:     UpdatePortraitWindow ()
[Python/ERROR]:   File ".\gemrb\GUIScripts\GUICommonWindows.py", line 1654, in UpdatePortraitWindow
[Python/ERROR]:     UpdateAnimatedPortrait(Window, i)
[Python/ERROR]:   File ".\gemrb\GUIScripts\GUICommonWindows.py", line 1774, in UpdateAnimatedPortrait
[Python/ERROR]:     ratio = (hp + 0.0) / hp_max
[Python/ERROR]: TypeError: cannot concatenate 'str' and 'float' objects
```

Looks like a younger bug, works on master.

**Comment by lynxlynxlynx** [comment]
Yeah, subviews just needs to be brought up to speed with master.
