### ISSUE TITLE
[subviews] IWD2 sometimes fails to setup the message window correctly

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#558]
**Describe the bug**
_Sometimes_ in IWD2 now, after loading, I hit this error, ending up in a action bar where it's not supposed to be:

```python
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File ".\gemrb\GUIScripts\iwd2\MessageWindow.py", line 89, in UpdateControlStatus
[Python/ERROR]:     largeMW.SetVisible(False)
[Python/ERROR]: AttributeError: 'NoneType' object has no attribute 'SetVisible'
```
![iwd_positioning](https://user-images.githubusercontent.com/238558/71329422-4d5a4280-2525-11ea-88b8-d9d76fd12057.jpg)

**Comment by lynxlynxlynx** [comment]
I can reproduce this reliably, just load a save and talk. Don't see any pattern though:
```python
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "../gemrb/GUIScripts/iwd2/GUIWORLD.py", line 54, in DialogStarted
[Python/ERROR]:     MessageWindow.UpdateControlStatus()
[Python/ERROR]:   File "../gemrb/GUIScripts/iwd2/MessageWindow.py", line 105, in UpdateControlStatus
[Python/ERROR]:     smallMTA = largeMW.AddSubview(smallMTA)
[Python/ERROR]:   File "../gemrb/GUIScripts/MetaClasses.py", line 44, in handler
[Python/ERROR]:     raise type(e)(str(e) + "\nMethod Docs:\n" + str(f.__doc__))
[Python/ERROR]: RuntimeError: Cannot construct object with null ref.
```

Here it at least doesn't make much sense, since we swapped the small TA for the big dialog one already.

**Comment by bradallred** [comment]
@MarcelHB can you still reproduce this?

**Comment by MarcelHB** [comment]
Looks good.
