### ISSUE TITLE
[subviews] Assertion error when drawing vert. lines

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#579]
While trying to get #577 running, I noticed two things:

- IWD2 crashes immediately upon entering the game.
- BG2 crashes when trying to draw a selection rectangle.

For both cases, the error is the same:
```gdb
[ResourceManagerAssertion failed: dst.imp->pixel < dstend.imp->pixel, file ./gemrb_subviews/gemrb/plugins/SDLVideo/Pixels.h, line 620

Thread 1 hit Breakpoint 1, 0x000007fefcdb5383 in msvcrt!abort ()
   from C:\Windows\system32\msvcrt.dll
(gdb) bt
#0  0x000007fefcdb5383 in msvcrt!abort () from C:\Windows\system32\msvcrt.dll
#1  0x000007fefcdb23ab in msvcrt!_assert ()
   from C:\Windows\system32\msvcrt.dll
#2  0x0000000002d8b5ba in GemRB::WriteColor<GemRB::SrcRGBA<false> > (
    mask=..., blender=..., dstend=..., dst=..., srcc=...)
    at ./gemrb_subviews/gemrb/plugins/SDLVideo/Pixels.h:497
#3  GemRB::DrawVLineSurface<false> (dst=dst@entry=0x2e85d0, p=...,
    y2=<optimized out>, y2@entry=289, clip=..., color=...)
    at ./gemrb_subviews/gemrb/plugins/SDLVideo/SDLSurfaceDrawing.h:211
#4  0x0000000002d86704 in GemRB::SDL12VideoDriver::DrawRect (this=0x2ebc40,
    rgn=..., color=..., fill=<optimized out>, flags=0)
    at ./gemrb_subviews/gemrb/core/Region.h:111
#5  0x0000000069e9ecfd in GemRB::GameControl::DrawSelf (this=0x926dd0,
    screen=...)
    at ./gemrb_subviews/gemrb/core/GUI/GameControl.cpp:566
#6  0x0000000069eb2208 in GemRB::View::Draw (this=0x926dd0)
    at D:/Programme/MSYS2/mingw64/include/c++/9.2.0/bits/stl_iterator.h:806
#7  0x0000000069eb2179 in GemRB::View::DrawSubviews (this=0x2e81c0)
    at ./gemrb_subviews/gemrb/core/GUI/View.cpp:176
#8  GemRB::View::Draw (this=0x2e81c0)
    at ./gemrb_subviews/gemrb/core/GUI/View.cpp:234
#9  0x0000000069eb2179 in GemRB::View::DrawSubviews (this=0x2e80d0)
    at ./gemrb_subviews/gemrb/core/GUI/View.cpp:176
#10 GemRB::View::Draw (this=0x2e80d0)
    at ./gemrb_subviews/gemrb/core/GUI/View.cpp:234
#11 0x0000000069eb6404 in GemRB::WindowManager::DrawWindows (this=0x2e7870)
    at ./gemrb_subviews/gemrb/core/GUI/WindowManager.cpp:534
#12 0x0000000069ef7d43 in GemRB::Interface::Main (this=0x2e24b0)
    at ./gemrb_subviews/gemrb/core/Interface.cpp:978
#13 0x0000000000402da8 in main (argc=3, argv=0x922a20)
    at ./gemrb_subviews/gemrb/GemRB.cpp:99
```

**Comment by bradallred** [comment]
how about now?

**Comment by MarcelHB** [comment]
Looks good.
