### ISSUE TITLE
[subviews] crash when pressing some mouse button beyond the third

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#594]
I haven't managed to reproduce this yet, but it got triggered by just right-clicking in the game area. The event data looks a bit suspicious though.
```
gemrb: gemrb/core/GUI/EventMgr.cpp:256: static GemRB::Event GemRB::EventMgr::CreateMouseBtnEvent(const GemRB::Point&, GemRB::EventButton, bool, int): Assertion `btn' failed.             

Breakpoint 1, 0x00007ffff7692436 in abort () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7692436 in abort () from /lib64/libc.so.6
#1  0x00007ffff7692431 in __assert_fail_base.cold () from /lib64/libc.so.6
#2  0x00007ffff76a1592 in __assert_fail () from /lib64/libc.so.6
#3  0x00007ffff7d77949 in GemRB::EventMgr::CreateMouseBtnEvent (pos=..., btn=0 '\000', down=true, 
    mod=0) at gemrb/core/GUI/EventMgr.cpp:256
#4  0x00007ffff6653d6a in GemRB::SDLVideoDriver::ProcessEvent (this=0x437610, event=...)
    at gemrb/plugins/SDLVideo/SDLVideo.cpp:229
#5  0x00007ffff665dc19 in GemRB::SDL12VideoDriver::ProcessEvent (this=0x437610, event=...)
    at gemrb/plugins/SDLVideo/SDL12Video.cpp:589
#6  0x00007ffff6653891 in GemRB::SDLVideoDriver::PollEvents (this=0x437610)
    at gemrb/plugins/SDLVideo/SDLVideo.cpp:64
#7  0x00007ffff7eece62 in GemRB::Video::SwapBuffers (this=0x437610, fpscap=30)
    at gemrb/core/Video.cpp:154
#8  0x00007ffff7e20d2f in GemRB::Interface::Main (this=0x417330)
    at gemrb/core/Interface.cpp:993
#9  0x0000000000401314 in main (argc=3, argv=0x7fffffffdc18)
    at gemrb/GemRB.cpp:99
(gdb) f 3
#3  0x00007ffff7d77949 in GemRB::EventMgr::CreateMouseBtnEvent (pos=..., btn=0 '\000', down=true, 
    mod=0) at gemrb/core/GUI/EventMgr.cpp:256
256             assert(btn);
(gdb) list
251             Taps.erase(monitor);
252     }
253
254     Event EventMgr::CreateMouseBtnEvent(const Point& pos, EventButton btn, bool down, int mod)
255     {
256             assert(btn);
257
258             Event e = CreateMouseMotionEvent(pos, mod);
259
260             if (down) {
(gdb) f 5
#5  0x00007ffff665dc19 in GemRB::SDL12VideoDriver::ProcessEvent (this=0x437610, event=...)
    at gemrb/plugins/SDLVideo/SDL12Video.cpp:589
589             return SDLVideoDriver::ProcessEvent(event);
(gdb) p event
$1 = (const SDL_Event &) @0x7fffffffd910: {type = 5 '\005', active = {type = 5 '\005', 
    gain = 0 '\000', state = 9 '\t'}, key = {type = 5 '\005', which = 0 '\000', state = 9 '\t', 
    keysym = {scancode = 208 '\320', sym = SDLK_UNKNOWN, mod = KMOD_NONE, unicode = 0}}, motion = {
    type = 5 '\005', which = 0 '\000', state = 9 '\t', x = 208, y = 333, xrel = 0, yrel = 0}, 
  button = {type = 5 '\005', which = 0 '\000', button = 9 '\t', state = 1 '\001', x = 208, y = 333}, 
  jaxis = {type = 5 '\005', which = 0 '\000', axis = 9 '\t', value = 208}, jball = {type = 5 '\005', 
    which = 0 '\000', ball = 9 '\t', xrel = 208, yrel = 333}, jhat = {type = 5 '\005', 
    which = 0 '\000', hat = 9 '\t', value = 1 '\001'}, jbutton = {type = 5 '\005', which = 0 '\000', 
    button = 9 '\t', state = 1 '\001'}, resize = {type = 5 '\005', w = 21823696, h = 0}, expose = {
    type = 5 '\005'}, quit = {type = 5 '\005'}, user = {type = 5 '\005', code = 21823696, data1 = 0x0, 
    data2 = 0x0}, syswm = {type = 5 '\005', msg = 0x0}}
```

**Comment by lynxlynxlynx** [comment]
Scratch that, it's a different button. This mouse has two side ones extra and I must've pressed that.  One of them works (as a normal click), the other causes the crash.

**Comment by bradallred** [comment]
I couldn't reproduce, but the stack trace is clear enough that this should fix it.
