### ISSUE TITLE
[subviews] Crash on moving around the cursor/viewport

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#649]
**Describe the bug**
The latest changes on wall polygons seem to be reponsible for some crash. Not sure how easy to reproduce somewhere else, but this works:

**To Reproduce**
Steps to reproduce the behavior in my case.
1. I load PST, a savegame on AR0508.
2. I send the party to somewhere.
3. I move the cursor over some wall regions, i. e. where the blocked cursor appears.
4. I try to move the viewport by moving the cursor to one of the edges, some area I had not moved to in the ongoing session.

No claim to be the minimal test case, but this seems to reproduce it realiably.

```gdb
Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000069f25084 in __gnu_cxx::__atomic_add (__mem=0xaf000000cc, __val=1)
    at ./mingw64/include/c++/9.3.0/ext/atomicity.h:53
53        { __atomic_fetch_add(__mem, __val, __ATOMIC_ACQ_REL); }
(gdb) bt
#0  0x0000000069f25084 in __gnu_cxx::__atomic_add (__mem=0xaf000000cc,
    __val=1)
    at ./mingw64/include/c++/9.3.0/ext/atomicity.h:53
#1  0x0000000069f25148 in __gnu_cxx::__atomic_add_dispatch (
    __mem=0xaf000000cc, __val=1)
    at ./mingw64/include/c++/9.3.0/ext/atomicity.h:96
#2  0x0000000069fece81 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_add_ref_copy (this=0xaf000000c4)
    at ./mingw64/include/c++/9.3.0/bits/shared_ptr_base.h:139
#3  0x0000000069fe9e69 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count (this=0x13dd5f38, __r=...)
    at ./mingw64/include/c++/9.3.0/bits/shared_ptr_base.h:737
#4  0x0000000069fe8546 in std::__shared_ptr<GemRB::Wall_Polygon, (__gnu_cxx::_Lock_policy)2>::__shared_ptr (this=0x13dd5f30)
    at ./mingw64/include/c++/9.3.0/bits/shared_ptr_base.h:1167
#5  0x0000000069fda560 in std::shared_ptr<GemRB::Wall_Polygon>::shared_ptr (
    this=0x13dd5f30)
    at ./mingw64/include/c++/9.3.0/bits/shared_ptr.h:129
#6  0x0000000069fb9395 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::shared_ptr<GemRB::Wall_Polygon> > >::construct<std::shared_ptr<GemRB::Wall_Polygon>, std::shared_ptr<GemRB::Wall_Polygon> const&> (this=0x22f470, __p=0x13dd5f30)
    at ./mingw64/include/c++/9.3.0/ext/new_allocator.h:147
#7  0x0000000069ff2486 in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::shared_ptr<GemRB::Wall_Polygon> > > >::construct<std::shared_ptr<GemRB::Wall_Polygon>, std::shared_ptr<GemRB::Wall_Polygon> const&> (__a=...,
    __p=0x13dd5f30)
    at ./mingw64/include/c++/9.3.0/bits/alloc_traits.h:484
#8  0x000000006a03533c in std::_Rb_tree<std::shared_ptr<GemRB::Wall_Polygon>, std::shared_ptr<GemRB::Wall_Polygon>, std::_Identity<std::shared_ptr<GemRB::Wall_Polygon> >, std::less<std::shared_ptr<GemRB::Wall_Polygon> >, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::_M_construct_node<std::shared_ptr<GemRB::Wall_Polygon> const&> (this=0x22f470, __node=0x13dd5f10)
    at ./mingw64/include/c++/9.3.0/bits/stl_tree.h:614
#9  0x000000006a03527f in std::_Rb_tree<std::shared_ptr<GemRB::Wall_Polygon>, std::shared_ptr<GemRB::Wall_Polygon>, std::_Identity<std::shared_ptr<GemRB::Wall_Polygon> >, std::less<std::shared_ptr<GemRB::Wall_Polygon> >, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::_M_create_node<std::shared_ptr<GemRB::Wall_Polygon> const&> (this=0x22f470)
    at ./mingw64/include/c++/9.3.0/bits/stl_tree.h:631
#10 0x0000000069fd6264 in std::_Rb_tree<std::shared_ptr<GemRB::Wall_Polygon>, std::shared_ptr<GemRB::Wall_Polygon>, std::_Identity<std::shared_ptr<GemRB::Wall_Polygon> >, std::less<std::shared_ptr<GemRB::Wall_Polygon> >, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::_Alloc_node::operator()<std::shared_ptr<GemRB::Wall_Polygon> const&> (this=0x22f348, __arg=...)
    at ./mingw64/include/c++/9.3.0/bits/stl_tree.h:548
#11 0x000000006a03506f in std::_Rb_tree<std::shared_ptr<GemRB::Wall_Polygon>, std::shared_ptr<GemRB::Wall_Polygon>, std::_Identity<std::shared_ptr<GemRB::Wall_Polygon> >, std::less<std::shared_ptr<GemRB::Wall_Polygon> >, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::_M_insert_<std::shared_ptr<GemRB::Wall_Polygon> const&, std::_Rb_tree<std::shared_ptr<GemRB::Wall_Polygon>, std::shared_ptr<GemRB::Wall_Polygon>, std::_Identity<std::shared_ptr<GemRB::Wall_Polygon> >, std::less<std::shared_ptr<GemRB::Wall_Polygon> >, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::_Alloc_node> (this=0x22f470, __x=0x0,
    __p=0x13dd5910, __v=..., __node_gen=...)
    at ./mingw64/include/c++/9.3.0/bits/stl_tree.h:1810
#12 0x000000006a0353cd in std::_Rb_tree<std::shared_ptr<GemRB::Wall_Polygon>, std::shared_ptr<GemRB::Wall_Polygon>, std::_Identity<std::shared_ptr<GemRB::Wall_Polygon> >, std::less<std::shared_ptr<GemRB::Wall_Polygon> >, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::_M_insert_unique_<std::shared_ptr<GemRB::Wall_Polygon> const&, std::_Rb_tree<std::shared_ptr<GemRB::Wall_Polygon>, std::shared_ptr<GemRB::Wall_Polygon>, std::_Identity<std::shared_ptr<GemRB::Wall_Polygon> >, std::less<std::shared_ptr<GemRB::Wall_Polygon> >, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::_Alloc_node> (this=0x22f470,
    __position=..., __v=..., __node_gen=...)
    at ./mingw64/include/c++/9.3.0/bits/stl_tree.h:2263
#13 0x000000006a035484 in std::_Rb_tree<std::shared_ptr<GemRB::Wall_Polygon>, std::shared_ptr<GemRB::Wall_Polygon>, std::_Identity<std::shared_ptr<GemRB::Wall_Polygon> >, std::less<std::shared_ptr<GemRB::Wall_Polygon> >, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::_M_insert_range_unique<__gnu_cxx::__normal_iterator<std::shared_ptr<GemRB::Wall_Polygon> const*, std::vector<std::shared_ptr<GemRB::Wall_Polygon>, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > > > > (this=0x22f470, __first=..., __last=...)
    at ./mingw64/include/c++/9.3.0/bits/stl_tree.h:1113
#14 0x0000000069ffd91b in std::set<std::shared_ptr<GemRB::Wall_Polygon>, std::less<std::shared_ptr<GemRB::Wall_Polygon> >, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::insert<__gnu_cxx::__normal_iterator<std::shared_ptr<GemRB::Wall_Polygon> const*, std::vector<std::shared_ptr<GemRB::Wall_Polygon>, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > > > > (this=0x22f470,
    __first=..., __last=...)
    at ./mingw64/include/c++/9.3.0/bits/stl_set.h:567
#15 0x0000000069f29904 in GemRB::Map::WallsCoveringRegion (this=0xee65920,
    r=...) at ./gemrb_subviews/gemrb/core/Map.cpp:1341
#16 0x0000000069f2bfb6 in GemRB::Map::RedrawStencils (this=0xee65920, vp=...)
    at ./gemrb_subviews/gemrb/core/Map.cpp:2062
#17 0x0000000069f28c56 in GemRB::Map::DrawMap (this=0xee65920, viewport=...,
    debugFlags=0 '\000')
    at ./gemrb_subviews/gemrb/core/Map.cpp:1136
#18 0x0000000069ea505f in GemRB::GameControl::DrawSelf (this=0xd9fadb0,
    screen=...)
    at ./gemrb_subviews/gemrb/core/GUI/GameControl.cpp:528
#19 0x0000000069ebe8d1 in GemRB::View::Draw (this=0xd9fadb0)
    at ./gemrb_subviews/gemrb/core/GUI/View.cpp:223
#20 0x0000000069ebe571 in GemRB::View::DrawSubviews (this=0x5828d0)
    at ./gemrb_subviews/gemrb/core/GUI/View.cpp:176
#21 0x0000000069ebe957 in GemRB::View::Draw (this=0x5828d0)
    at ./gemrb_subviews/gemrb/core/GUI/View.cpp:234
#22 0x0000000069ebe571 in GemRB::View::DrawSubviews (this=0x5827e0)
    at ./gemrb_subviews/gemrb/core/GUI/View.cpp:176
#23 0x0000000069ebe957 in GemRB::View::Draw (this=0x5827e0)
    at ./gemrb_subviews/gemrb/core/GUI/View.cpp:234
#24 0x0000000069ec361f in GemRB::WindowManager::DrawWindows (this=0x581f80)
    at ./gemrb_subviews/gemrb/core/GUI/WindowManager.cpp:505
#25 0x0000000069f0cc5a in GemRB::Interface::Main (this=0x5724b0)
    at ./gemrb_subviews/gemrb/core/Interface.cpp:968
#26 0x0000000000401695 in main (argc=3, argv=0x6750b0)
    at ./gemrb_subviews/gemrb/GemRB.cpp:99
```

**Comment by MarcelHB** [comment]
I can produce a 2nd case, in a similar but not identical case:

```gdb
Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000069fcb0dc in std::__shared_ptr<GemRB::Wall_Polygon, (__gnu_cxx::_Lock_policy)2>::get (this=0x0)
    at ./mingw64/include/c++/9.3.0/bits/shared_ptr_base.h:1310
1310          { return _M_ptr; }
(gdb) bt
#0  0x0000000069fcb0dc in std::__shared_ptr<GemRB::Wall_Polygon, (__gnu_cxx::_Lock_policy)2>::get (this=0x0)
    at ./mingw64/include/c++/9.3.0/bits/shared_ptr_base.h:1310
#1  0x000000006a065242 in std::operator< <GemRB::Wall_Polygon, GemRB::Wall_Polygon> (__a=..., __b=...)
    at ./mingw64/include/c++/9.3.0/bits/shared_ptr.h:418
#2  0x0000000069fce894 in std::less<std::shared_ptr<GemRB::Wall_Polygon> >::operator() (this=0x22f470, __x=..., __y=...)
    at ./mingw64/include/c++/9.3.0/bits/stl_function.h:386
#3  0x000000006a03569a in std::_Rb_tree<std::shared_ptr<GemRB::Wall_Polygon>, std::shared_ptr<GemRB::Wall_Polygon>, std::_Identity<std::shared_ptr<GemRB::Wall_Polygon> >, std::less<std::shared_ptr<GemRB::Wall_Polygon> >, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::_M_get_insert_hint_unique_pos (
    this=0x22f470, __position=..., __k=...)
    at ./mingw64/include/c++/9.3.0/bits/stl_tree.h:2198
#4  0x000000006a035395 in std::_Rb_tree<std::shared_ptr<GemRB::Wall_Polygon>, std::shared_ptr<GemRB::Wall_Polygon>, std::_Identity<std::shared_ptr<GemRB::Wall_Polygon> >, std::less<std::shared_ptr<GemRB::Wall_Polygon> >, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::_M_insert_unique_<std::shared_ptr<GemRB::Wall_Polygon> const&, std::_Rb_tree<std::shared_ptr<GemRB::Wall_Polygon>, std::shared_ptr<GemRB::Wall_Polygon>, std::_Identity<std::shared_ptr<GemRB::Wall_Polygon> >, std::less<std::shared_ptr<GemRB::Wall_Polygon> >, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::_Alloc_node> (this=0x22f470,
    __position=..., __v=..., __node_gen=...)
    at ./mingw64/include/c++/9.3.0/bits/stl_tree.h:2257
#5  0x000000006a035484 in std::_Rb_tree<std::shared_ptr<GemRB::Wall_Polygon>, std::shared_ptr<GemRB::Wall_Polygon>, std::_Identity<std::shared_ptr<GemRB::Wall_Polygon> >, std::less<std::shared_ptr<GemRB::Wall_Polygon> >, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::_M_insert_range_unique<__gnu_cxx::__normal_iterator<std::shared_ptr<GemRB::Wall_Polygon> const*, std::vector<std::shared_ptr<GemRB::Wall_Polygon>, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > > > > (this=0x22f470, __first=..., __last=...)
    at ./mingw64/include/c++/9.3.0/bits/stl_tree.h:1113
#6  0x0000000069ffd91b in std::set<std::shared_ptr<GemRB::Wall_Polygon>, std::less<std::shared_ptr<GemRB::Wall_Polygon> >, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > >::insert<__gnu_cxx::__normal_iterator<std::shared_ptr<GemRB::Wall_Polygon> const*, std::vector<std::shared_ptr<GemRB::Wall_Polygon>, std::allocator<std::shared_ptr<GemRB::Wall_Polygon> > > > > (this=0x22f470,
    __first=..., __last=...)
    at ./mingw64/include/c++/9.3.0/bits/stl_set.h:567
#7  0x0000000069f29904 in GemRB::Map::WallsCoveringRegion (this=0xe937de0,
    r=...) at ./gemrb_subviews/gemrb/core/Map.cpp:1341
#8  0x0000000069f2bfb6 in GemRB::Map::RedrawStencils (this=0xe937de0, vp=...)
    at ./gemrb_subviews/gemrb/core/Map.cpp:2062
#9  0x0000000069f28c56 in GemRB::Map::DrawMap (this=0xe937de0, viewport=...,
    debugFlags=0 '\000')
    at ./gemrb_subviews/gemrb/core/Map.cpp:1136
#10 0x0000000069ea505f in GemRB::GameControl::DrawSelf (this=0xd92d5f0,
    screen=...)
    at ./gemrb_subviews/gemrb/core/GUI/GameControl.cpp:528
#11 0x0000000069ebe8d1 in GemRB::View::Draw (this=0xd92d5f0)
    at ./gemrb_subviews/gemrb/core/GUI/View.cpp:223
#12 0x0000000069ebe571 in GemRB::View::DrawSubviews (this=0x5128e0)
    at ./gemrb_subviews/gemrb/core/GUI/View.cpp:176
#13 0x0000000069ebe957 in GemRB::View::Draw (this=0x5128e0)
    at ./gemrb_subviews/gemrb/core/GUI/View.cpp:234
#14 0x0000000069ebe571 in GemRB::View::DrawSubviews (this=0x5127f0)
    at ./gemrb_subviews/gemrb/core/GUI/View.cpp:176
#15 0x0000000069ebe957 in GemRB::View::Draw (this=0x5127f0)
    at ./gemrb_subviews/gemrb/core/GUI/View.cpp:234
#16 0x0000000069ec361f in GemRB::WindowManager::DrawWindows (this=0x511f90)
    at ./gemrb_subviews/gemrb/core/GUI/WindowManager.cpp:505
#17 0x0000000069f0cc5a in GemRB::Interface::Main (this=0x5024b0)
    at ./gemrb_subviews/gemrb/core/Interface.cpp:968
#18 0x0000000000401695 in main (argc=3, argv=0x3c50b0)
    at ./gemrb_subviews/gemrb/GemRB.cpp:99
```

**Comment by MarcelHB** [comment]
Looks like some out-of-bounds, in the latter case, frame 7, I get:
```
(gdb) p y
$1 = 3
(gdb) p x
$2 = 1
(gdb) p pitch
$3 = 4
(gdb) p wallGroups.size()
$4 = 12
```

**Comment by bradallred** [comment]
if the problem only occurs in PST it probably means it uses a different group size

**Comment by bradallred** [comment]
it is really easy to tell this is the case, load any save (possibly the map cant be evenly divisible by 640x480, but i do not know) and open the map and move the viewport to the bottom right corner.

using tools like asan/ubsan with immediately show the error instead of possibly getting randomly "lucky".

**Comment by bradallred** [comment]
that fixes the issue i'm seeing. You?

**Comment by MarcelHB** [comment]
I still get a crash in my primary case, like
```1341                            set.insert(group.begin(), group.end());
(gdb) p x
$1 = 1
(gdb) p y
$2 = 8
(gdb) p pitch
$3 = 6
(gdb) p wallGroups.size()
$4 = 48
```

**Comment by bradallred** [comment]
can I get a save with instructions?

**Comment by bradallred** [comment]
@MarcelHB how is that now?

**Comment by MarcelHB** [comment]
Cannot reproduce anymore :+1:
