### ISSUE TITLE
[TOB] Segmentation fault during combat

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#886]
#### Bug description
During combat or just after, segmentation fault is occurring 

GemRB version: master

#### Steps to reproduce
1. Load save (here in mind flayer area (Sendai's Enclave))
2. enter in mind flayer area
3. fight opponent

[000000028-segfault mind flayer.zip](https://github.com/gemrb/gemrb/files/5009983/000000028-segfault.mind.flayer.zip)

#### BT trace
[Actor/COMBAT]: Damage animation type: 1                                                         
[ResourceManager]: Found 'mumb.2da' in 'chitin.key'.                                             
[2DAImporter/WARNING]: Bad signature (mumb.2da)! Complaining, but not ignoring...                
[Actor]: Getting sound 2da mumb entry: Battle_Cry                                                
[Actor/DEBUG]: Performattack for Umber Hulk, target is: Minsc                                    
[Attack/COMBAT]: (Main) Left: 2 | Next: 45351406 [Missed]                                        
[ResourceManager]: Found 'mumbg21.bam' in 'chitin.key'.                                          
[ResourceManager]: Found 'mming1.bam' in 'chitin.key'.                                           
[ResourceManager]: Found 'mmin.2da' in 'chitin.key'.                                             
[2DAImporter/WARNING]: Bad signature (mmin.2da)! Complaining, but not ignoring...                
[Actor]: Getting sound 2da mmin entry: Battle_Cry                                                
[FindPath/DEBUG]: s = (655, 825), d = (281, 627), caller = Vampiric Illithid, dist = 0, size = 2 
[FindPath/DEBUG]: Pathing failed for Vampiric Illithid                                           
[FindPath/DEBUG]: s = (814, 625), d = (281, 627), caller = Vampiric Illithid, dist = 0, size = 2 
[FindPath/DEBUG]: Pathing failed for Vampiric Illithid                                           
[Actor/DEBUG]: Performattack for Ulitharid, target is: Anomen                                    
[Attack/COMBAT]: (Main) Left: 2 | Next: 45351415 [Missed]                                        
[ResourceManager]: Found 'mumbg1.bam' in 'chitin.key'.                                           
[Actor/DEBUG]: Performattack for Jaheira, target is: Ulitharid                                   
[ResourceManager]: Searching for 'swi_05b'...                                                    
[ResourceManager]: Found 'swi_05b.wav' in 'chitin.key'.                                          
[Attack/COMBAT]: (Main) Left: 0 | Next: 45351431 [Hit]                                           
[Actor/DEBUG]: Performattack for Imoen, target is: Ulitharid                                     
[ResourceManager]: Searching for 'swi_02b'...                                                    
[ResourceManager]: Found 'swi_02b.wav' in 'chitin.key'.                                          
[Attack/COMBAT]: (Main) Left: 0 | Next: 45351449 [Hit]                                           
[ModifyDamage/COMBAT]: Resisted 6 of 13 at 50% resistance to 128                                 
[Actor/COMBAT]: 7 unknown damage taken.                                                          

[Actor/COMBAT]: Damage animation type: 1                                                         
[Sprite2D]: Frame fetched while animation is inactive2!                                          

Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.                                    
0x00007ffff7e81297 in GemRB::Animation::NextFrame() ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
(gdb) bt
#0  0x00007ffff7e81297 in GemRB::Animation::NextFrame() ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#1  0x00007ffff7f4f14b in GemRB::ScriptedAnimation::HandlePhase(GemRB::Sprite2D*&) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#2  0x00007ffff7f4f2fd in GemRB::ScriptedAnimation::Draw(GemRB::Region const&, GemRB::Point const&, GemRB::Color const&, GemRB::Map*, int, int, int) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#3  0x00007ffff7f26278 in GemRB::Actor::DrawVideocells(GemRB::Region const&, std::vector<GemRB::ScriptedAnimation*, std::allocator<GemRB::ScriptedAnimation*> >&, GemRB::Color const&) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#4  0x00007ffff7f2dbb9 in GemRB::Actor::Draw(GemRB::Region const&) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#5  0x00007ffff7f09bf0 in GemRB::Map::DrawMap(GemRB::Region) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#6  0x00007ffff7ea0704 in GemRB::GameControl::DrawInternal(GemRB::Region&) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#7  0x00007ffff7e99239 in GemRB::Control::Draw(unsigned short, unsigned short) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#8  0x00007ffff7eb25b7 in GemRB::Window::DrawWindow() ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
--Type <RET> for more, q to quit, c to continue without paging--
#9  0x00007ffff7eeade8 in GemRB::Interface::DrawWindows(bool) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#10 0x00007ffff7ef3832 in GemRB::Interface::Main() ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#11 0x0000555555555209 in ?? ()
#12 0x00007ffff798de1b in __libc_start_main () from /lib64/libc.so.6
#13 0x00005555555552ba in _start ()
(gdb) quit

another trace :

[GameScript]: Displaying string on: anomen                                                       
[Sprite2D]: Frame fetched while animation is inactive2!                                          
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e81297 in GemRB::Animation::NextFrame() ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
(gdb) bt
#0  0x00007ffff7e81297 in GemRB::Animation::NextFrame() ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#1  0x00007ffff7f4f14b in GemRB::ScriptedAnimation::HandlePhase(GemRB::Sprite2D*&) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#2  0x00007ffff7f4f2fd in GemRB::ScriptedAnimation::Draw(GemRB::Region const&, GemRB::Point const&, GemRB::Color const&, GemRB::Map*, int, int, int) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#3  0x00007ffff7f26278 in GemRB::Actor::DrawVideocells(GemRB::Region const&, std::vector<GemRB::ScriptedAnimation*, std::allocator<GemRB::ScriptedAnimation*> >&, GemRB::Color const&) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#4  0x00007ffff7f2dbb9 in GemRB::Actor::Draw(GemRB::Region const&) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#5  0x00007ffff7f09bf0 in GemRB::Map::DrawMap(GemRB::Region) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#6  0x00007ffff7ea0704 in GemRB::GameControl::DrawInternal(GemRB::Region&) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#7  0x00007ffff7e99239 in GemRB::Control::Draw(unsigned short, unsigned short) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#8  0x00007ffff7eb25b7 in GemRB::Window::DrawWindow() ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
--Type <RET> for more, q to quit, c to continue without paging--
#9  0x00007ffff7eeade8 in GemRB::Interface::DrawWindows(bool) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#10 0x00007ffff7ef3832 in GemRB::Interface::Main() ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.8.6-git
#11 0x0000555555555209 in ?? ()
#12 0x00007ffff798de1b in __libc_start_main () from /lib64/libc.so.6
#13 0x00005555555552ba in _start ()

**Comment by FrElvire** [comment]
The segfault begin with commit : 0e43f0f - don't tie VVC sounds to the animation phases
