### ISSUE TITLE
another vvc crash

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#891]
While trying to reproduce #890 in ar6000, I hit this:

```
terminate called after throwing an instance of 'std::bad_alloc'                                                                                     
  what():  std::bad_alloc                                                                                                                           

Thread 1 "gemrb" hit Breakpoint 1, __GI_abort () at abort.c:49
49      abort.c: No such file or directory.
(gdb) bt
#0  __GI_abort () at abort.c:49
#1  0x00007ffff7a905f6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff7a9c9ec in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7a9ca47 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7a9cca9 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7a90266 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7f07a7e in GemRB::Video::InitSpriteCover (this=0x5555555bf850, sc=0x5555572c2760, flags=2)
    at /home/kajak/games/gemrb/gemrb/core/Video.cpp:382
#7  0x00007ffff7e6d223 in GemRB::Map::BuildSpriteCover (this=0x55555639d9d0, x=902, y=1003, xpos=15720065, ypos=16642730, width=4278190394, 
    height=4278190111, flags=2, areaanim=false) at /home/kajak/games/gemrb/gemrb/core/Map.cpp:2075
#8  0x00007ffff7ee8b75 in GemRB::ScriptedAnimation::Draw (this=0x5555572aa240, screen=..., Pos=..., p_tint=..., area=0x55555639d9d0, dither=2, 
    orientation=14, height=77) at /home/kajak/games/gemrb/gemrb/core/ScriptedAnimation.cpp:706
#9  0x00007ffff7eb9b39 in GemRB::Actor::DrawVideocells (this=0x555555d656d0, screen=..., vvcCells=std::vector of length 5, capacity 8 = {...}, 
    tint=...) at /home/kajak/games/gemrb/gemrb/core/Scriptable/Actor.cpp:8309
#10 0x00007ffff7ebb998 in GemRB::Actor::Draw (this=0x555555d656d0, screen=...) at /home/kajak/games/gemrb/gemrb/core/Scriptable/Actor.cpp:8850
#11 0x00007ffff7e6a13b in GemRB::Map::DrawMap (this=0x55555639d9d0, screen=...) at /home/kajak/games/gemrb/gemrb/core/Map.cpp:1169
#12 0x00007ffff7db0125 in GemRB::GameControl::DrawInternal (this=0x55555564e610, screen=...)
    at /home/kajak/games/gemrb/gemrb/core/GUI/GameControl.cpp:500
#13 0x00007ffff7da9905 in GemRB::Control::Draw (this=0x55555564e610, x=64, y=0) at /home/kajak/games/gemrb/gemrb/core/GUI/Control.cpp:110
#14 0x00007ffff7dd9a95 in GemRB::Window::DrawWindow (this=0x555555d01380) at /home/kajak/games/gemrb/gemrb/core/GUI/Window.cpp:137
#15 0x00007ffff7e47e95 in GemRB::Interface::DrawWindows (this=0x55555556ce80, allow_delete=true)
    at /home/kajak/games/gemrb/gemrb/core/Interface.cpp:3177
#16 0x00007ffff7e3e29b in GemRB::Interface::Main (this=0x55555556ce80) at /home/kajak/games/gemrb/gemrb/core/Interface.cpp:1026
#17 0x0000555555555449 in main (argc=3, argv=0x7fffffffdc88) at /home/kajak/games/gemrb/gemrb/GemRB.cpp:101
(gdb) f 6
#6  0x00007ffff7f07a7e in GemRB::Video::InitSpriteCover (this=0x5555555bf850, sc=0x5555572c2760, flags=2)
    at /home/kajak/games/gemrb/gemrb/core/Video.cpp:382
382             sc->pixels = new unsigned char[sc->Width * sc->Height];
(gdb) p sc
$1 = (GemRB::SpriteCover *) 0x5555572c2760
(gdb) p sc->Width 
$2 = -16776902
(gdb) p sc->Height 
$3 = -16777185
```

Looks like we have some memory corruption. Perhaps another problem from the sound decoupling? I'll do the lazy thing and run coverity over current HEAD.

**Comment by fizzet** [comment]
Those line numbers don't really match up with what's on master...

**Comment by lynxlynxlynx** [comment]
Are they off-by-3? I had a similar check in to ensure phase doesn't cause crashes, but forgot to push before you fixed it.

**Comment by fizzet** [comment]
-3 would line up better, yes.

**Comment by lynxlynxlynx** [comment]
Yeah, could be a duplicate. I'll try to reproduce.

**Comment by lynxlynxlynx** [comment]
Can't reproduce, closing. :)
