### ISSUE TITLE
[subviews] Assertion error upon entering IWD2/BG2 inventory

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#923]
When I try to enter the inventory in IWD2 or BG2, I am greeted by the following assertion error:

```
[ResourAssertion failed: pal != palette, file D:/Sources/gemrb_subviews/gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp, line 139

Thread 1 hit Breakpoint 1, 0x00007ffb323bf1e7 in msvcrt!abort ()
   from C:\Windows\System32\msvcrt.dll
(gdb) bt
#0  0x00007ffb323bf1e7 in msvcrt!abort () from C:\Windows\System32\msvcrt.dll
#1  0x00007ffb323bbbc5 in msvcrt!_assert ()
   from C:\Windows\System32\msvcrt.dll
#2  0x00000000041a5c2a in GemRB::SDLSurfaceSprite2D::SetPalette (
    this=0x175afe40, pal=0x1dfb8730)
    at D:/Sources/gemrb_subviews/gemrb/core/Palette.h:79
#3  0x0000000068408f3e in GemRB::ControlAnimation::UpdateAnimationSprite (
    this=0x1dfb7c60)
    at D:/Sources/gemrb_subviews/gemrb/core/ControlAnimation.cpp:144
#4  0x00000000684091aa in GemRB::ControlAnimation::SetPaletteGradients (
    this=<optimized out>, col=col@entry=0x69d830)
    at D:/Sources/gemrb_subviews/gemrb/core/ControlAnimation.cpp:162
#5  0x000000000178be6f in GemRB_Control_SetAnimationPalette (
    self=<optimized out>, args=<optimized out>)
    at D:/Sources/gemrb_subviews/gemrb/plugins/GUIScript/GUIScript.cpp:3688
#6  0x000000006cee133e in libpython2.7!PyEval_EvalFrameEx ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#7  0x000000006cee49de in libpython2.7!PyEval_EvalCodeEx ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#8  0x000000006cee2128 in libpython2.7!PyEval_EvalFrameEx ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#9  0x000000006cee49de in libpython2.7!PyEval_EvalCodeEx ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#10 0x000000006ce70eee in libpython2.7!PyFrame_Fini ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#11 0x000000006ce4bef1 in libpython2.7!PyObject_Call ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#12 0x000000006cedb459 in libpython2.7!PyEval_CallObjectWithKeywords ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#13 0x00000000017971c9 in GemRB::CallPython<int, &GemRB::noop<int> > (
    function=<optimized out>, args=0x0, retVal=0x69deac)
    at D:/Sources/gemrb_subviews/gemrb/plugins/GUIScript/PythonCallbacks.h:42
#14 0x000000000179808a in GemRB::CallPython (args=0x0, function=0xffffffff)
    at D:/Sources/gemrb_subviews/gemrb/plugins/GUIScript/PythonCallbacks.h:68
#15 GemRB::PythonComplexCallback<void, GemRB::Control*>::operator() (arg=
    0x1dfa2390, this=0x1dfb2930)
    at D:/Sources/gemrb_subviews/gemrb/plugins/GUIScript/PythonCallbacks.h:128
#16 GemRB::PythonComplexCallback<void, GemRB::Control*>::operator() (
    arg=0x1dfa2390, this=0x1dfb2930)
    at D:/Sources/gemrb_subviews/gemrb/plugins/GUIScript/PythonCallbacks.h:123
#17 std::__invoke_impl<void, GemRB::PythonComplexCallback<void, GemRB::Control*>&, GemRB::Control*> (__f=...)
    at C:/MSYS2/mingw64/include/c++/10.1.0/bits/invoke.h:60
#18 std::__invoke_r<void, GemRB::PythonComplexCallback<void, GemRB::Control*>&, GemRB::Control*> (__fn=...)
    at C:/MSYS2/mingw64/include/c++/10.1.0/bits/invoke.h:153
#19 std::_Function_handler<void (GemRB::Control*), GemRB::PythonComplexCallback<void, GemRB::Control*> >::_M_invoke(std::_Any_data const&, GemRB::Control*&&)
    (__functor=..., __args#0=<optimized out>)
    at C:/MSYS2/mingw64/include/c++/10.1.0/bits/std_function.h:291
#20 0x0000000068418f2d in std::function<void (GemRB::Control*)>::operator()(GemRB::Control*) const (__args#0=<optimized out>, this=0x1dfb28d8)
    at C:/MSYS2/mingw64/include/c++/10.1.0/bits/std_function.h:617
#21 GemRB::View::ActionResponder<GemRB::Control*>::Responder::operator() (
    responder=0x1dfa2390, this=0x1dfb28d8)
    at D:/Sources/gemrb_subviews/gemrb/core/GUI/ViewInterfaces.h:74
#22 GemRB::Control::PerformAction (this=this@entry=0x1dfa2390, key=...)
    at D:/Sources/gemrb_subviews/gemrb/core/GUI/Control.cpp:122
#23 0x000000006841993f in GemRB::Control::PerformAction (key=...,
    this=0x1dfa2390) at D:/Sources/gemrb_subviews/gemrb/core/GUI/View.h:181
#24 GemRB::Control::SetValue (val=<optimized out>, this=0x1dfa2390)
    at D:/Sources/gemrb_subviews/gemrb/core/GUI/Control.cpp:162
#25 GemRB::Control::SetValue (this=this@entry=0x1dfa2390, val=<optimized out>)
    at D:/Sources/gemrb_subviews/gemrb/core/GUI/Control.cpp:153
#26 0x000000000178c17d in GemRB_Control_SetVarAssoc (self=<optimized out>,
    args=<optimized out>)
    at D:/Sources/gemrb_subviews/gemrb/plugins/GUIScript/GUIScript.cpp:1932
#27 0x000000006cee133e in libpython2.7!PyEval_EvalFrameEx ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#28 0x000000006cee49de in libpython2.7!PyEval_EvalCodeEx ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#29 0x000000006cee2128 in libpython2.7!PyEval_EvalFrameEx ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#30 0x000000006cee49de in libpython2.7!PyEval_EvalCodeEx ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#31 0x000000006cee2128 in libpython2.7!PyEval_EvalFrameEx ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#32 0x000000006cee49de in libpython2.7!PyEval_EvalCodeEx ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#33 0x000000006cee2128 in libpython2.7!PyEval_EvalFrameEx ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#34 0x000000006cee49de in libpython2.7!PyEval_EvalCodeEx ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#35 0x000000006ce70eee in libpython2.7!PyFrame_Fini ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#36 0x000000006ce4bef1 in libpython2.7!PyObject_Call ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#37 0x000000006cedb459 in libpython2.7!PyEval_CallObjectWithKeywords ()
   from C:\MSYS2\mingw64\bin\libpython2.7.dll
#38 0x00000000017971c9 in GemRB::CallPython<int, &GemRB::noop<int> > (
    function=<optimized out>, args=0x47b4e60, retVal=0x69eaec)
    at D:/Sources/gemrb_subviews/gemrb/plugins/GUIScript/PythonCallbacks.h:42
#39 0x000000000179808a in GemRB::CallPython (args=0x47b4e60,
    function=0xffffffff)
    at D:/Sources/gemrb_subviews/gemrb/plugins/GUIScript/PythonCallbacks.h:68
#40 GemRB::PythonComplexCallback<void, GemRB::Control*>::operator() (
    arg=0x17570830, this=0x17fe10f0)
    at D:/Sources/gemrb_subviews/gemrb/plugins/GUIScript/PythonCallbacks.h:128
#41 GemRB::PythonComplexCallback<void, GemRB::Control*>::operator() (
    arg=0x17570830, this=0x17fe10f0)
    at D:/Sources/gemrb_subviews/gemrb/plugins/GUIScript/PythonCallbacks.h:123
#42 std::__invoke_impl<void, GemRB::PythonComplexCallback<void, GemRB::Control*>&, GemRB::Control*> (__f=...)
    at C:/MSYS2/mingw64/include/c++/10.1.0/bits/invoke.h:60
#43 std::__invoke_r<void, GemRB::PythonComplexCallback<void, GemRB::Control*>&, GemRB::Control*> (__fn=...)
    at C:/MSYS2/mingw64/include/c++/10.1.0/bits/invoke.h:153
#44 std::_Function_handler<void (GemRB::Control*), GemRB::PythonComplexCallback<void, GemRB::Control*> >::_M_invoke(std::_Any_data const&, GemRB::Control*&&)
    (__functor=..., __args#0=<optimized out>)
    at C:/MSYS2/mingw64/include/c++/10.1.0/bits/std_function.h:291
#45 0x0000000068418f2d in std::function<void (GemRB::Control*)>::operator()(GemRB::Control*) const (__args#0=<optimized out>, this=0x17fe47d8)
    at C:/MSYS2/mingw64/include/c++/10.1.0/bits/std_function.h:617
#46 GemRB::View::ActionResponder<GemRB::Control*>::Responder::operator() (
    responder=0x17570830, this=0x17fe47d8)
    at D:/Sources/gemrb_subviews/gemrb/core/GUI/ViewInterfaces.h:74
#47 GemRB::Control::PerformAction (this=this@entry=0x17570830, key=...)
    at D:/Sources/gemrb_subviews/gemrb/core/GUI/Control.cpp:122
#48 0x00000000684193ff in GemRB::Control::PerformAction (key=...,
    this=0x17570830) at D:/Sources/gemrb_subviews/gemrb/core/GUI/View.h:181
#49 GemRB::Control::OnMouseUp (this=0x17570830, me=..., mod=<optimized out>)
    at D:/Sources/gemrb_subviews/gemrb/core/GUI/Control.cpp:223
#50 0x0000000068438e84 in GemRB::View::MouseUp (this=0x17570830, me=...,
    mod=0) at D:/Sources/gemrb_subviews/gemrb/core/GUI/View.cpp:702
#51 0x000000006843bea2 in GemRB::Window::DispatchMouseUp (
    mod=<optimized out>, me=..., target=<optimized out>, this=0x47e2c00)
    at D:/Sources/gemrb_subviews/gemrb/core/GUI/Window.cpp:362
#52 GemRB::Window::DispatchEvent (this=0x47e2c00, event=...)
    at D:/Sources/gemrb_subviews/gemrb/core/GUI/Window.cpp:510
#53 0x000000006843ccf4 in GemRB::WindowManager::DispatchEvent (
    this=0x4b536b0, event=...)
    at D:/Sources/gemrb_subviews/gemrb/core/GUI/WindowManager.cpp:346
#54 0x000000006841c26a in std::function<bool (GemRB::Event const&)>::operator()(GemRB::Event const&) const (__args#0=..., this=0x18b84430)
    at C:/MSYS2/mingw64/include/c++/10.1.0/bits/std_function.h:617
#55 GemRB::EventMgr::DispatchEvent (this=<optimized out>, e=...)
    at D:/Sources/gemrb_subviews/gemrb/core/GUI/EventMgr.cpp:201
#56 0x00000000041a1be5 in GemRB::SDLVideoDriver::ProcessEvent (
    this=this@entry=0xebc4d0, event=...)
    at D:/Sources/gemrb_subviews/gemrb/plugins/SDLVideo/SDLVideo.cpp:235
#57 0x00000000041a9235 in GemRB::SDL20VideoDriver::ProcessEvent (
    this=0xebc4d0, event=...)
    at D:/Sources/gemrb_subviews/gemrb/plugins/SDLVideo/SDL20Video.cpp:683
#58 0x00000000041a13d3 in GemRB::SDLVideoDriver::PollEvents (this=0xebc4d0)
    at D:/Sources/gemrb_subviews/gemrb/plugins/SDLVideo/SDLVideo.cpp:65
#59 0x000000006848730d in GemRB::Interface::Main (this=0x775e90)
    at D:/Sources/gemrb_subviews/gemrb/core/Holder.h:86
#60 0x00000000004027d6 in main (argc=1, argv=0x7746e0)
    at D:/Sources/gemrb_subviews/gemrb/GemRB.cpp:101
```

**Comment by lynxlynxlynx** [comment]
iwd2 works for me, but I'm on sdl1.

**Comment by MarcelHB** [comment]
Is it really fixed? I still get the same error.

**Comment by bradallred** [comment]
I didn't test IWD2, but any remaining fixes will be the same if you want to send a PR

**Comment by bradallred** [comment]
that seems to work now
