### ISSUE TITLE
[subviews] SpriteRenderer crash 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#945]
pix ends up corrupted. It's quite quickly reproducible, but no clear reproduction pattern yet. 
```
Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.                                                                                       
0x00007ffff5c13cf4 in SRBlender<unsigned int, SRBlender_Alpha>::operator() (this=0x7fffffffc094, pix=<error reading variable>, r=223 '\337', 
    g=156 '\234', b=40 '(', a=254 '\376') at /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SpriteRenderer.inl:213
213             unsigned int dr = 1 + a*r + (255-a)*((pix >> RSHIFT) & 0xFF);

(gdb) bt
#0  0x00007ffff5c13cf4 in SRBlender<unsigned int, SRBlender_Alpha>::operator() (this=0x7fffffffc094, pix=<error reading variable>, r=223 '\337', 
    g=156 '\234', b=40 '(', a=254 '\376') at /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SpriteRenderer.inl:213
#1  0x00007ffff5c2392e in MaskedTintedBlend<unsigned int, SRTinter_Tint<true, true>, SRBlender<unsigned int, SRBlender_Alpha> > (
    dest=<error reading variable>, maskval=0 '\000', col=..., flags=65544, tint=..., blend=...)
    at /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SpriteRenderer.inl:235
#2  0x00007ffff5c19832 in BlitSpriteRLE_Total<unsigned int, SRTinter_Tint<true, true>, SRBlender<unsigned int, SRBlender_Alpha> > (
    rledata=0x555557514f1d "", pal=0x5555580fdbc0, transindex=0 '\000', dest=..., cover=..., flags=65544, tint=..., blend=...)
    at /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SpriteRenderer.inl:258
#3  0x00007ffff5c16626 in BlitSpriteRLE<SRBlender_Alpha, SRTinter_Tint<true, true> > (spr=0x55555751ad10, srect=..., dst=0x5555556e77f0, 
    drect=..., 
    cover=0x7ffff5c33470 <BlitSpriteRLE<SRBlender_Alpha, SRTinter_Tint<true, true> >(GemRB::Sprite2D const*, GemRB::Region const&, SDL_Surface*, GemRB::Region const&, GemRB::IAlphaIterator*, unsigned int, SRTinter_Tint<true, true> const&)::nomask>, flags=65544, tint=...)
    at /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SpriteRenderer.inl:378
#4  0x00007ffff5c145d9 in GemRB::SDL12VideoDriver::BlitSpriteBAMClipped (this=0x55555558b390, spr=0x55555751ad10, src=..., dst=..., flags=65544, 
    t=0x7fffffffc280) at /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDL12Video.cpp:188
#5  0x00007ffff5c0db2a in GemRB::SDLVideoDriver::BlitSpriteClipped (this=0x55555558b390, spr=0x55555751ad10, src=..., dst=..., flags=65544, 
    tint=0x7fffffffc280) at /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLVideo.cpp:591
#6  0x00007ffff5c0bb0e in GemRB::SDLVideoDriver::BlitGameSprite (this=0x55555558b390, spr=0x55555751ad10, x=234, y=192, flags=65544, tint=..., 
    clip=0x0) at /home/kajak/games/gemrb-subviews/gemrb/plugins/SDLVideo/SDLVideo.cpp:305
#7  0x00007ffff7ecf50e in GemRB::Video::BlitGameSpriteWithPalette (this=0x55555558b390, spr=0x55555751ad10, pal=0x5555580fdbc0, x=234, y=192, 
    flags=65544, tint=..., clip=0x0) at /home/kajak/games/gemrb-subviews/gemrb/core/Video.cpp:256
#8  0x00007ffff7e7c76d in GemRB::Actor::DrawActorSprite (this=0x555555bbc9c0, cx=234, cy=192, flags=65544, 
    anims=std::vector of length 4, capacity 4 = {...}, tint=...) at /home/kajak/games/gemrb-subviews/gemrb/core/Scriptable/Actor.cpp:8492
```

**Comment by lynxlynxlynx** [comment]
Couldn't hit this again now, so closing.
